### ISSUE TITLE
Server-side blazor template project can't work with BlazorStrap

### ISSUE THREAD

**Issue by howardgod** [chanan/BlazorStrap#101]
Environment:

- Visual Studio 2019 preview 16.2.0 Preview 3.0
- Dotnet core 3.0.100-preview6-012264
- Blazor 0.8.0(not quite sure)

Description: 
Looks like it fails to load the necessary BlazorStrap js files. And also makes local site.css & bootstrap.css failing to load up.

Reproduce step:

1. Create a Blazor server-side template project
2. @using BlazorStrap in _Imports.razor
3. add necessary js files in _Host.cshtml

Expect result: 
everything works fine.

Actual result:
![sc1](https://user-images.githubusercontent.com/10459637/60913486-187d6a80-a2ba-11e9-9415-1c452042b41a.PNG)

**Comment by chanan** [comment]
Some of those files are included in the default template and not by BlazorStrap, for example:

```
<link rel="stylesheet" href="/css/bootstrap/bootstrap.min.css" />
```

it's a bit weird that your project can't load them.

The one I know why its not loading is styled.js - you shouldn't need that, the ServerSideSample site uses it for the code snippets, but you shouldn't need that. As for the rest, I can't explain why your project won't run like I said above. Are you using preview6 of aspnet?

**Comment by howardgod** [comment]
Yes, it’s asp preview6 like I list in environment.
The weird part is that, when I remove blazorStrsp from nuget, everything works fine.

**Comment by chanan** [comment]
Can you post a failing project to Github?

**Comment by howardgod** [comment]
I guess I found out the problem
BlazorStrap v0.7.1: fail
BlazorStrap v1.0.0-preview6-19: work

looks like stable version got some problem with loading JS files.

**Comment by chanan** [comment]
Ah yes, 0.7.x worked back with Blazor0.7, v.1.0.0-previewX works with aspnet core previewX - I try to keep my version numbers in sync with aspnet, sorry about the confusion
