### ISSUE TITLE
Navbar overlays Jumbotron 

### ISSUE THREAD

**Issue by endeffects** [chanan/BlazorStrap#104]
I've noticed that the Navbar overlays the Jumbotron and all other contrainers.
Is this the expected behaviour?

![image](https://user-images.githubusercontent.com/13432569/60987843-b9b00380-a342-11e9-8fde-b842d586dad8.png)

**Comment by chanan** [comment]
Add your code here and I will check it out (might need to compare it to "plain" bootstrap to see)

**Comment by endeffects** [comment]
Thanks, i'm using the following code on my test page:

**Layout**

```
<Container IsFluid="true">
    <NavMenu />
</Container>

<Container IsFluid="true">
    @Body
</Container>
```

**Navbar**

```
<Navbar IsExpand="true" IsFixedTop="true" IsDark="true" Color="Color.Dark" class="navbar-expand-md">
    <NavbarBrand href="#">Brand</NavbarBrand>
    <NavbarToggler onclick="@(async () => await OnClick())" />
    <Collapse isOpen="@IsOpen" IsNavbar="true">
        <BlazorNav IsList="true" IsNavbar="true" class="mr-auto">
            <NavItem>
                <BlazorNavLink IsActive="true" href="#" Match="NavLinkMatch.All">Home</BlazorNavLink>
            </NavItem>
        </BlazorNav>
    </Collapse>
</Navbar>
```

**Page**

```
<Jumbotron IsFluid="true" class="d-none d-sm-block">
    <Container>
        <h1 class="display-4">Welcome</h1>
    </Container>
</Jumbotron>

<Container IsFluid="true">

</Container>
```

**Comment by jbomhold3** [comment]
Are you using a template or default bootstrap 4x?

**Comment by endeffects** [comment]
I'm using the default.

Index.html

```
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Welcome</title>
    <base href="/" />
    <link href="css/site.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
</head>
<body>
    <app>Loading...</app>
    <script src="_framework/blazor.webassembly.js"></script>
</body>
</html>
```

**Comment by chanan** [comment]
This does not happen in "vanilla" bootstrap. Looking to see if I can find the difference.

**Comment by chanan** [comment]
Ok, so no, I was wrong its like that in "vanilla" bootstrap as well. If you add fixed-top to the nav bar (IsFixed="true" in our case) it happens as well.

I think what you will need to do is manage the margin yourself like this:

```
@inherits LayoutComponentBase

<Container IsFluid="true">
    <NavMenu />
</Container>

<Container IsFluid="true" style="margin-top: 40px;">
    @Body
</Container>
```

Let me know if that works out for you

**Comment by endeffects** [comment]
Yes, this works for sure. I just thought that it is not a good idea to fix a responsive layout by defining pixel dimensions.

**Comment by endeffects** [comment]
The original example does not contain such a fix too.
https://getbootstrap.com/docs/4.3/examples/jumbotron/#

**Comment by endeffects** [comment]
Oh i think i found the difference. The sample has an other jumbotron padding defined:

**Bootstrap**

![image](https://user-images.githubusercontent.com/13432569/60993679-39dc6600-a34f-11e9-91fa-7678e7b363ee.png)

**BlazorStrap**

![image](https://user-images.githubusercontent.com/13432569/60993710-482a8200-a34f-11e9-9806-6a00b0e6d010.png)

**Comment by chanan** [comment]
did you mean does contain?

**Comment by endeffects** [comment]
no, or maybe i'm to dumb to find it.

**Comment by jbomhold3** [comment]
The fix comes from here
https://getbootstrap.com/docs/4.3/examples/jumbotron/jumbotron.css

**Comment by jbomhold3** [comment]
the 3.5 comes from 
1.5 = 1.5 Line height on the body.
1    = .5 rem top/bottom padding on Nav
1    = .5 rem top/bottom padding on .NavLink
For the total of 3.5

**Comment by jbomhold3** [comment]
@chanan this isn't a bug. We could do a bit of JS major to fix this for the user but really its a template thing and might cause issues for others.
