### ISSUE TITLE
Navbar Link has an active border

### ISSUE THREAD

**Issue by endeffects** [chanan/BlazorStrap#105]
I've noticed that an active dropdown link has a active link border that does not exists on the bootstrap sample. There seems to be also no other bootstrap styles defined in this sample.
Also the dropdown lables seems to be centered and not aligned left.

**Bootstrap**

https://getbootstrap.com/docs/4.3/examples/jumbotron/#

![image](https://user-images.githubusercontent.com/13432569/60991225-680b7700-a34a-11e9-9cf6-8f2b42f207df.png)

![image](https://user-images.githubusercontent.com/13432569/60991435-d3554900-a34a-11e9-9b79-aad9f07dd850.png)

**BlazorStrap**

![image](https://user-images.githubusercontent.com/13432569/60991357-b15bc680-a34a-11e9-9691-5cf600e2f2e9.png)

![image](https://user-images.githubusercontent.com/13432569/60991667-4232a200-a34b-11e9-9001-b9af2f108086.png)

**Comment by chanan** [comment]
Might be related to/fixed by #97

**Comment by chanan** [comment]
I would like to check this on the docs site post 1.0.0-preview6-21 which we will be releasing soon

**Comment by endeffects** [comment]
Solved with the latest version, thank you.
