### ISSUE TITLE
Create a TabManager

### ISSUE THREAD

**Issue by chanan** [chanan/BlazorStrap#106]
Create a TabManager to automatically switch between tabs like DropDownManager does for dropdowns

**Comment by jbomhold3** [comment]
Will work on this once P7 ships

**Comment by jbomhold3** [comment]
This is done. Functions much like matblazor.  Expect with a little more flexibility. I'll do pr tomarrow

**Comment by chanan** [comment]
Will be released in 1.0.0-preview6-21

**Comment by woodste36** [comment]
Is there any reason not to include the "active" class on the BSTab element as well as the hyperlink (BSTabLabel)?  CSS styling can be used for the tab element itself in some cases as well as the hyperlink.  Thought I would ask before potentially adding this.

**Comment by chanan** [comment]
@jbomhold3 Can you add that active link @woodste36 asked about above to your PR?

**Comment by jbomhold3** [comment]
active class added to BSTab exists in BSTabLabel. Am I missing something in this request?

**Comment by woodste36** [comment]
@jbomhold3 basically the active css property was only appearing on the "a" tag.  So therefore styling for "active" only appeared on the link itself and not the entire tab.  I just happened to run across this in our project when switching over to the new tab component (which is great by the way) and noticed the styling for the tabs was not rendering as originally designed.  Again thanks for adding. Much appreciated.

**Comment by jbomhold3** [comment]
Fixed in P7-1
