### ISSUE TITLE
BlazorButton ignores additional stylings

### ISSUE THREAD

**Issue by endeffects** [chanan/BlazorStrap#107]
I tried to set different stylings on the BlazorButton Component and it seems like, that the class styles got not applied to the html output.

**Sample**
`<BlazorButton ButtonType="ButtonType.Button" class="w-100">Create</BlazorButton>`

![image](https://user-images.githubusercontent.com/13432569/61075425-424da300-a41a-11e9-9d50-cb9f27f35d05.png)

**Comment by chanan** [comment]
My fault. When I refacotred the class creation I missed:

```
.AddClass(Class)
```

PS - Reminder to myself - check all components when fixing this issue
