### ISSUE TITLE
Preview 7 Upgrade

### ISSUE THREAD

**Issue by jbomhold3** [chanan/BlazorStrap#109]
- [x] Upgrade BlazorComponentUtilities
- [x] Upgrade BlazorPrettyCode ![blocking](https://img.shields.io/badge/-Blocking-red.svg)
- [X] Upgrade Other Dependencies 
- [X] Fix any breaking changes

**Comment by chanan** [comment]
I will upgrade BlazorPrettyCode as soon as preview7 comes out. 

Have you seen any other major changes in p7?

**Comment by jbomhold3** [comment]
System.Json   Prase and to String is now Deserialize and Serialize

**Comment by IvanJosipovic** [comment]
If you want to get ahead of the game, P7s builds are done.
NET Core SDK Version: 3.0.100-preview7-012802
Asp Net Core: 3.0.0-preview7.19353.9

All the info is here, https://github.com/dotnet/core-sdk
Installer: https://dotnetcli.blob.core.windows.net/dotnet/Sdk/release/3.0.1xx/dotnet-sdk-latest-win-x64.exe

add the following Nuget.config to the project:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <packageSources>
        <clear />
        <add key="NuGet.org" value="https://api.nuget.org/v3/index.json" />		
        <add key="dotnet-core" value="https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json" />
        <add key="extensions" value="https://dotnetfeed.blob.core.windows.net/aspnet-extensions/index.json" />
        <add key="entityframeworkcore" value="https://dotnetfeed.blob.core.windows.net/aspnet-entityframeworkcore/index.json" />
        <add key="aspnetcore-tooling" value="https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore-tooling/index.json" />
        <add key="aspnetcore" value="https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore/index.json" />
        <add key="aspnet-blazor" value="https://dotnetfeed.blob.core.windows.net/aspnet-blazor/index.json" />
    </packageSources>
</configuration>
```

**Comment by jbomhold3** [comment]
BlazorStrap is already updated to P7. I'm just pulling in the BlazorPrettyCode project directly at the moment.

**Comment by chanan** [comment]
I will wait till the actual release :)

**Comment by chanan** [comment]
Daniel Roth said preview7 is expected on July 23rd

**Comment by endeffects** [comment]
Does this version support none-string bindings to input controls also?
Preview6 throws an exception for such bindings:

> Microsoft.AspNetCore.Components.EventCallback<long>' to 'string'

**Comment by chanan** [comment]
I will add that as a separate issue. Binding in general to be honest has not been an easy subject (also in Blazor it changed a few times).

**Comment by jbomhold3** [comment]
With changes in P7, this should just work. We will test this more once we get an official release. I don't want to have to reinstall again. lol

**Comment by mihaimyh** [comment]
I've created a [PR](https://github.com/chanan/BlazorStrap/pull/129) to upgrade to P7.

**Comment by endeffects** [comment]
Thanks for the update and the great support. :)
