### ISSUE TITLE
Error updating to Blazor 0.5.0

### ISSUE THREAD

**Issue by chanan** [chanan/BlazorStrap#11]
While trying to update to Blazor 0.5.0 parts of the sample site stopped working. I opened an issue in the main Blazor repo:

https://github.com/aspnet/Blazor/issues/1206

**Comment by jinqi166** [comment]
what about Blazor0.5.1

**Comment by chanan** [comment]
Tried 0.5.1 - didnt help.

I might try to delete the sample project and recreate it, see if that helps. That will take me a while to do though.

**Comment by ebekker** [comment]
Looking at the latest comments in 1206 -- it seems the issue may be that your custom `<Col>` tag that you use for defining layouts is conflicting with the built-in HTML [`<col>` tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/col) which is a self-closing tag.  Wonder if the custom layout tag should be renamed just to not conflict anyway?

**Comment by chanan** [comment]
@ebekker Ah, didn't think of that. I will try renaming it to BlazorCol later today and see if it goes away. Thanks for the idea!

**Comment by chanan** [comment]
Thanks to the suggestion by @ebekker, I fixed that error, now working on new ones.

**Comment by ebekker** [comment]
Great!  Post those as well, maybe there's a clever way to work around them too.
