### ISSUE TITLE
Sample Page Issue

### ISSUE THREAD

**Issue by endeffects** [chanan/BlazorStrap#118]
When i enter a sub page directly on your demo site, the browser url gets flooded with additional parameters:

![image](https://user-images.githubusercontent.com/13432569/61290618-949d1400-a7cc-11e9-936e-d7ff66c642cf.png)

To reproduce open a new tab and then the following url:
https://blazorstrap.io/popovers/

Happens on latest Chrome.

**Comment by endeffects** [comment]
Hm now it seems to work, strange.

**Comment by endeffects** [comment]
I'm still getting this error sometime:

![image](https://user-images.githubusercontent.com/13432569/61365084-60d2f480-a887-11e9-953c-012f8ac14791.png)

**Comment by chanan** [comment]
This is an artifact of github pages and not the BlazorStrap itself, but when we release the next version with preview7 I will do what I can to fix it

**Comment by jbomhold3** [comment]
If we add a route not found a handler. We can forward it back to the home page.  with a return URL and strip out the attracting, and since blazor will be booted by then it will just work. It's a silly workaround but something that will solve the issue.

**Comment by chanan** [comment]
Heck the 404.html page in the docs folder too. It had stuff in it to make it work when we the sites under a /BlazorStrap/ maybe. Now we are in the root. Could be the issue

**Comment by jbomhold3** [comment]
l.pathname.split('/').slice(0, 1 + segmentCount).join('/') + '/?p=/' +
        l.pathname.slice(1).split('/').slice(segmentCount).join('/').replace(/&/g, '~and~') 


Yup that would be it

**Comment by jbomhold3** [comment]
that could be simpled a lot... dump the entire route into returnurl... and let Blazors router do its thing.

**Comment by chanan** [comment]
Yep. I just grabbed a generic one at the time. Didn’t really look at it

**Comment by jbomhold3** [comment]
This is now fixed
