### ISSUE TITLE
Handling Validation Errors

### ISSUE THREAD

**Issue by endeffects** [chanan/BlazorStrap#119]
I tried to use the FormFeedback Control to show validation errors for each input field.
I have a dictionary of error messages filled at runtime and tried to populate them 
to the FormFeedback Control. The console output appears but the message 
is not shown on the page, so i think the IsInvalid binding seems not to work.

```
<BlazorForm>
    <h3>Invalid: @this.Errors.ContainsKey("Name")</h3>
    <FormGroup>
        <BlazorLabel For="Name">Name</BlazorLabel>
        <BlazorInput Id="Name" InputType="InputType.Text" @bind-Value="State.Request.Name" />
        <FormFeedback IsInvalid="@this.Errors.ContainsKey("Name")">@this.Errors["Name"]</FormFeedback>
    </FormGroup>
    <FormGroup>
        <BlazorButton ButtonType="ButtonType.Button" onclick="@(() => Submit())" class="w-100">Create</BlazorButton>
    </FormGroup>
</BlazorForm>

@functions
{
    Dictionary<string, string> Errors { get; set; } = new Dictionary<string, string>();

    private void Submit()
    {
        if (!this.Errors.ContainsKey("Name"))
        {
            this.Errors.Add("Name", "An error occured!");
        }

        Console.WriteLine("Validation: {0}", this.Errors["Name"]);

        this.StateHasChanged();
    }
}
```

**Comment by chanan** [comment]
I just tried the control (in isolation) this past weekend when checking everything over and it seemed to work. I will try your example though and get back to you.

**Comment by endeffects** [comment]
Did you had time to compare this with your isolated tests?

**Comment by chanan** [comment]
tbh I forgot (sorry head down in another library). I will add it to the next milestone which we should release right after preview7 comes out so that I we remember to check it out before we release our preview7.

**Comment by jbomhold3** [comment]
Adding support for default validation editform.. If you want to control this manually you will need to add is-invalid or is-valid to the form-control class

**Comment by jbomhold3** [comment]
Fixed in upcoming release
