### ISSUE TITLE
Tooltips are not displayed from time to time

### ISSUE THREAD

**Issue by fs86** [chanan/BlazorStrap#12]
Hello,

I have a table with a few icons in each row. Every single icon has its own tooltip. But for some reason some of the tooltips don't show up when a mouseover event occurs. It seems to be totally random and every time the page loads it is an other tooltip that dosn't show up. If I use the classic bootstrap way to display tooltips (not via BlazorStrap) and initialize them in the OnAfterRender method of my component, everything works fine.

If you want I can build a small sample project, but it will take a few days to get the time.

Best regards
Felix

**Comment by chanan** [comment]
A small repro will help if you get the time. I did notice that the tooltip page in my sample project, the hover spot doesnt seem to take up the full element. Could that be the same problem you are having?

**Comment by fs86** [comment]
Possible, but I need further investigation. I will create a sample repo.

**Comment by fs86** [comment]
Unfortunately I was not able to reproduce this behavior in my test repo. Maybe there are some other things in my project that I have to resolve first. From my side this issue can be closed as I think it is not an issue of BlazorStrap.

**Comment by Nick-DataByte** [comment]
The target would probably need to be unique for each row creating the ToolTip and target. The code for the ToolTip is using GetElementById so is getting the first element it finds in the DOM with the specified target id, which could be random and not the element that you would expect.

What would be nice is if the ToolTip tag wrapped the tag it was targeting and would automatically attach to the MouseOver/MouseOut events of the relevent instance of the target being created

**Comment by chanan** [comment]
I am closing this as we werent able to reproduce. If this still happens let us know
