### ISSUE TITLE
Closing Burger Menu automatically

### ISSUE THREAD

**Issue by endeffects** [chanan/BlazorStrap#121]
Is there any option to close the burger menu on collapsed state when i click outside the navbar?

![image](https://user-images.githubusercontent.com/13432569/61309027-c4aade00-a7f1-11e9-88c6-9ec01cdfaed9.png)

**Comment by chanan** [comment]
@jbomhold3 Can we use the same onfocusout solution you did for dropdowns?

**Comment by chanan** [comment]
Sorry to hijack this thread, what are you building @endeffects is it something public that we can see? (Just curious not for the bug)

**Comment by endeffects** [comment]
Nope sorry, currently i'm working locally only.

**Comment by jbomhold3** [comment]
Added in PR #142

**Comment by endeffects** [comment]
I installed the latest version, but closing the menu automatically seems not to work. Do i have to add a special parameter for it?

**Comment by chanan** [comment]
Reopening so it doesnt get lost in the shuffle

**Comment by endeffects** [comment]
Automatically closing the Dropdown by clicking outside the menu or choosing an element seems to be effected too.

**Comment by jbomhold3** [comment]
Can't reproduce. Is your toggle button nested properly?
