### ISSUE TITLE
Not working for multiple rows of items

### ISSUE THREAD

**Issue by dmarciano** [chanan/BlazorStrap#122]
I have a div where I am displaying symbols.  If there is only one row of symbols, or only one column, then the tooltips for each symbol will show.  However, if the symbols overflow onto additional rows, then the tooltips only for the first row of symbols shows.  Also (probably related) if the div's height is restricted, and overflow-y is set to scroll then a lot of additional blank space is added after the last row of symbols.

**Comment by chanan** [comment]
Can you supply a code sample for the two issues please?

**Comment by jbomhold3** [comment]
This is very old and no reply to the issue closing
