### ISSUE TITLE
Complete list of Components old and new name 

### ISSUE THREAD

**Issue by jbomhold3** [chanan/BlazorStrap#123]
Old Name| New Name
------------ | -------------
Alert | BSAlert
Badge | BSBadge
BlazorButton | BSButton
BlazorCol | BSCol
BlazorFigure | BSFigure
BlazorForm | BSForm
BlazorInput | BSInput
BlazorLabel | BSLabel
BlazorNav | BSNav
BlazorNavLink | BSNavLink
BlazorTable | BSTable
Breadcrumb | BSBreadcrumb
BreadcrumbItem | BSBreadcrumbItem
ButtonGroup | BSButtonGroup
Card | BSCard
Carousel | BSCarousel
CarouselCaption | BSCarouselCaption
CarouselControl | BSCarouselControl
CarouselIndicatorItem | BSCarouselIndicatorItem
CarouselIndicators | BSCarouselIndicators
CarouselItem | BSCarouselItem
Collapse | BSCollapse
Container | BSContainer
Dropdown | BSDropdown
DropdownHeader | BSDropdownHeader
DropdownItem | BSDropdownItem
DropdownMenu | BSDropdownMenu
DropdownToggle | BSDropdownToggle
FigureCaption | BSFigureCaption
FigureImage | BSFigureImage
FormFeedback | BSFormFeedback
FormGroup | BSFormGroup
FormLabel | BSFormLabel
Image | BSImage
Jumbotron | BSJumbotron
ListGroup | BSListGroup
ListGroupItem | BSListGroupItem
ListGroupItemHeading | BSListGroupItemHeading
ListGroupItemText | BSListGroupItemText
Media | BSMedia
Modal | BSModal
ModalBody | BSModalBody
ModalFooter | BSModalFooter
ModalHeader | BSModalHeader
NavItem | BSNavItem
Navbar | BSNavbar
NavbarBrand | BSNavbarBrand
NavbarToggler | BSNavbarToggler
Pagination | BSPagination
PaginationItem | BSPaginationItem
PaginationLink | BSPaginationLink
Popover | BSPopover
PopoverBody | BSPopoverBody
PopoverHeader | BSPopoverHeader
Progress | BSProgress
Row | BSRow
TabContent | BSTabContent
TabPane | REMOVED
TableCell | BSTableCell
TableHead | BSTableHead
TableHeadCell | BSTableHeadCell
TableRow | BSTableRow
Toast | BSToast
Tooltip | BSTooltip
NEW | BSTab
NEW | BSTabGroup
NEW | BSTabLabel
NEW | BSTabList
NEW | BSTabSelectedContent

**Comment by endeffects** [comment]
The Prefix Strap instead of BS is no option?

**Comment by jbomhold3** [comment]
It's something we can talk over

However, trying to avoid the user having to type too much before he/she is able, to start filtering what they are looking for. IG BSMo and you're already filtering to model.  Where if it was StrapMo you would have 3 extra keystrokes. 

BS = BlazorStrap, or bootstrap, or bull sh*t if you're mad at it or the program in general.

**Comment by jbomhold3** [comment]
If you have an idea for the prefix please get them in.  Once we submit preview 7-1 they will be locked. Myself and Chanan are open to ideas. Max of 3 letters, please.
