### ISSUE TITLE
Vertical Modal Issues

### ISSUE THREAD

**Issue by endeffects** [chanan/BlazorStrap#124]
On your demo page the vertical modal demo has an issue:

![image](https://user-images.githubusercontent.com/13432569/61371865-08efba00-a896-11e9-920e-231e40f9f1a1.png)

**Comment by jbomhold3** [comment]
When modals are opened the modal is given focus so escape works with them. I'm going to assume this is something in our css looking into it thank you.

**Comment by jbomhold3** [comment]
Fixed in upcoming p7 release
