### ISSUE TITLE
Plan Events for each component 

### ISSUE THREAD

**Issue by jbomhold3** [chanan/BlazorStrap#125]
We need to look at the components and add events where it makes sense.

| Component | Complete | Events | Event Class |
| ---|---|---|--- |
| Alert | 👍  | CloseEvent, ClosedEvent | BSAlertEvent { Target}
| Carousel | 👎 | N/A
| Collapse | 👍 | | ShowEvent, ShownEvent, HideEvent, HiddenEvent | BSCollapseEvent { Activated, Deactivated}
| Dropdown | 👍  | | ShowEvent, ShownEvent, HideEvent, HiddenEvent | BSDowndownEvent { Activated, Deactivated}
| Tabs | 👍 | ShowEvent, ShownEvent, HideEvent, HiddenEvent | BSTabEvent { Activated, Deactivated}
| Modal| 👍  | | ShowEvent, ShownEvent, HideEvent, HiddenEvent | BSModalEvent { Activated, Deactivated}
| Nav| 👎  | N/A
| Popover| 👎  | N/A
| ScrollSpy | 👎  | N/A
| Tooltip| 👎  | N/A

**Comment by jbomhold3** [comment]
Please, let us know your input on what event hooks you would like to see on components.

**Comment by jbomhold3** [comment]
These are the default bootstrap jquery events. Things that wait for CSS to complete. would likely be best fired after render? 
## Alert
Event | Description
-- | --
close.bs.alert | This event fires immediately when the close instance method is called.
closed.bs.alert | This event is fired when the alert has been closed (will wait for CSS transitions to complete).

## Carousel
Event Type | Description 
-- | --
slide.bs.carousel | This event fires immediately when the slide instance method is invoked.
slid.bs.carousel | This event is fired when the carousel has completed its slide transition.

## Collapse

Event Type | Description
-- | --
show.bs.collapse | This event fires immediately when the show instance method is called.
shown.bs.collapse | This event is fired when a collapse element has been made visible to the user (will wait for CSS transitions to complete).
hide.bs.collapse | This event is fired immediately when the hide method has been called.
hidden.bs.collapse | This event is fired when a collapse element has been hidden from the user (will wait for CSS transitions to complete).

## Dropdown
Event | Description
-- | --
show.bs.dropdown | This event fires immediately when the show instance method is called.
shown.bs.dropdown | This event is fired when the dropdown has been made visible to the user (will wait for CSS transitions, to complete).
hide.bs.dropdown | This event is fired immediately when the hide instance method has been called.
hidden.bs.dropdown | This event is fired when the dropdown has finished being hidden from the user (will wait for CSS transitions, to complete).

## Tabs

vent type | Description
-- | --
show.bs.tab | This event fires on tab show, but before the new tab has been shown. Use event.target and event.relatedTarget to target the active tab and the previous active tab (if available) respectively.
shown.bs.tab | This event fires on tab show after a tab has been shown. Use event.target and event.relatedTarget to target the active tab and the previous active tab (if available) respectively.
hide.bs.tab | This event fires when a new tab is to be shown (and thus the previous active tab is to be hidden). Use event.target and event.relatedTarget to target the current active tab and the new soon-to-be-active tab, respectively.
hidden.bs.tab | This event fires after a new tab is shown (and thus the previous active tab is hidden). Use event.target and event.relatedTarget to target the previous active tab and the new active tab, respectively.

## Modal

Event Type | Description
-- | --
show.bs.modal | This event fires immediately when the show instance method is called. If caused by a click, the clicked element is available as the relatedTarget property of the event.
shown.bs.modal | This event is fired when the modal has been made visible to the user (will wait for CSS transitions to complete). If caused by a click, the clicked element is available as the relatedTarget property of the event.
hide.bs.modal | This event is fired immediately when the hide instance method has been called.
hidden.bs.modal | This event is fired when the modal has finished being hidden from the user (will wait for CSS transitions to complete).

## Navs

Event Type | Description
-- | --
show.bs.tab | This event fires on tab show, but before the new tab has been shown. Use event.target and event.relatedTarget to target the active tab and the previous active tab (if available) respectively.
shown.bs.tab | This event fires on tab show after a tab has been shown. Use event.target and event.relatedTarget to target the active tab and the previous active tab (if available) respectively.
hide.bs.tab | This event fires when a new tab is to be shown (and thus the previous active tab is to be hidden). Use event.target and event.relatedTarget to target the current active tab and the new soon-to-be-active tab, respectively.
hidden.bs.tab | This event fires after a new tab is shown (and thus the previous active tab is hidden). Use event.target and event.relatedTarget to target the previous active tab and the new active tab, respectively.

## Popover

Event Type | Description
-- | --
show.bs.popover | This event fires immediately when the show instance method is called.
shown.bs.popover | This event is fired when the popover has been made visible to the user (will wait for CSS transitions to complete).
hide.bs.popover | This event is fired immediately when the hide instance method has been called.
hidden.bs.popover | This event is fired when the popover has finished being hidden from the user (will wait for CSS transitions to complete).
inserted.bs.popover | This event is fired after the show.bs.popover event when the popover template has been added to the DOM.

## Scrollspy

Event Type | Description
-- | --
activate.bs.scrollspy | This event fires on the scroll element whenever a new item becomes activated by the scrollspy.

## Tooltip

Event Type | Description
-- | --
show.bs.tooltip | This event fires immediately when the show instance method is called.
shown.bs.tooltip | This event is fired when the tooltip has been made visible to the user (will wait for CSS transitions to complete).
hide.bs.tooltip | This event is fired immediately when the hide instance method has been called.
hidden.bs.tooltip | This event is fired when the tooltip has finished being hidden from the user (will wait for CSS transitions to complete).
inserted.bs.tooltip | This event is fired after the show.bs.tooltip event when the tooltip template has been added to the DOM.

**Comment by chanan** [comment]
Thanks for getting the list together. I think it makes sense to stick to what bootstrap has.

**Comment by jbomhold3** [comment]
Show vs shown ext.. since we cant directly affect the dom. Events like show will happen the moment the user performs the action. Shown will happen after render.   For shown to work thinking a generic list of event<t> will hold our que and on afterrender will will loop through the que and fire them off

**Comment by chanan** [comment]
Is there ever a case where one control would need to fire more than one at AfterRender?

**Comment by jbomhold3** [comment]
I can think of a few with tabs and jsinterop if they are using it. you want to know when the element can be referenced safely. No point in a race condition. I think I have a rather smart way to solve firing them after that event without adding any real overhead
