### ISSUE TITLE
Feature Request: Speech Recognation

### ISSUE THREAD

**Issue by endeffects** [chanan/BlazorStrap#127]
I'm using a speech recognation component together with blazor strap, but maybe it would be a nice idea if your input controls support this by default.

https://github.com/jsakamoto/Toolbelt.Blazor.SpeechRecognition

**Comment by chanan** [comment]
Weird, I thought I also commented on this... anyway...

Awesome library! 

How exactly do you see the integration working? Do you have current code samples of how you combine the two?

@jbomhold3 I think this might be the start of either an external or internal Ext library we discussed

**Comment by endeffects** [comment]
Well, i think it should be possible to have an enum which allows to active the speech recognation by clicking into the input field or by pressing an additional "button" (microfon) that appears in the input box. The control should deactivate this feature by itself if the browser dows not support it or the user did not grant the required rights. The drawback here is, that it works only locally or on https pages. 

I have an older samples i can access at the moment:

```
@inherits SpeechInputBase

<div>
    <input type="text" @bind="Value" pattern="@Pattern" onfocus="@(async () => await OnFocus())" onclick="@(async () => await OnClick())" onblur="@(async () => await OnBlur())" />
</div>
```

```
using Toolbelt.Blazor.SpeechRecognition;
...
    public abstract class SpeechInputBase : ComponentBase, IDisposable
    {
        private string value;
        
        [Parameter]
        internal string Value
        {
            get => this.value;

            set
            {
                this.value = value;
                ValueChanged?.Invoke(value);
            }
        }

        [Parameter]
        internal string Pattern { get; set; }

        [Parameter]
        internal Action<string> ValueChanged { get; set; }
        
        [Inject]
        internal SpeechRecognition SpeechRecognition { get; set; }

        public virtual async Task InitializeSpeechRecognition()
        {
            if (this.SpeechRecognition.Available)
            {
                this.SpeechRecognition.Lang = "en-US";
                this.SpeechRecognition.InterimResults = true;
                this.SpeechRecognition.Continuous = false;
            }

            await Task.CompletedTask;
        }

        public async Task StartSpeechRecognition()
        {
            if (this.SpeechRecognition.Available)
            {
                this.SpeechRecognition.Result += OnSpeechRecognized;
                this.SpeechRecognition.Start();
            }

            await Task.CompletedTask;
        }

        public async Task StopSpeechRecognition()
        {
            if (this.SpeechRecognition.Available)
            {
                this.SpeechRecognition.Result -= OnSpeechRecognized;
                this.SpeechRecognition.Stop();
            }

            await Task.CompletedTask;
        }

        protected override async Task OnInitAsync()
        {
            await this.InitializeSpeechRecognition();
        }

        protected virtual async Task OnFocus()
        {
            await this.StartSpeechRecognition();
        }

        protected virtual async Task OnClick()
        {
            await this.StartSpeechRecognition();
        }

        protected virtual async Task OnBlur()
        {
            await this.StopSpeechRecognition();
        }

        protected virtual void OnSpeechRecognized(object sender, SpeechRecognitionEventArgs args)
        {
            this.Value = string.Join(" ", args.Results.Select(e => e.Items[0].Transcript));

            if (args.Results.All(e => e.IsFinal))
            {
                this.StopSpeechRecognition().Wait();
            }

            this.StateHasChanged();
        }

        public virtual void Dispose()
        {
            this.StopSpeechRecognition().Wait();
        }
    }
```

**Comment by chanan** [comment]
So what I think we can do here is have another project for extra controls or user contribution or something like that, where this can be added. I don't think we want this in the main BlazorStrap project because then everyone using BlazorStrap will need to also import Toolbelt.Blazor.SpeechRecognition

We can in this new "extras" project (or projects) have a SpeechInput control that should be "simple" to use and be based on the above plus maybe an SVG microphone icon inside the control box. Something along the lines of BlazorStrap.Extras.SpeechInput - That project will import both BlazorStrap and Toolbelt.Blazor.SpeechRecognition

As to timing of doing this? Not sure, but considering that I work with SpeechRecongnition almost every day, I would be very interested in doing this, so I am going to add this our post preview7 release and discuss further with @jbomhold3 on how we want to structure this, so hopefully wont be too long!

**Comment by endeffects** [comment]
Thanks for your feedback, sounds great. :)

**Comment by endeffects** [comment]
I have updated the link, it was the wrong repository.

**Comment by chanan** [comment]
@endeffects - @jbomhold3 put together a nice Speech Control that integrates with BSInput. It is going to live here: https://github.com/chanan/BlazorStrap.Extensions - It's not quite ready (and needs preview7 anyway), but should be available soon after preview7 is released. Once it is and you want to enhance it, please feel free to submit PRs for it - we don't use it often, so we don't know what you will need.

**Comment by endeffects** [comment]
Cool, that was fast. Thank you. I'll try it out as soon as the new version is out and i'm able to migrate.
