### ISSUE TITLE
BSTab Selected

### ISSUE THREAD

**Issue by mihaimyh** [chanan/BlazorStrap#128]
Hi,

Since I don't see any documentation published, I would like to ask if there is an event that fires when a BSTab gets selected/unselected.

Is see that the object BSTab has a Selected property, but how can I catch when a user navigates through tabs?

Thanks in advance.
Mihai

**Comment by chanan** [comment]
In #125 there is a listing of all the events we will be adding shortly to the controls. BSTab Shown is one of them. We hope to have that added very soon. In the meantime, you can bind Selected to a property in your page and override “get” which will be called when the property changes

**Comment by jbomhold3** [comment]
Added in PR #142
