### ISSUE TITLE
Modal border is out of range

### ISSUE THREAD

**Issue by sureadam** [chanan/BlazorStrap#132]
When a modal opens with preview 7 the border ranges from the top to the bottom of the page. CSS overrides are not working to update this, yet :/

[](https://clevelandclinic-staging-integration.silkroad.com/image/BlazorStrap_ModalBorder.png)

You can also see the modal in use on the below page when clicking contractor and using a modal. 

https://clevelandclinic-staging-integration.silkroad.com

**Comment by chanan** [comment]
Do you mean the blue border on the screen when you click Reset Form on https://clevelandclinic-staging-integration.silkroad.com/Contractor

**Comment by sureadam** [comment]
Exactly, I updated my project to preview 7 and had to update this one as well to match, everything came out ok after updating to the new tags but this border.

**Comment by chanan** [comment]
Can you supply the code from you model please?

**Comment by sureadam** [comment]
Sure, this one is a simple one, the other one behave the same way. The border only shows when it's active, it clears once you click on another window. 

     <BSModal IsOpen="@IsOpen3" IsCentered="true">
            <BSModalHeader OnClick="@onclick" >Reset Form</BSModalHeader>
            <BSModalBody> <p class="HEADLINE text-center">Are you sure you want to reset this form?</p> </BSModalBody>
            <BSModalFooter>
                <BSButton Color="Color.Secondary" OnClick="@onclickR">Cancel</BSButton>
                <BSButton Color="Color.Dark" OnClick="@refresh">Reset Form</BSButton>
            </BSModalFooter>
        </BSModal>

**Comment by jbomhold3** [comment]
include _content/BlazorStrap/css/cromefix.css  This is crome highlighting focused items

**Comment by jbomhold3** [comment]
Not really a bug more of an annoying thing crome added

**Comment by chanan** [comment]
@jbomhold3 Should we/can we inject that chrome fix as part of `SetBootstrapCSS();` - is it safe to always add?

**Comment by sureadam** [comment]
Thanks for the workaround, the chrome fix css works in chrome and IE edge as well. All set!

**Comment by chanan** [comment]
I am going to leave this open for now while we consider adding the fix to `SetBootstrapCSS()`

**Comment by jbomhold3** [comment]
Fixed in next release.
