### ISSUE TITLE
Remove BootstrapComponentBase

### ISSUE THREAD

**Issue by chanan** [chanan/BlazorStrap#133]
Do we still use: https://github.com/chanan/BlazorStrap/blob/master/src/BlazorStrap/Util/Components/BootstrapComponentBase.cs ?

If so, why? Do we really still need it? 

If not, lets delete it.

**Comment by jbomhold3** [comment]
We would have to add

[Parameter(CaptureUnmatchedValues = true)] protected IDictionary<string, object> UnknownParameters { get; set; }

to all files  but I'm fine with removing a near pointless base class

**Comment by jbomhold3** [comment]
Gone
