### ISSUE TITLE
Overriding Colors

### ISSUE THREAD

**Issue by endeffects** [chanan/BlazorStrap#137]
Is there an easy way to override your color definitions without to use themes?
It would be great to use the existing enums and to define some other colors for them.

**Comment by chanan** [comment]
Can you just over ride the bootstrap colors in your “site.css”?

**Comment by endeffects** [comment]
Well, maybe on the wrong road here, but what i found is something like this, which seems to be much overhead:
https://getbootstrap.com/docs/4.0/getting-started/theming/

And by using pure css i have to override the specific css classes, like "navbar-dark" or "text-light".
So i thought doing something like this would be more comfortable:

```
<BSSettings>
     <BSColorOverride Color="Color.Black" NewValue="#grey" />
    <BSColorOverride Color="Color.Light" NewValue="#223344" />
</BSSettings>
```

**Comment by chanan** [comment]
can you try this:

<BSButton style=“color:red;”>red button</BSButton>

**Comment by endeffects** [comment]
Yes i know this is possible. But that's not my point. What i try to explain is, that i already use an abstract color definition for my layout - your color enumerations, which are used to create the abstract bootstrap css classes. Or in other words, a single enumeration value like Color.Black is used to create various bootstrap tags like bg-black, text-black, nav-black.

So from my perspective it would be much easier to override your color convertion than to deal with multiple css overrides. But this is just an idea.

**Comment by chanan** [comment]
I see. The problem with that is that bootstrap’s btn-primary for example might be just a color or it might be many css rules. Btn is simple so it’s probably just a color. But like you mention navbar bg-black is likely at least two background and color. So I am not sure how easy it will be. 

Having said that, allowing the user to override some of the css rules by setting up a “theme” and passing it down (somewhat like your snippet) using CascadingValues is something I have always considered (might already be an issue for that not sure). I will talk it over with @jbomhold3 and see if we can do something like you suggested.

**Comment by jbomhold3** [comment]
We could have a static color override dictionary they can add to. then just output the contents in the right place in a style tag.

**Comment by chanan** [comment]
That simpler :) I suppose you can do any css rule. Doesn’t have to be color

**Comment by jbomhold3** [comment]
We have worked out how we want to do global overrides. You are going to have to include a <BSColorSettings/>  as the first line of your main layout. Pre Component level overrides will be done via the Style tag.

**Comment by endeffects** [comment]
Thank you, great news :)

**Comment by jbomhold3** [comment]
bootstrap does not use its own css vars. .... annoying but have another idea might push this back a release though

**Comment by StuartHemming** [comment]
> We have worked out how we want to do global overrides. You are going to have to include a as the first line of your main layout. Pre Component level overrides will be done via the Style tag.

Could you put that in words of one-syllable, for those of us in hard of thinking.

**Comment by jbomhold3** [comment]
This didn't work as expected is why it got pushed to the back log. You still have to mod your css to set default colors.
