### ISSUE TITLE
Horizontal navbar has odd responsive behaviors

### ISSUE THREAD

**Issue by MarkStega** [chanan/BlazorStrap#14]
These may all be known to you based on the alert on the navbars page in the sample app ("Navbar toggle needs more work)  but here is what I have observed:

As you reduce the width of the page the navbar reorients from a horizontal to a vertical presentation, however:
* The hamburger does not appear until you further reduce the page width
* The vertical menu starts in the open format and it really should start in the collapsed form

The opposite issue occurs when you stretch the page width, the hamburger disappears leaving you with no menu if the menu wasn't expanded at the time you do the stretch

**Comment by MarkStega** [comment]
I take part of my observations back; The lack of coordination of the hamburger and the menu that I was observing was getting caused by the css in site.css that got generated when creating a new Blazor project. As soon as I removed the following css the menu became responsive as expected:
```
.main {
    flex: 1;
}

.top-row {
    height: 3.5rem;
    display: flex;
    align-items: center;
}

    .main .top-row {
        background-color: #e6e6e6;
        border-bottom: 1px solid #d6d5d5;
    }

@media (max-width: 767.98px) {
    .main .top-row {
        display: none;
    }
}

@media (min-width: 768px) {
    app {
        flex-direction: row;
    }

    .sidebar {
        width: 250px;
        height: 100vh;
        position: sticky;
        top: 0;
    }

    .main .top-row {
        position: sticky;
        top: 0;
    }

    .main > div {
        padding-left: 2rem !important;
        padding-right: 1.5rem !important;
    }

    .navbar-toggler {
        display: none;
    }

    .sidebar .collapse {
        display: block;
    }
}
```
You have the same @media content in your sample app so I removed it and the responsiveness was OK where beforehand it had the same funky hamburger/menu non-coordination.

The issue still exists that when you are collapsing the width (or starting with a narrow width) that the vertical menu is initially displayed.

**Comment by MarkStega** [comment]
And I take the issue of the initial vertical navbar being open when it is first presented off the table also. Counter intuitively, is you start with 'IsOpen = false;' a horizontal menu still displays but however you get to a vertical menu it starts off as collapsed.

**Comment by chanan** [comment]
The issue with the site.css might be that Blazor is still using (last I checked) Bootstrap 4.0 and BlazorStrap uses 4.1. There are a few differences between the two which *might* cause the issue with the site.css. I will look into it.

I will also review the isOpen functionality and see if we can avoid the "flicker" you observed.

**Comment by MarkStega** [comment]
I changed by Index.html to have
```
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
```
I confirmed with the Blazor guys that they have no inherent use of Bootstrap other than what gets styled in the client app.

**Comment by jbomhold3** [comment]
Closed reopen if this is till an issue.
