### ISSUE TITLE
BSNavLink should apply the "active" class when href matches the site path like standard NavLink

### ISSUE THREAD

**Issue by noahc3** [chanan/BlazorStrap#147]
The standard NavLink component in Blazor automatically applies the `active` class (or a custom "active" class(es) specified with the `ActiveClass` parameter) to the rendered `a` element when the site path matches the href parameter. BSNavLink should also do this so ex. Navs automatically highlight the correct tab after being clicked without needing any custom logic.

**Comment by jbomhold3** [comment]
Done
