### ISSUE TITLE
AuthorizeView Issue

### ISSUE THREAD

**Issue by endeffects** [chanan/BlazorStrap#149]
I have surrounded some of my controls with an AuthorizeView.
With the latest version of BlazorStrap i receiving the following error:

`Error	RZ9999	The child content element 'ChildContent' of component 'BSForm' uses the same parameter name ('context') as enclosing child content element 'Authorized' of component 'AuthorizeView'. Specify the parameter name like: '<ChildContent Context="another_name"> to resolve the ambiguity`

```
<AuthorizeView Policy="@Policies.IsUser">
    <Authorized>
        <BSForm>
            ...
        </BSForm>
    </Authorized>
</AuthorizeView>
```

**Comment by chanan** [comment]
@jbomhold3 I think thats a "problem" in the way Blazor does cascading values... I put the word problem is quotes because I doubt they will fix it.

Should we just go and prefix all our cascading values with "BS"?

**Comment by jbomhold3** [comment]
After playing around with this some. This is not a blazorstrap issue. It happens with the default EditForm. This can be fixed easily  <Authorized context="Auth"> @Auth.User..... <.Authorized>

**Comment by jbomhold3** [comment]
Checking into the matter more this is Blazors Default behavior when dealing with a RenderFragment<T>. They automagically generate a context for each. If you nest them your creating the ambiguous issue. Changing the context name in any of the components will resolve the issue

**Comment by chanan** [comment]
Based on the information @jbomhold3 found out about Cascading Values with RenderFragment, we are closing this issue

**Comment by endeffects** [comment]
Ah thank you, i did not noticed this and i found nothing related to the error code.

**Comment by endeffects** [comment]
One more question about the context issue, won't it make sense to use a custom context name within the BlazorStrap RenderFragments by default? The chance that this happens for other users seems to be high and you could prevent this easily?

**Comment by chanan** [comment]
We can't we don't use the name "context" at all - when we use RenderFragment<T> - Blazor auto creates behind the scene a variable named context, but they use the same variable everytime which causes your error. That is a bug in Blazor if you ask me, they should use different names - so one day they might fix it...

**Comment by endeffects** [comment]
Oh ok, I just thought you are able to override it on a lower level as suggested.

**Comment by chanan** [comment]
Yes that’s what I thought too when I first read the issue but after more investigation by John we found that is not the case. Sadly.

**Comment by jbomhold3** [comment]
RenderFragment<T> to be more clear. For anyone finding this issue later on. Renaming the auth context is probably the easiest bet as your likely to run into the issue with other things. This also affects Microsoft's Editform component.

**Comment by shahedc** [comment]
> After playing around with this some. This is not a blazorstrap issue. It happens with the default EditForm. This can be fixed easily
> 
> ```
> <Authorized context="Auth"> @Auth.User..... </Authorized>
> ```

Btw, the attribute Context is case-sensitive, so a lower-case 'c' won't work when adding the context name. You must spell the word Context with an upper-case 'C'.

**Comment by Manzoliz** [comment]
just for the correct overall answer: <Authorized Context="Auth"> @Auth.User..... </Authorized>
