### ISSUE TITLE
Documentation missing for css environment

### ISSUE THREAD

**Issue by MarkStega** [chanan/BlazorStrap#15]
I see in the sample that you have added css in site.css to support the sample. Is any of that needed for proper functioning of BlazorStrap or is the current BootStrap V4 css all that is needed? A quick addition to the documentation adding a "Using BlazorStrap" section would be welcome.

**Comment by chanan** [comment]
I think the only thing I added to site.css was specific to the sample site - such as the docs div. I will recheck.

I do plan to add support for bootstrap themes and a theme switcher component, which will require setup to use. So will definitely have its own documentation page.

**Comment by MarkStega** [comment]
At least so far, I emptied the site.css file and my use of BlazorNav, Tables, and Container, Row, & BlazorCol are all working as expected.

**Comment by peterblazejewicz** [comment]
@chanan 
I've added more propert css as part of #29

**Comment by chanan** [comment]
Closing this due to this PR: #111
