### ISSUE TITLE
Handling custom validation issue

### ISSUE THREAD

**Issue by endeffects** [chanan/BlazorStrap#150]
I try to handle custom validation messages that do not use data annotations.
In the past i tried something like this, which does not work still with the new version:

`<BSFormFeedback IsInvalid="@this.State.Errors.ContainsKey("Name")">@this.State.Errors["Name"]</BSFormFeedback>`

With the new BlazorStrap version i also tried this, which does not work too, because the "For" statement does not accept method calls and the ValidMessage property tries to resolve the unavailable value of the dictionary:

`<BSFormFeedback For="@(() => this.State.Errors.ContainsKey("Name"))" ValidMessage="@this.State.Errors["Name"]" />`

`System.ArgumentException: The provided expression contains a InstanceMethodCallExpression1 which is not supported. FieldIdentifier only supports simple member accessors (fields, properties) of an object.`

I really don't want to provide extra IsValid-Properties.

**Comment by chanan** [comment]
@jbomhold3 is this related to the hotfix you mentioned we need?

**Comment by jbomhold3** [comment]
@endeffects  are you using a Model? I'm assuming your not going to want to do a custom validator as our validation is using the exact same code as Blazor, but thats an option. If your at least using the Model I can add away for you to set errors per parm yourself and then you just remove the DataAnnotationsValidator   but used it like the example..

``` HTML
<BSForm Model="@formsModel" @ref="myform">
        <BSFormGroup>
            <BSLabel For="Name">Test input</BSLabel>
            <BSInput InputType="InputType.Text" @bind-Value="@formsModel.Name"  />
            <BSFormFeedback For="@(() => formsModel.Name)" ValidMessage="Everything looks good" />
        </BSFormGroup>
    </BSForm>
```

``` C#
@code
private BSForm myform;
{
    YouErrorHandler ()
{
    myform.AddError("Name", "Some error message");
}
}
```

**Comment by jbomhold3** [comment]
Have an easier fix then that give me a few will post howto do what your wanting.

**Comment by jbomhold3** [comment]
@endeffects  What type is Errors["Name"]... list or string?

**Comment by endeffects** [comment]
Thanks for your reply, yes the error dictionary is of type dictionary<string, string> and yes the BSForm is bound to a model.

**Comment by jbomhold3** [comment]
``` C# 
<BSForm Model="@FormModel" ValidateOnInit="true" UserValidation="true">
    <BSRow>
        <BSFormGroup Class="col-md-12">
            <BSLabel For="exampleEmail8">Valid input</BSLabel>
            <BSInput IsValid="true" InputType="InputType.Text" Id="exampleEmail8" @bind-Value="@FormModel.Name" />
            <BSFormFeedback IsValid="true" For="@(() => FormModel.Name)" ValidMessage="Sweet! you fixed the issue" InvalidMessage="Oh no something is wrong"/>
        </BSFormGroup>
    </BSRow>
</BSForm>
<BSForm Model="@FormModel" ValidateOnInit="true" UserValidation="true">
    <BSRow>
        <BSFormGroup Class="col-md-12">
            <BSLabel For="exampleEmail8">Invalid input</BSLabel>
            <BSInput IsInvalid="true" InputType="InputType.Text" Id="exampleEmail8" @bind-Value="@FormModel.Name" />
            <BSFormFeedback IsInvalid="true" For="@(() => FormModel.Name)" ValidMessage="Sweet! you fixed the issue" InvalidMessage="Oh no something is wrong" />
        </BSFormGroup>
    </BSRow>
</BSForm>
```

**Comment by chanan** [comment]
Released in 1.0.0-preview7-04

**Comment by endeffects** [comment]
Thanks for the quick fix, i got it working now. But there seems to be a logical issue here.

1) The page is loaded:

![image](https://user-images.githubusercontent.com/13432569/62790677-e08d6100-bacb-11e9-87c4-a6299eaa19ef.png)

2) I click into the input field and the control enters into a valid state, but no validation happend:

![image](https://user-images.githubusercontent.com/13432569/62790742-fbf86c00-bacb-11e9-97bd-22723fd17ae7.png)

3) I click "create" and the validation error appears, but the error message is green:

![image](https://user-images.githubusercontent.com/13432569/62790835-382bcc80-bacc-11e9-9675-8bf4d5e3888e.png)

4) Entering some text (changing the state) without submitting it should reset the validation state:

![image](https://user-images.githubusercontent.com/13432569/62791104-c607b780-bacc-11e9-8e30-9599dec7f393.png)

5) Finally submitting a valid text ends in the expected state:

![image](https://user-images.githubusercontent.com/13432569/62791082-bc7e4f80-bacc-11e9-9e4b-4e4a04589d67.png)

**Comment by jbomhold3** [comment]
My PR got closed and not committed by mistake. adding to this round of bug fixes. my post is how its done manually

**Comment by endeffects** [comment]
I have an other issue here, beside the general input validation i'm also capturing exceptions from the underlying http requests. If the request fails i'd like to show the exception message for the submit button. The property "HasErrors" is true and the "ShowErrorMessage" returns an error message.

```
        <BSForm Model="@this.State.Request">
            <BSFormGroup>
                <BSButton ButtonType="ButtonType.Button" onclick="@(async () => await this.Create(this.State.Request))" class="w-100">Create</BSButton>
                <BSFormFeedback For="@(() => this.State.HasErrors)" ValidMessage="@this.State.ShowErrorMessage("Exception")" />
            </BSFormGroup>
        </BSForm>
```

Is also tried to set the FormFeedback Property IsInvalid="true".

**Comment by jbomhold3** [comment]
Once released it's 
``` html <BSFormFeedback IsValid="true" For="@(() => FormModel.Name)" ValidMessage="Sweet! you fixed the issue" InvalidMessage="Oh no something is wrong"/>
```

ValidMessage shows up only when valid
InvalidMessage is new for manual validation

**Comment by chanan** [comment]
Released in 1.0.0-preview7-05

**Comment by endeffects** [comment]
Hmm, i tried the new version, but i still have some issues. 

**1. I've loaded the page:**

![image](https://user-images.githubusercontent.com/13432569/62835543-021c5300-bc5a-11e9-91b2-33edb791d9ec.png)

**2. I click into the input box, no visual validation appear, which is great.**

![image](https://user-images.githubusercontent.com/13432569/62835554-211ae500-bc5a-11e9-856a-3e076fe4946d.png)

**3. I submit the invalid form and the validation gets triggered, but the FormFeedback is not shown:**

![image](https://user-images.githubusercontent.com/13432569/62835560-41e33a80-bc5a-11e9-8d0c-8f50c61f61ed.png)

**4. I submit a valid form and a http error gets triggered, but the FormFeedback for the button is not shown:**

![image](https://user-images.githubusercontent.com/13432569/62835564-64755380-bc5a-11e9-870e-11d93b66971b.png)

```
<BSForm Model="@this.State.Request" UserValidation="true">
    <h3>Rename</h3>
    <BSFormGroup>
        <BSLabel>Name</BSLabel>
        <BSInput Id="Name" InputType="InputType.Text" @bind-Value="this.State.Request.Name" IsInvalid="@this.State.ContainsError("Name")" />
        <BSFormFeedback For="@(() => this.State.Request.Name)" InvalidMessage="@this.State.ShowErrorMessage("Name")" />
    </BSFormGroup>
    <BSFormGroup>
        <BSButton ButtonType="ButtonType.Button" onclick="@(async () => await this.Rename(this.State.Request))" class="w-100">Rename</BSButton>
        <BSFormFeedback For="@(() => this.State.HasErrors)" IsInvalid="@this.State.HasErrors" InvalidMessage="@this.State.ShowErrorMessage("Exception")" />
    </BSFormGroup>
</BSForm>
```

From your comments i have to apply the following steps:

1) I have to set the UserValidation to true for the BSForm.
2) I have to trigger the IsInvalid Property and set it to true.
3) I have to provide an error for the InvalidMessage Property.

Is this correct?

**Comment by jbomhold3** [comment]
@endeffects You're doing manual validation so you are responsible for the invalid and invalid flags. This is a working sample

``` html
<BSForm Model="@FormModel" ValidateOnInit="true" UserValidation="true">
    <BSRow>
        <BSFormGroup Class="col-md-12">
            <BSLabel For="exampleEmail8">Invalid input</BSLabel>
            <BSInput IsInvalid="invalid" IsValid="valid" InputType="InputType.Text" Id="exampleEmail8" @bind-Value="@FormModel.Name" />
            <BSFormFeedback IsInvalid="invalid" IsValid="valid" For="@(() => FormModel.Name)" ValidMessage="Sweet! you fixed the issue" InvalidMessage="Oh no something is wrong" />
        </BSFormGroup>
    </BSRow>
</BSForm>

<BSButton ButtonType="ButtonType.Button" @onclick="@(() => invalid = !invalid )">Toggle invalid</BSButton>
<BSButton ButtonType="ButtonType.Button" @onclick="@(() => valid = !valid )">Toggle valid</BSButton>
```
``` C#
@code
{
    private bool _invalid = false;
    private bool _valid = false;
    bool invalid
    {
        get{return _invalid;}
        set{_valid = valid && !value; _invalid = value; }
    }
    bool valid
    {
        get{return _valid;}
        set{_invalid = invalid && !value; _valid = value; }
    }
    MyModel FormModel = new MyModel();
}
```

**Comment by endeffects** [comment]
Oh thank you, i missed the IsInvalid Binding for the FormFeedback itself. So this is working now. What is does not solve is to show a general error under the form if the http request fails, this seems to be not possible with the FormFeedback control, or?

```
    <BSFormGroup>
        <BSButton ButtonType="ButtonType.Button" onclick="@(async () => await this.Rename(this.State.Request))" class="w-100">Rename</BSButton>
        <BSFormFeedback For="@(() => this.State.HasErrors)" IsInvalid="@this.State.HasErrors" InvalidMessage="@this.State.ShowErrorMessage("Exception")" />
    </BSFormGroup>
```

**Comment by jbomhold3** [comment]
Hidden input above button as a workaround for the moment bind to anything so invalid gets placed. We will look into the best way to handle this with bootstrap. Rather that is putting an isvalid/isinvalid in the button.

**Comment by jbomhold3** [comment]
BTN isn't going to be the right area if we align as close as we align with bootstrap.  Will take a little thought. I need to add the validation summary to a bs component and not using the default so will likely be what fixes this so opening a new ticket.

**Comment by endeffects** [comment]
Ok, thank you. :)
