### ISSUE TITLE
ChildContent not rendered on BSInput

### ISSUE THREAD

**Issue by EMaderbacher** [chanan/BlazorStrap#153]
With latest beta build  (v1.0.0-preview7-03) isn't rendered anymore the ChildContent for InputType.Select

**Comment by chanan** [comment]
Can you supply a code snippet of the issue please?

**Comment by jbomhold3** [comment]
Issue confirmed. looking into it

**Comment by jbomhold3** [comment]
Fixed in next release. Was rendering childcontent wrong .

**Comment by chanan** [comment]
Fixed in 1.0.0-preview7-05
