### ISSUE TITLE
Tabs content not update on removing tab

### ISSUE THREAD

**Issue by bens-web-dev** [chanan/BlazorStrap#154]
Hello there,

when i create a list of tabs and remove one tab in the list the Tab content wont update. I created this code to reproduce it. Maybe im doing anything wrong? 

Best regards

`<BSTabGroup>
    <BSTabList>

        @foreach (var tab in _tabList)
        {
        <BSTab>
            <BSTabLabel>@tab.Label <strong @onclick="() => RemoveTab(tab.Id)">X</strong></BSTabLabel>
            <BSTabContent>@tab.Content</BSTabContent>
        </BSTab>
        }
    </BSTabList>
    <BSTabSelectedContent />
</BSTabGroup>`

`@code {

    private class SimpleTab
    {
        public string Id { get; set; }
        public string Label { get; set; }
        public string Content { get; set; }

        public SimpleTab(string label, string content)
        {
            this.Id = Guid.NewGuid().ToString();
            this.Label = label;
            this.Content = content;
        }
    }

    private List<SimpleTab> _tabList = new List<SimpleTab>
    {
        new SimpleTab("Tab1", "Content One"),
        new SimpleTab("Tab2", "Content Two"),
        new SimpleTab("Tab3", "Content Three"),
        new SimpleTab("Tab4", "Content Four")
    };

    private void RemoveTab(string tabId)
    {
        var tab = this._tabList.FirstOrDefault(x => x.Id == tabId);
        if(tab != null)
        {
            this._tabList.Remove(tab);
        }
    }

}`

**Comment by chanan** [comment]
Can you try adding StateHasChanged() at the end of RemoveTab and see if it fixes it? If not, we will try to fix it ASAP

**Comment by bens-web-dev** [comment]
Oh ive forgotten to add this in my code snippet, but that does not fix the issue.

**Comment by jbomhold3** [comment]
https://gyazo.com/b3f06033acec5c6c41185bc80d94f8c9
``` html
<BSTabGroup >
    <BSTabList>
        @foreach (var tab in _tabList)
        {
            <BSTab>
                <BSTabLabel>@tab.Label <strong @onclick="() => RemoveTab(tab.Id)">X</strong></BSTabLabel>
                <BSTabContent>@tab.Content</BSTabContent>
            </BSTab>
        }
    </BSTabList>
    <BSTabSelectedContent />
    </BSTabGroup>
```

``` C#
 @code{
        private class SimpleTab
        {
            public string Id { get; set; }
            public string Label { get; set; }
            public string Content { get; set; }

            public SimpleTab(string label, string content)
            {
                this.Id = Guid.NewGuid().ToString();
                this.Label = label;
                this.Content = content;
            }
        }

        private List<SimpleTab>
            _tabList = new List<SimpleTab>
                {
        new SimpleTab("Tab1", "Content One"),
        new SimpleTab("Tab2", "Content Two"),
        new SimpleTab("Tab3", "Content Three"),
        new SimpleTab("Tab4", "Content Four")
                    };

        private void RemoveTab(string tabId)
        {
            var tab = this._tabList.FirstOrDefault(x => x.Id == tabId);
            if (tab != null)
            {
                this._tabList.Remove(tab);
            }
            StateHasChanged();
        }
    }
```

**Comment by jbomhold3** [comment]
@bens-web-dev can you tell me if the code above works on your end?

**Comment by bens-web-dev** [comment]
hey @jbomhold3 , you can see in your demo link on gyazo.com that the tab content not update correctly. The content does not match the tab label.

**Comment by jbomhold3** [comment]
@bens-web-dev  Addressing that just wanted to make sure the content does update on your end even if it points to the wrong item. Fixing the wrong item issue as we speak

**Comment by bens-web-dev** [comment]
@jbomhold3  Yes okay, by content i meant the BSTabContent which not update correctly, but sure its the wrong item.

**Comment by jbomhold3** [comment]
Found the issue. We have a race condition going on here. Basically, it's updating to the new because of the click. However, it's being removed at the same time. So the tab gets removed first. Triggering dispose of then the click event comes in and triggers its command and renders what it had as the selected tab.

**Comment by jbomhold3** [comment]
Next issue is blazor has no clue what tab you removed. Only that something has been removed from the list. So it picks the last item in the list assuming its the one removed. So adding a remove function to the tabs.

**Comment by jbomhold3** [comment]
@bens-web-dev   Note the @key this keeps the components rendered insync with the list. The above comment is fixed in next release. However, @key should hold you over until it is
 <BSTabList>
        @foreach (var tab in _tabList)
        {
            <BSTab Name="@tab.Label" @key="tab">
                <BSTabLabel>@tab.Label <strong @onclick="() => RemoveTab(tab.Id)">X</strong></BSTabLabel>
                <BSTabContent>@tab.Content</BSTabContent>
            </BSTab>
        }
    </BSTabList>
    <BSTabSelectedContent />
    </BSTabGroup>

**Comment by bens-web-dev** [comment]
@jbomhold3 Great that you found the Issue!! And thank you for the hint with the @key attribute. Thats good to know and works perfectly for now. I started with blazor only a few days ago but its fun. So shall i close this opened issue?

**Comment by jbomhold3** [comment]
Welcome to blazor happy to help
