### ISSUE TITLE
preview 8

### ISSUE THREAD

**Issue by jbomhold3** [chanan/BlazorStrap#162]
Just wanted to give everyone a heads up we are actively porting to preview 8. If all gos well we should have a build ready tomarrow.

**Comment by ivmarkov68** [comment]
BSForm.razor is missing

**Comment by Mason742** [comment]
Cool! Looking forward to it.

**Comment by jbomhold3** [comment]
there isn' t a BSForm.razor we are building the view in code.

**Comment by jbomhold3** [comment]
Preview 8 PR is ready.
Please note there were code changes because of API changes on Microsoft's end. So bugs that had already been fixed could show their head again.  Heres hoping that didn't happen.
