### ISSUE TITLE
DropDown Menu not retaining selection

### ISSUE THREAD

**Issue by Redeye51** [chanan/BlazorStrap#172]
The normal behavior of a select or drop down box is that once a value selected that value would show in the control. when I test your DDB the value is not retained. Is that by design or is that control on complete?

Thanks!

**Comment by Redeye51** [comment]
Chanan,

Thanks for the reply. All your samples use an href so I'm unable to test
this using your site.

Here's the code from my test page.

@page "/bstest"
<h3>BlazorStrap Test</h3>

<div class="row">
    <div class="col">
        <BSDropdown>
            <BSDropdownToggle>Dropdown1</BSDropdownToggle>
            <BSDropdownMenu>
                <BSDropdownItem>Action</BSDropdownItem>
                <BSDropdownItem>Another Action</BSDropdownItem>
                <BSDropdownItem>Yet Another Action</BSDropdownItem>
            </BSDropdownMenu>
        </BSDropdown>
    </div>
    <div class="col">
        <BSDropdown>
            <BSDropdownToggle>Dropdown2</BSDropdownToggle>
            <BSDropdownMenu>
                <BSDropdownItem>Action</BSDropdownItem>
                <BSDropdownItem>Another Action</BSDropdownItem>
                <BSDropdownItem>Yet Another Action</BSDropdownItem>
            </BSDropdownMenu>
        </BSDropdown>
    </div>
    <div class="col">
        <input value="@selectedDate.ToString("yyyy-MM-dd")" @onchange="@(o
=> selectedDate = DateTime.Parse(o.Value.ToString()))" type="date" />
    </div>
</div>


@code {

    DateTime selectedDate { get; set; } = DateTime.Now;

}

Thanks,

Bryan

**Comment by jbomhold3** [comment]
What are we testing here? BSDropDown is a navbar drop don't not a select option box... use <BSInput Inputtype="Inputtype.Select"> <option>value</option> </bsinput>    BSInputBasic if your not data binding

**Comment by Redeye51** [comment]
Hi,

This was a basic test of the component. My apologies, I must have missed
that detail. I didn't know it was a navbar only component. I am data
binding so the BSInputBasic won't work.

Thanks for your help.

Cheers

**Comment by jbomhold3** [comment]
Bsinput for data binding with a model. no worries dont expect people to k ow what everything in the library does
