### ISSUE TITLE
nothing back from @bind-Value on checkbox

### ISSUE THREAD

**Issue by le5h** [chanan/BlazorStrap#182]
and also I can't bind boolean, as I am expected for checkbox
![image](https://user-images.githubusercontent.com/10676426/64709150-7434c180-d4be-11e9-9641-dedf381a622d.png)

**Comment by chucker** [comment]
This indeed seems broken.

```cshtml
doesn't work:
    <BSInput InputType="InputType.Checkbox" @bind-Value="IsTicked" />

works:
    <InputCheckbox @bind-Value="IsTicked" />
```

**Comment by chucker** [comment]
>also I can't bind boolean

`BSBasicInput` doesn't seem to be generic. I'm not sure if that's by design.

`BSInput` _is_ generic, so you might prefer using that. But it doesn't actually seem to work for checkboxes yet either.
