### ISSUE TITLE
BSInput with decimal number or Nullable (int?/decimal?)

### ISSUE THREAD

**Issue by anderjoy** [chanan/BlazorStrap#187]
How can i use the BSInput with decimal type or Nullabe type?

**Comment by jbomhold3** [comment]
Added  Support for nullable types testing now

**Comment by jbomhold3** [comment]
We do not normally do releases for one issue. However, this issue exposed a critical oversite in the project. One that could prevent people from using it for basic tasks.  Nullable Value types are now supported in BSInput...  

- Int?
- Long?
- Double?
- Guid?
- DateTime?
- DateTimeOffsert?

**Comment by anderjoy** [comment]
Thanks... 
I made a workeraround to get around, the problem is that was repeating because there are several fields that are optional.

Soon I update to test...

**Comment by Eonasdan** [comment]
@jbomhold3 did this end up getting release? I have an error `BlazorStrap.BSInput`1[System.Decimal] does not support the type 'System.Decimal'.`

**Comment by anderjoy** [comment]
> @jbomhold3 did this end up getting release? I have an error `` BlazorStrap.BSInput``1[System.Decimal] does not support the type 'System.Decimal'. ``

I have the same error.
I tried with double but it's not allow number with decimal value: 58.85 > 5885.

**Comment by jbomhold3** [comment]
@Eonasdan  I have to prase all return types. So we can't support every return type. Double is what we are using for decimal numbers.

@anderjoy Can you shown an example of what you're doing. This is working for me https://blazorstrap.io/samples/issue187

**Comment by anderjoy** [comment]
> @Eonasdan I have to prase all return types. So we can't support every return type. Double is what we are using for decimal numbers.
> 
> @anderjoy Can you shown an example of what you're doing. This is working for me https://blazorstrap.io/samples/issue187

This is my code from razor:
`
    <div class="form-group col-md-6">
        <label for="ValorLiquidacao">Valor para liquidação</label>
        <BSInput Id="ValorLiquidacao" InputType="InputType.Number" @bind-Value="PortabilidadeAprovar.ValorLiquidacao" ValidateOnChange="true" />
        <BSFormFeedback For="@(() => PortabilidadeAprovar.ValorLiquidacao)" />
    </div>
`

My backend:
public class PortabilidadeVeiculoAprovar
{
	...
	public double ValorLiquidacao { get; set; }
	...
}

When I set the value in razor page, the field lose de decimal separator:

Before:
![image](https://user-images.githubusercontent.com/6249874/64990182-ab7fe580-d8a5-11e9-8c3e-106caa400043.png)

After:
![image](https://user-images.githubusercontent.com/6249874/64990581-71fbaa00-d8a6-11e9-9ea8-aae257b1c377.png)

The debug of set property:
![image](https://user-images.githubusercontent.com/6249874/64990425-2d700e80-d8a6-11e9-81c3-37956e2f866e.png)

**Comment by anderjoy** [comment]
@jbomhold3 I think this problem is because my culture.

The code below:
```
...
else if (typeof(T) == typeof(double) || typeof(T) == typeof(double?))

{
	result = (T)(object)Convert.ToDouble(value);
	validationErrorMessage = null;
	return true;
}
...
```
Loses the decimal separator because you don't use culture.
When I change this code the issue is resolved:

```
...
else if (typeof(T) == typeof(double) || typeof(T) == typeof(double?))
{
	result = (T)(object)double.Parse(value, CultureInfo.InvariantCulture);
	validationErrorMessage = null;
	return true;
}
...
```

**Comment by jbomhold3** [comment]
Looks good can you do a PR with the changes?

**Comment by anderjoy** [comment]
Done.. #195

**Comment by jbomhold3** [comment]
Added to lastest release. Thank you for the PR
