### ISSUE TITLE
Displaying a modal when a page navigation occurs

### ISSUE THREAD

**Issue by MarkStega** [chanan/BlazorStrap#19]
I'd like to have a modal displayed when a page is the target of a navigation event. IE, if you navigate to page x that contains a component that is a modal I'd like to have that modal rendered in open mode.

The issue is that if you try to set IsOpen (presuming that is your member controlling the modal visibility) in OnAfterRender the modal does not display. If you simply place a button on page x that toggles the same  member then the modal acts as expected. However the extra button press is what I am trying to avoid.

**Comment by chanan** [comment]
Ok, I will update the other project I have first to Blazor 0.6.0 and come back to this, unless you want to submit a PR?

**Comment by MarkStega** [comment]
I haven't figured out what is breaking; If I do I'll also figure out a PR and submit same...

**Comment by chanan** [comment]
Awesome! If not, I will try to get back to this in a few days.

**Comment by chanan** [comment]
@MarkStega Did you get this working?

**Comment by MarkStega** [comment]
I never got it to work directly. I ended up setting a timer for a very short period in OnAfterRenderand have the timer fired method do the IsOpen.
Cheating for certain, but I had other things to implement...

**Comment by chanan** [comment]
@MarkStega Can you explain more what you are trying to do here? Why is the code in AfterRender and not in OnInit? If you can provide a code sample of how it should work that would be best. (And sorry for the huge delay in answering this)

**Comment by jbomhold3** [comment]
The new @ref toggle should work with this issue. NOTE.... your will need
```C#
protected bool FirstRender {get;set;}= true;
protected BSModel mymodelref;

protected override OnAfterRender()
{
    if(FirstRender )
    {
        FirstRender =false;
        mymodelref.Toggle();
    }
}
```

Since on AfterRender calls every time a render occurs. It would keep opening and closing, the model. This is what the FirstRender prevents. This is not a hack its how Microsoft expects us to handle FirstRender right now.

**Comment by MarkStega** [comment]
It does work...
