### ISSUE TITLE
Using events on BSTabGroup causes InvalidOperationException

### ISSUE THREAD

**Issue by MarkZither** [chanan/BlazorStrap#191]
using the example from https://blazorstrap.io/tabs when the page loads it results in an exception

An unhandled exception occurred while processing the request.
AggregateException: Exceptions were encountered while disposing components. (The current thread is not associated with the Dispatcher. Use InvokeAsync() to switch execution to the Dispatcher when triggering rendering or component state.) (The current thread is not associated with the Dispatcher. Use InvokeAsync() to switch execution to the Dispatcher when triggering rendering or component state.)
Microsoft.AspNetCore.Components.Rendering.HtmlRenderer.HandleException(Exception exception)

InvalidOperationException: The current thread is not associated with the Dispatcher. Use InvokeAsync() to switch execution to the Dispatcher when triggering rendering or component state.
Microsoft.AspNetCore.Components.Dispatcher.AssertAccess()

InvalidOperationException: The current thread is not associated with the Dispatcher. Use InvokeAsync() to switch execution to the Dispatcher when triggering rendering or component state.
Microsoft.AspNetCore.Components.Dispatcher.AssertAccess()

**Comment by chucker** [comment]
@MarkZither what browser is this?

**Comment by Reltik** [comment]
It happens to me too, Google Chrome 77

`InvalidOperationException: The current thread is not associated with the Dispatcher. Use InvokeAsync() to switch execution to the Dispatcher when triggering rendering or component state.
Microsoft.AspNetCore.Components.Dispatcher.AssertAccess()
Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToRenderQueue(int componentId, RenderFragment renderFragment)
Microsoft.AspNetCore.Components.ComponentBase.StateHasChanged()
Microsoft.AspNetCore.Components.ComponentBase.Microsoft.AspNetCore.Components.IHandleEvent.HandleEventAsync(EventCallbackWorkItem callback, object arg)
Microsoft.AspNetCore.Components.EventCallback<TValue>.InvokeAsync(TValue arg)
BlazorStrap.BSTabGroupBase.set_Selected(BSTabBase value)
BlazorStrap.BSTabBase.Dispose(bool disposing)
BlazorStrap.BSTabBase.Dispose()
Microsoft.AspNetCore.Components.Rendering.ComponentState.Dispose()
Microsoft.AspNetCore.Components.RenderTree.Renderer.Dispose(bool disposing)
Microsoft.AspNetCore.Components.Rendering.HtmlRenderer.HandleException(Exception exception)
Microsoft.AspNetCore.Components.RenderTree.Renderer.Dispose(bool disposing)
Microsoft.AspNetCore.Components.RenderTree.Renderer.Dispose()
Microsoft.AspNetCore.Mvc.ViewFeatures.RazorComponents.StaticComponentRenderer.PrerenderComponentAsync(ParameterView parameters, HttpContext httpContext, Type componentType)
Microsoft.AspNetCore.Mvc.Rendering.HtmlHelperComponentExtensions.PrerenderedServerComponentAsync(HttpContext context, ServerComponentInvocationSequence invocationId, Type type, ParameterView parametersCollection)
Microsoft.AspNetCore.Mvc.Rendering.HtmlHelperComponentExtensions.RenderComponentAsync<TComponent>(IHtmlHelper htmlHelper, RenderMode renderMode, object parameters)
PagosV9.Pages.Pages__Host.<ExecuteAsync>b__10_1() in _Host.cshtml
+
        @(await Html.RenderComponentAsync<App>(RenderMode.ServerPrerendered))
Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext.SetOutputContentAsync()
PagosV9.Pages.Pages__Host.ExecuteAsync()
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, bool invokeViewStarts)
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, string contentType, Nullable<int> statusCode)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0<TFilter, TFilterAsync>(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext<TFilter, TFilterAsync>(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
`

**Comment by MarkZither** [comment]
@chucker i am using Edge Version 79.0.279.0 (Official build) dev (64-bit), and also checked on Firefox 69.0 (64-bit) and Chrome Version 77.0.3865.90 (Official Build) (64-bit)

I updated everything to 1.0.0 today and tried again and still get the same error.

**Comment by jbomhold3** [comment]
Can you give a source example? Not able to reproduce this

**Comment by Reltik** [comment]
Mmm, you enabled ServerPrerendered mode?

**Comment by jbomhold3** [comment]
I found the issue.  Doing a build and releasing now

**Comment by jbomhold3** [comment]
The cause was prerendering like @MarkZither pointed out.

**Comment by MarkZither** [comment]
thanks @jbomhold3 working for me now.
