### ISSUE TITLE
DataAnnotationsValidator not works with compare

### ISSUE THREAD

**Issue by a-iafrate** [chanan/BlazorStrap#192]
Hi

i have created a model like this

` [Required(AllowEmptyStrings = false, ErrorMessage = "Oh noes! that name is already taken")]
            public string Password { get; set; }
            [Required(AllowEmptyStrings = false)]
            [Compare("Password")]
            public string Password2 { get; set; }`

with this there is an error if password2 is empty but not if password2 is not equal to password.

It's only my problem?

Thanks!

**Comment by jbomhold3** [comment]
File this in https://github.com/aspnet/aspnetcore. DataAnnotationsValidator is a default blazor component

**Comment by chanan** [comment]
Closing this as it is not a reactstrap issue - feel free to open another issue if you run into other problems.
