### ISSUE TITLE
How do you set the size of the Carousel

### ISSUE THREAD

**Issue by 1Stan2Harris** [chanan/BlazorStrap#197]
I'd like to have the BSCarousel take the top 20% of the screen.  I tried setting height in a <div> section and that failed to change the size.

**Comment by herbertmilhomme** [comment]
maybe might have to manually set it using `@attributes`

https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0#attribute-splatting-and-arbitrary-parameters

Follow that, and maybe toss in custom css as an inline `style` attribute?

**Comment by chanan** [comment]
I will recheck reactstrap and react-bootstrap and see how those libraries handle this and get back to you.

**Comment by ZainabJac** [comment]
Any conclusions on this?

**Comment by jbomhold3** [comment]
Currently have two ways you can do this. Wrap in <BSROW><BSCOL> this will set the width. If you need to change the height it would be just adding style="height:300px" to the Carousel tag. You can also add a class to your carousel and configure it in your CSS. In the future, we may provide a direct way to size it. However, as bootstrap does not even do so its a little outside of the goal of the project but we also recognize the convenience factor of just having a selection. 

@chanan  think the best way if do add this would be to allow the MD and SM and LG tags from col and just wrap it ourselves if they are set. Same thing if they pass a height just add the style to the tag.
