### ISSUE TITLE
Modal Backdrop is not functioning

### ISSUE THREAD

**Issue by herbertmilhomme** [chanan/BlazorStrap#198]
`BSModal.razor.cs`
```csharp
        // Is only called once, when page (component) is loaded... 
        // modal component isn't loaded multiple times, as it's baked into html when page loads.
        protected override async Task OnAfterRenderAsync(bool firstrun)
        {
            if (!HasRendered)
            {
                HasRendered = true;
            }
            else
            {
                // This try can be removed after they fix prerendering
                try
                {
                    // Sets Focus inside model so escape key can work.
                    if (JustOpened)
                    {
                        await new BlazorStrapInterop(JSRuntime).ChangeBody(_isOpen ? "modal-open" : string.Empty); //changed null to empty
                        await new BlazorStrapInterop(JSRuntime).ChangeBodyModal(_isOpen ? "17px" : string.Empty); //changed null to empty
                        if (!IgnoreEscape)
                        {
                            await new BlazorStrapInterop(JSRuntime).ModalEscapeKey();
                            BlazorStrapInterop.OnEscapeEvent += OnEscape;
                        }
                        JustOpened = false;
                    }
                    else if (Closed)
                    {
                        Closed = false;
                        await new BlazorStrapInterop(JSRuntime).ChangeBody(_isOpen ? "modal-open" : string.Empty); //changed null to empty
                        await new BlazorStrapInterop(JSRuntime).ChangeBodyModal(_isOpen ? "17px" : string.Empty); //changed null to empty
                    }
                    for (int i = 0; i < EventQue.Count; i++)
                    {
                        await EventQue[i].InvokeAsync(BSModalEvent);
                        EventQue.RemoveAt(i);
                    }
                }
                catch
                {

                }
            }
        }
```

I don't believe `OnAfterRender` is the best place to put the method/command. It needs to be an event listener, and currently it's only marked as a one time thing... so it's never really triggered because it's instantiated as false, and never changes.

Solutions?... maybe an actual event listener from the original `bootstrap.js` (why was it even disabled?) 
Additional reference => #196

Edit: Solution 2, how about an override on `ToggleableComponentBase.Show()/Hide()` to change class attributes when triggered? (though i believe javascript would be a better tool for job, as would need to toggle specific class values, instead of emptying and loading the whole thing... which offset user-custom designs).

**Comment by chucker** [comment]
[`OnAfterRender` isn't called once](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0#lifecycle-methods) (hence its parameter `firstRun`). It's called whenever a new render was required, typically because the parameters have changed.

Your title is "Modal Backdrop is Broken", but it's not really clear to me whether you're saying something broke, or whether you disagree with some design decisions?

**Comment by herbertmilhomme** [comment]
![image](https://user-images.githubusercontent.com/15901670/65047628-c481a880-d930-11e9-882f-3a8e021fbb2b.png)

> OnAfterRender isn't called once (hence its parameter firstRun). It's called whenever a new render was required, typically because the parameters have changed.

I am fully aware...

**Comment by herbertmilhomme** [comment]
> Your title is "Modal Backdrop is Broken", but it's not really clear to me whether you're saying something broke, or whether you disagree with some design decisions?

@chucker i hope new title helps to clarify.

**Comment by chanan** [comment]
@herbertmilhomme Thanks for the snippet, we will take a look. I should mention, I just started a new job on Monday and have to go to the office most this week (instead of working from home) - so my time is limited this week, but we will try to address this issue as soon as we can

**Comment by jbomhold3** [comment]
@herbertmilhomme are you using manual triggers or ref triggers?

**Comment by herbertmilhomme** [comment]
@jbomhold3 Interesting... i didn't realize they yielded different results. Is it possible for you to offer me solutions to mimic the same results through both options? As i find one easier to implement for my needs than the  other. I believe the one i am using is "manual triggers." It's less moving parts and pieces to juggle around. But i'm disappointed that it really affects so much of my experience on both backend as well as front. Thanks for pointing that out, that the two are so radically different.

![image](https://user-images.githubusercontent.com/15901670/65061002-ff8ed680-d946-11e9-8043-b2ca92e229b3.png)

**Comment by herbertmilhomme** [comment]
I stand by my solutions offered, that the code should be `OnTriggered` (`.Hide()/.Show()`) instead of `OnComponentRender`. As one is more directly influenced why the other is not always a guarantee. Especially, when you think about it even further... why would you want a dom modifier so high up on food chain to be triggered every time, ANY element is loaded/refreshed, rather than specifically, only when it's called/needed?

**Comment by jbomhold3** [comment]
Fixed in PR #199 it's been some time since I worked with that component. A lot of the oddball behavior was to deal with the Demo Modal being rendered to the screen.

**Comment by herbertmilhomme** [comment]
@jbomhold3 thanks for speedy turn-around! i thought you would only have to modify one or two commands and that i could just copy and paste changes into my code. But i guess i'll just wait for next commit and then i'll merge changes into my local repository.

**Comment by jbomhold3** [comment]
Will have a release out today
