### ISSUE TITLE
BSModal broken scrollbar

### ISSUE THREAD

**Issue by anderjoy** [chanan/BlazorStrap#202]
Hello,

After the  last release the scrollbar of BSModal broken:

![image](https://user-images.githubusercontent.com/6249874/65157068-86ef4f00-da06-11e9-9bbf-62d77cffa84e.png)

**Comment by jbomhold3** [comment]
Looks like it's not outputting the model class in the body anymore. Going to do some testing and see what happened

**Comment by jbomhold3** [comment]
Fixed in RC1-04 release soon

**Comment by anderjoy** [comment]
> Fixed in RC1-04 release soon

Thanks...
