### ISSUE TITLE
Add Animations

### ISSUE THREAD

**Issue by jbomhold3** [chanan/BlazorStrap#203]
👍  = complete
👎  = incomplete
- Modal  👍 
- Carousels  👍 
- Collapse 👎 - Will require a design change. This animation is on hold for now.

**Comment by ChocolaDiGiCharat** [comment]
Hello! I tried 1.0.0-RC1-04 but Modal no longer shows. I have too many nested "div" tags?

**Comment by jbomhold3** [comment]
What does your model code look like? Also, make sure the javascript isn't cached.   If that still does not work add disableanimations="true"

**Comment by jbomhold3** [comment]
@ChocolaDiGiCharat  Make sure you include the <script src="_content/BlazorStrap/blazorStrap.js"></script>  in your _host.cshtml

**Comment by ChocolaDiGiCharat** [comment]
I'm creating a project that causes problems, but I can't make it in time. I'm sorry.
> disableanimations="true"

Yes shown!
> _content/BlazorStrap/blazorStrap.js

No... hidden.

**Comment by jbomhold3** [comment]
Going to attempt to remove the javascript requirement for animations. I will do another release soon disabling them by default if I don't have a fix for the issue by tomorrow.

**Comment by jbomhold3** [comment]
Javascript is no longer required for animations.

**Comment by anderjoy** [comment]
After the last release of version 101, when I close the popup, the scroll box disappears.

![image](https://user-images.githubusercontent.com/6249874/65912341-6d55ec00-e3a4-11e9-8e49-552810a7a556.png)

![image](https://user-images.githubusercontent.com/6249874/65912387-7d6dcb80-e3a4-11e9-8376-95350b0d9ad9.png)

When I close:
![image](https://user-images.githubusercontent.com/6249874/65912420-8c547e00-e3a4-11e9-8ff4-a1b1365df4da.png)

**Comment by jbomhold3** [comment]
Can you confirm the body tag still has the modal class after it's closed? Guessing its not removing properly

**Comment by ChocolaDiGiCharat** [comment]
Has  DisableAnimations been removed?
Since v.1.0.101, Modal can no longer be displayed. 
I'm checking my code...

**Comment by jbomhold3** [comment]
Yes please upgrade to 1.0.104 removed javascript from animations it was causing the issue
