### ISSUE TITLE
OnInput

### ISSUE THREAD

**Issue by Kanda** [chanan/BlazorStrap#207]
Before the update to 1.0.0 I could use oninput in the following manor:
<BSBasicInput SM="10"  @oninput="OnReferenceChanged" PlaceHolder="Product reference"></BSBasicInput>

Now in the 1.0.0 release I can't figure out how to make it work on an input. The errors the above code gives:

1. The type arguments for method 'TypeInference.CreateBSBasicInput_0<T>(RenderTreeBuilder, int, int, object, int, object, int, object, int, object)' cannot be inferred from the usage. Try specifying the type arguments explicitly.

2. Cannot convert lambda expression to intended delegate type because some of the return types in the block are not implicitly convertible to the delegate return type

3. The type of component 'BSBasicInput' cannot be inferred based on the values provided. Consider specifying the type arguments directly using the following attributes: 'T'.

This does work but I aint entirely sure this is intended on how to do it:
<BSBasicInput SM="10" Value="SearchReference" @oninput="OnReferenceChanged" PlaceHolder="Product reference"></BSBasicInput>

So I am currently unsure what the correct way is to handle oninput. Some guidance would be appreciated

**Comment by jbomhold3** [comment]
<BSBasicInput InputType="InputType.Select" Value="Selected" ValueChanged="@((string value) => SelectedChanged(value))">

**Comment by Kanda** [comment]
So how I did it is the intended way for OnInput in that case I guess.

You offer ValueChanged in your sample but that sadly only triggered for me when I left the box instead of triggering while typing.

Thanks for the feedback

**Comment by jbomhold3** [comment]
Yes, you're correct. I just offered a copy and paste a similar code we are doing in the demo

**Comment by arivera12** [comment]
I can't make the oninput event to work instead of default change event...
```
<BSInput T=string
                 Id=@nameof(record.FirstName)
                 maxlength="50"
                 @bind-Value:event="oninput"
                 @bind-Value=@record.FirstName />
```
Then I get this error
![image](https://user-images.githubusercontent.com/5600102/75920331-840ddc80-5e35-11ea-826a-5e0dd6f68689.png)

If I remove `@bind-Value:event="oninput"` then it works perfectly but only when input lost focus.

**Comment by pelshen** [comment]
@arivera12 did you work out a way of doing this? Would like to be able to update model oninput so can validate whilst typing, rather than only on blur.

**Comment by arivera12** [comment]
@pelshen I don't think so. @jbomhold3 did you an option to validate `oninput` event?

**Comment by arivera12** [comment]
@jbomhold3
Here is an implementation of debounce and Throttle. 

This should be added as an utility.

```
using System;
using System.Threading;

public class RateLimitingExtensionForObject
    {
        #region Private Properties

        private static Timer _throttleTimerInterval;
        private static Timer _debounceTimerInterval;

        private static Action<object> _debounceAction;
        private static object _lastObjectDebounce;

        private static Action<object> _throttleAction;
        private static object _lastObjectThrottle;

        #endregion

        #region Debounce

        /// <summary>
        /// Debounce reset timer and after last item received give you last item. 
        /// </summary>
        /// <param name="obj">Your object</param>
        /// <param name="interval">Milisecond interval</param>
        /// <param name="debounceAction">Called when last item call this method and after interval was finished</param>
        public static void Debounce(object obj, int interval, Action<object> debounceAction)
        {
            _lastObjectDebounce = obj;
            _debounceAction = debounceAction;
                                      
            _debounceTimerInterval?.Dispose();

            _debounceTimerInterval = new Timer(DebounceTimerIntervalOnTick, obj, interval, interval);
        }

        /// <summary>
        /// DispatchTimer tick event for debounce
        /// </summary>
        /// <param name="state"></param>
        private static void DebounceTimerIntervalOnTick(object state)
        {
            _debounceTimerInterval?.Dispose();

            if (_debounceTimerInterval != null)
            {
                _debounceAction?.Invoke(_lastObjectDebounce);
            }

            _debounceTimerInterval = null;
        }

        #endregion

        #region Throttle

        /// <summary>
        /// Throttle give you last object when timer was ticked and invoke throttleAction callback.
        /// </summary>
        /// <param name="obj">Your object</param>
        /// <param name="interval">Milisecond interval</param>
        /// <param name="throttleAction">Invoked last object when timer ticked invoked</param>
        public static void Throttle(object obj, int interval, Action<object> throttleAction)
        {
            _lastObjectThrottle = obj;
            _throttleAction = throttleAction;

            if (_throttleTimerInterval == null)
            {
                _throttleTimerInterval = new Timer(ThrottleTimerIntervalOnTick, obj, interval, interval);
            }
        }

        /// <summary>
        /// DispatchTimer tick event for throttle
        /// </summary>
        /// <param name="state"></param>
        private static void ThrottleTimerIntervalOnTick(object state)
        {
            _throttleTimerInterval?.Dispose();
            _throttleTimerInterval = null;

            if (_lastObjectThrottle != null)
            {
                _throttleAction?.Invoke(_lastObjectThrottle);
            }
        }

        #endregion
    }
```

Example on how to use?

```
//Debounce interval is expressed in milliseconds
[Parameter] public int DebounceInterval { get; set; }

public virtual void OnInputValueChanged(string value)
{
     RateLimitingExtensionForObject.Debounce(value, DebounceInterval, (valueDebounced) =>
     {
           //Do something with the valueDebounced
      });
}
```

**Comment by MasterSkriptor** [comment]
I'll work on this

**Comment by jbomhold3** [comment]
Added in 1.3.3-Preview-03

**Comment by chucker** [comment]
This issue shows ChangeEventArgs in a stacktrace [in a comment above](https://github.com/chanan/BlazorStrap/issues/207#issuecomment-594819611), so I _think_ I'm running into something related.

The following will not work in `1.3.3-Preview-03`:

```cshtml
<BSInput Id="hue" InputType="InputType.Range" min="0" max="359" @bind-Value="Model.Hue" @bind-Value:event="oninput" />
```

`Hue` is a `double`.

Trying to set the slider will throw the following:

```
Unhandled exception rendering component: Object of type 'Microsoft.AspNetCore.Components.ChangeEventArgs' cannot be converted to type 'System.Double'.
System.ArgumentException: Object of type 'Microsoft.AspNetCore.Components.ChangeEventArgs' cannot be converted to type 'System.Double'.
  at System.RuntimeType.CheckValue (System.Object value, System.Reflection.Binder binder, System.Globalization.CultureInfo culture, System.Reflection.BindingFlags invokeAttr) <0x277dfc8 + 0x000ba> in <filename unknown>:0 
[..]
```

A similar variant with regular HTML will work:

```cshtml
<input type="range" id="hue" min="0" max="359" @bind-value="Model.Hue" @bind-value:event="oninput" />
```

(As will leaving out `bind-value:event`.)

Is that a separate issue, or an edge cases of this same issue?

**Comment by MasterSkriptor** [comment]
I will find out for you @chucker

**Comment by chanan** [comment]
Reopening this issue so we can keep track of it
