### ISSUE TITLE
StateHasChanged required for updates

### ISSUE THREAD

**Issue by samartzidis** [chanan/BlazorStrap#21]
Hi, 

Thanks for developing this library. I've got a small issue, in a simple scenario where the click of a BlazorButton updates the _itemList which is one-way bound to this block:

```
<ListGroup>
    @foreach (var item in _itemList)
    {
        <ListGroupItem>@item</ListGroupItem>
    }
</ListGroup>
```

`<BlazorButton Color="Color.Primary" OnClick="@AddWord">Add</BlazorButton>`

```
void AddWord(UIMouseEventArgs e)
{
        _itemList.Add("a word");
        StateHasChanged(); // <- should not normally need this!
}
```

Blazor does not seem able to automatically detect that the DOM needs updating and I have to stick in a StateHasChanged( ) call into the OnClick handler. 

But If I use a normal html `<button>` element instead the StateHasChanged( ) call is not needed as the framework is able to automatically detect the data change and re-render the DOM. 

Is that a known/expected behaviour or a bug?

Thanks!

**Comment by chanan** [comment]
For now, you do need the `StateHasChanged` which is due to Blazor not BlazorStrap. This might have changed in Blazor V0.7 but I am not sure yet. Need to test it out :)

**Comment by samartzidis** [comment]
@chanan Thank you.
