### ISSUE TITLE
After the last release of version 101, when I close the popup, the scroll box disappears.

### ISSUE THREAD

**Issue by anderjoy** [chanan/BlazorStrap#216]
After the last release of version 101, when I close the popup, the scroll box disappears.

![image](https://user-images.githubusercontent.com/6249874/65912341-6d55ec00-e3a4-11e9-8e49-552810a7a556.png)

![image](https://user-images.githubusercontent.com/6249874/65912387-7d6dcb80-e3a4-11e9-8376-95350b0d9ad9.png)

When I close:
![image](https://user-images.githubusercontent.com/6249874/65912420-8c547e00-e3a4-11e9-8ff4-a1b1365df4da.png)

_Originally posted by @anderjoy in https://github.com/chanan/BlazorStrap/issues/203#issuecomment-536729195_

**Comment by jbomhold3** [comment]
Can you confirm the body tag still has the modal class after it's closed? Guessing its not removing properly

**Comment by anderjoy** [comment]
I just upgraded to version 104, so far could not play. And yes, there was the modal-open class in the body.

After the update, the body returned to normal after closing the modal.

**Comment by Jerrgree** [comment]
Adding in that I also had issues with the scrollbar disappearing in 1.0.101. Upgrading to 1.0.104 resolved my issue as well.
