### ISSUE TITLE
BSPaginationLink doesn't render Href

### ISSUE THREAD

**Issue by MisinformedDNA** [chanan/BlazorStrap#219]
BSPaginationLink accepts the Href property, but it doesn't actually render. So links show up as `<a class="page-link">` instead of `<a class="page-link" href="#">`, which is screwing up my CSS.

**Comment by jbomhold3** [comment]
Added in 1.0.105

**Comment by MisinformedDNA** [comment]
@jbomhold3 Thanks for [the fix](https://github.com/chanan/BlazorStrap/commit/d97497d1b478399f694bab4c8549c8afabb32789). An unfortunate side effect is that the demo site is not functioning as before.

Now when you click on the page links, the user is sent to the home page.

![image](https://user-images.githubusercontent.com/1784452/66422973-56308300-e9d0-11e9-99c1-b160bf459c7d.png)

![image](https://user-images.githubusercontent.com/1784452/66422992-5df02780-e9d0-11e9-8f19-08fa6b4a613b.png)

**Comment by jbomhold3** [comment]
Will put a javascript:void(0) in them next release.  At least we know it works now :)
