### ISSUE TITLE
OnSubmit does not fire

### ISSUE THREAD

**Issue by endeffects** [chanan/BlazorStrap#220]
I changed my form submit button from onclick to form onsubmit, but the provided delegate is not called, also the custom validation get's not triggered:

```
<BSBasicForm UserValidation="true" @onsubmit="@(async () => await this.Move(this.State.Request))">
    <h3>Move</h3>
    <PositionView Position="@this.State.Request.Position" State="@this.State" />
    <BSFormGroup>
        <BSButton ButtonType="ButtonType.Submit" class="w-100">Move</BSButton>
    </BSFormGroup>
</BSBasicForm>
```

I saw that you do not add the required Attribute for the Basic Form

`Formbuilder.AddAttribute(5, "OnSubmit", OnSubmit);`

**Comment by jbomhold3** [comment]
Added in 1.0.105
