### ISSUE TITLE
BlazorStrap Extension: FluentValidation Support

### ISSUE THREAD

**Issue by endeffects** [chanan/BlazorStrap#223]
Steve Sanderson provided a good solution to support Fluent Validation for Blazor.
So maybe this is a good enhancement for BlazorStrap too.

https://blog.stevensanderson.com/2019/09/04/blazor-fluentvalidation/

**Comment by jbomhold3** [comment]
Custom valdation types are already supported.. Use BSForm, BSInput

**Comment by jbomhold3** [comment]
I use a fluent validator in my person project already

**Comment by endeffects** [comment]
Yeah, i know. I just thought it is a good improvement.
