### ISSUE TITLE
Checkbox can't be bound using @bind-Value="@boolProperty" or accepting Value="true"

### ISSUE THREAD

**Issue by 1Stan2Harris** [chanan/BlazorStrap#224]
I'm trying to set the value of the checkboxes checked state to match a boolean value from my model.  When, it doesn't allow bind value syntax, nor allow me to set the value once my api returns. 
 Any suggestions?
Compiler error:
<BSBasicInput InputType="InputType.Checkbox" Id="defaultCheck1" @bind-Value="@prod.IsActive"/>
 
Doesn't set the check box:
<BSBasicInput InputType="InputType.Checkbox" Id="defaultCheck1" Value="true"/>

**Comment by jbomhold3** [comment]
Highly suggest you use BSInput and BSForm if you have a modal. BSBasicInput is intended for people needing to render control without any of the automation. These two controls are getting closer closer to being the same thing, And I see a near future where they likely will be .Net Core 3.1.  For now keep in mind normal use is BSInput inside of BSForm and special use is BSBasicInput.  That being said <BSBasicInput InputType="InputType.Checkbox" @bind-Value="@boolbind" /> should work just fine.  You might be getting a oddball conversion error. Try something like
<BSBasicInput InputType="InputType.Checkbox" @bind-Value="@auto.Check" ConversionError="@(value => {stringerror = value;})"/> to capture it.
