### ISSUE TITLE
New Features

### ISSUE THREAD

**Issue by jbomhold3** [chanan/BlazorStrap#225]
Very curious about everyone's input on this. Keep in mind the goal of the project is to stay true to bootstrap.  We can use this thread to brainstorm. I'll start off. I want to add a real toaster. Myself, and Chanan have said it a few times but it hasn't been given a lot of priority.

**Comment by chucker** [comment]
> Keep in mind the goal of the project is to stay true to bootstrap.

Is there a list of missing of what's missing but still planned?

E.g.,

* Spinner
* checkbox/radio button variants of Button

**Comment by arivera12** [comment]
Stepper component? 

It should behave very closely to the tabs component but should 

- Expose a property to select the index of the step.
- Forward steps navigation should be deactivated until step is available.

Haven't test the tabs components itself to see if is possible to disable/deactivate navigation.

I will give feedback soon.

**Comment by arivera12** [comment]
### FluentValidation

IMO fluentvalidation offers more advance validation system that .net  validation attributes that would be a huge plus. It seems someone have already done an integration with blazor but won't integrate with BSInput and BSFormFeedback components. [https://github.com/Blazored/FluentValidation](https://github.com/Blazored/FluentValidation)

**Comment by timbze** [comment]
I see you have it in and issue in your extension repo, but some autocomplete typeahead like this would be cool: https://github.com/loresoft/LoreSoft.Blazor.Controls (I am actually using this one in a project I'm doing)

**Comment by timbze** [comment]
Not in bootstrap from what I can find, but this would be a great component to have: https://blazor.radzen.com/checkboxlist

**Comment by chanan** [comment]
I might need to create a "remote" data table for work next week, so if I do, I will add to extensions as well.

**Comment by timbze** [comment]
> Stepper Component

I just set one up manually using `BSBreadcrumb`
![Screenshot from 2020-12-04 11-26-45](https://user-images.githubusercontent.com/35117769/101194442-a2eb0a80-3623-11eb-9f2b-973ed5d33196.png)
