### ISSUE TITLE
Documentation Site on iPad Broken?

### ISSUE THREAD

**Issue by scottkuhl** [chanan/BlazorStrap#226]
The documentation site, https://blazorstrap.io/, does not seem to be working for me on an iPad running iOS 13.  Anyone else having this issue?

It’s working fine on my Note 10+.

**Comment by jbomhold3** [comment]
It does not surprise me Blazor wasm has had issues with IOS since day one. I think they have a fix in 3.1 for this.  We are considering changing the docs site to server-side. I will test IOS at work tomorrow.

**Comment by chucker** [comment]
Yes, this is currently broken in iOS 13 / Safari 13 (but not older versions), for two reasons:

* there's a bug in how `Module` is defined (I put a workaround in the documentation site, hoping that would be enough)
* Safari aggressively limits the size of the call stack. The documentation site still suffers from this.

@jbomhold3 [the workaround that works for me](https://github.com/mono/mono/issues/16986) requires replacing the `blazor.webassembly.js` manually. There's work in Mono to make the next Blazor preview handle this more gracefully (by reducing how much of the stack it uses).

**Comment by jbomhold3** [comment]
@chanan   Do we want to apply this?  It's going to be something we have to keep track of any make sure we don't override until its fully fixed in the framework.

**Comment by chanan** [comment]
@jbomhold3 I saw this in the mono repo... I was hoping to avoid it :) But since we have no idea when this might be fixed (ASPNet 3.1?) might be that we have no choice?

**Comment by jbomhold3** [comment]
I applied the first preview version does it help any?

**Comment by chucker** [comment]
@jbomhold3 if you're saying that blazorstrap.io already runs it, no, it doesn't help. It still yields:

    Unhandled Promise Rejection: RangeError: Maximum call stack size exceeded.

**Comment by chucker** [comment]
This should be resolved in 3.1 final. See https://github.com/mono/mono/issues/16986

**Comment by arivera12** [comment]
This issue sees to be fixed on wasm latest version.
