### ISSUE TITLE
Manual entry of InputType.Date doesn't enforce format

### ISSUE THREAD

**Issue by Gander7** [chanan/BlazorStrap#227]
I understand that the forms are under development but wanted to make sure this was on your radar.

```
<BSFormGroup>
                    <BSLabel For="dateOpened" Size="Size.Small">Date Opened</BSLabel>
                    <BSInput InputType="InputType.Date" Id="dateOpened" @bind-Value="@data.DateOpened" Size="Size.Small" ValidateOnChange="true"/>
                    <BSFormFeedback For="@(() => data.DateOpened)"/>
                </BSFormGroup>
```

Datepicker portion works well imo.
Manually entry doesn't follow placeholder format. It accepts the year as 6 digits before moving to the month rather than 4.

Issue in action:
https://gyazo.com/1ebee2a7a5bcb803603c4bc4bc05deee

**Comment by jbomhold3** [comment]
What browser are you using? Our datetime is nothing more than the default date input type.  So it uses the browsers built-in one. I could be a localization issue.

**Comment by Gander7** [comment]
@jbomhold3 You're right, it's the default date input type. I believe it's because the input can handle dates past 9999-12-31. Found a solution [here](https://stackoverflow.com/questions/24603919/html5-date-input-6-digit-year).

By adding a `max="9999-12-31"` to the control, it will force 4 digits for selection.
Imo this issue can be re-purposed as either a feature request to add the max by default or tagged as not an issue. :)

**Comment by jbomhold3** [comment]
@chanan  What's your opinion?

**Comment by chanan** [comment]
If its a default html prop, wont setting it on BSInput just pass it down to input? (because of the splat)

**Comment by Gander7** [comment]
@chanan That's what I've done in my project. I've passed the attribute to the BSInput component.

Just thinking that it would be a reasonable assumption that most users won't need dates past year 9999, and if they don't catch this behavior, it would cause an issue with their users. 

If it was set on the BSInput as default, then someone could possibly override if they needed to.

**Comment by chanan** [comment]
@jbomhold3 I am good with this change if you are.
@Gander7 Any chance you want to submit a PR? :)

**Comment by Gander7** [comment]
@chanan I can take a look :)

**Comment by Gander7** [comment]
@chanan @jbomhold3 
I'm good for this to be closed since the PR has been merged.
