### ISSUE TITLE
C# Acronyms Naming Guidelines

### ISSUE THREAD

**Issue by achmstein** [chanan/BlazorStrap#228]
Can you follow C# acronyms naming guidelines?
**DO** capitalize only the first character of acronyms with three or more characters, except the first word of a camel-cased identifier.

`await BootstrapCSS.SetBootstrapCSS("4.3.1");` should be `await BootstrapCss.SetBootstrapCss("4.3.1");`

**Comment by jbomhold3** [comment]
@chanan You're fired!! You named something wrong. Ok not fired, grounded. Ok not grounded even. However, will let you address this one.

**Comment by SayusiAndo** [comment]
Is this something needs to be fixed?

**Comment by blinard** [comment]
Hey @chanan  or @jbomhold3  - I'm not sure why this issue didn't close out when PR #265 went in but it should have. Not sure if I'm able to close out this issue at this point; one of you guys might need to close it.
