### ISSUE TITLE
How can you run the Sample project?

### ISSUE THREAD

**Issue by romanoza** [chanan/BlazorStrap#23]
It's a lame question probably but I can't run your project (Sample). Should I add the server part? (I'm new to Blazor)

**Comment by chanan** [comment]
You shouldn't need to add anything. I will update this weekend to 0.7.0 and ensure the sample runs.

**Comment by chanan** [comment]
I just tried running the sample V. 0.7.0 and didn't encounter any issues. What exactly are you seeing?

**Comment by chanan** [comment]
@romanoza Did you get it working? Can we close this?

**Comment by chanan** [comment]
Global json in the sample project has:

```
{
  "sdk": {
    "version": "2.2.100"
  }
}
```
