### ISSUE TITLE
BlazorStrap launchSettings.json into Nuget Package

### ISSUE THREAD

**Issue by IvanJosipovic** [chanan/BlazorStrap#233]
BlazorStrap1.1.0-preview1-02 appears to be packing launchSettings.json while it shouldn't be.
content\Properties\launchSettings.json

Steps to repro:

1. Create new Blazor Project
2. Add BlazorStrap Nuget
3. lunchSettings.json shouldn't be visible
![image](https://user-images.githubusercontent.com/9521987/67216555-405f8c80-f3d8-11e9-8d24-98c3441bae17.png)

**Comment by jbomhold3** [comment]
Will look into it

**Comment by jbomhold3** [comment]
It's removed. However, not going to do a release for just this so it will be fixed in the next release. For now, you should be able to right-click it and exclude it from the project.

**Comment by IvanJosipovic** [comment]
No problem, much appreciated!
