### ISSUE TITLE
Internet Explorer 11 error

### ISSUE THREAD

**Issue by phisakel** [chanan/BlazorStrap#237]
JavaScript critical error at line 92, column 25 in https://localhost:44380/_content/BlazorStrap/blazorStrap.js\n\nSCRIPT1014: Invalid character

**Comment by peterblazejewicz** [comment]
That's because of the ES2015 (non-ES5) string literals used there:
https://github.com/chanan/BlazorStrap/blob/master/src/BlazorStrap/wwwroot/blazorStrap.js#L92
Let me look

**Comment by chanan** [comment]
IE 11 doesnt do string literals? Well that will be an easy fix

**Comment by peterblazejewicz** [comment]
> IE 11 doesnt do string literals? Well that will be an easy fix

Nope, other magic also missing :) Made the PR, thanks!
