### ISSUE TITLE
Card Deck doesn't refresh : <BSCard CardType="CardType.Deck">

### ISSUE THREAD

**Issue by 1Stan2Harris** [chanan/BlazorStrap#242]
I have a menu that has multiple links to a products page, each link changes the product type so when clicked the products page should reload the card deck.  

Once the parameters are set (override async Task OnParametersSetAsync()) I call a function (GetData()) which refreshes the list of products via an API call to the database.  The cards don't refresh, however; an HTML table pointing to the same products list refreshes as I click the menu items. I've tried with and without using StateHasChanged() and the card deck doesn't refresh yet the table will refresh each time.  Do I need to make unbind and rebind the card deck to refresh it?

**Comment by chanan** [comment]
Are you able to get a small reproduction? Maybe from a json file instead of a database?

**Comment by 1Stan2Harris** [comment]
Yes,
I've modified the VS2019 sample program weather forecasts
1. Add nuget for BlazorStrap 
2. Modify the Weather forecast service to get 10 forecasts
3. Modify menu to pass an int parameters from the menu
4. Add second link, to pass a different parameters from the menu
5. Modify FetchData.razor - to create a deck and add some cards.
[BlazorApp6.zip](https://github.com/chanan/BlazorStrap/files/3826085/BlazorApp6.zip)

**Comment by chanan** [comment]
Thanks, we will try it out and get back to you

**Comment by 1Stan2Harris** [comment]
Thanks,
It appears as if it looses it's binding to the list of objects.
