### ISSUE TITLE
[Question] How to DateTime-Local and DateTime binding. 

### ISSUE THREAD

**Issue by ChocolaDiGiCharat** [chanan/BlazorStrap#243]
Hi,
I tried binding but DateTime.Now is not displayed in the form element.
Please give me advice.

```
<!-- -->
 <BSBasicInput InputType="InputType.DateTimeLocal" @bind-Value="@start_timestamp" Size="Size.Small">
<!-- -->

@code {
private DateTime start_timestamp { get; set; } = DateTime.Now;
}
```

**Comment by arivera12** [comment]
This is a serious problem over the browsers. 

The browser parses the value with a specific format but the browser based on his locales displays on a specific format take a look of [this](https://stackoverflow.com/questions/7372038/is-there-any-way-to-change-input-type-date-format)

The only way to have date, time and datetime implementation working correctly over blazor is to build this specific components.

In the meantime I have been using https://github.com/nheath99/NodaTimePicker. 

I think is currently the only free and working out box component for blazor for date and time.

I have use it in a while a work perfectly. 

Give it a try.

PS. I know this doesn't answer the question and this may be off topic but BlazorStrap needs to support this in any near future update. 

@chanan what you think about this? Are there any plans for this?

**Comment by chucker** [comment]
Semi-OT: unless things have changed, it should be noted that Blazor WebAssembly doesn't handle timezones right. Make sure you pull in https://github.com/jsakamoto/Toolbelt.Blazor.TimeZoneKit as a package if you need this.

**Comment by arivera12** [comment]
@chucker have you compared the difference between nodatimepicker and timezonekit?

**Comment by arivera12** [comment]
@chucker are there plans to support date and time pickers?
