### ISSUE TITLE
BlazorStrap Modal only showing backdrop for server-side Blazor

### ISSUE THREAD

**Issue by tobbi** [chanan/BlazorStrap#244]
I'm not sure if this is an actual issue or a support request. Anyway, here goes:
This is my _Host.cshtml:
```html
@page "/"
@namespace ImportTool.Server.Pages
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>IKON Import-Tool</title>
    <base href="~/" />
    <link href="css/bootstrap/bootstrap.min.css" rel="stylesheet" />
    <link href="css/site.css" rel="stylesheet" />
</head>
<body>
    <app>
        @(await Html.RenderComponentAsync<ImportTool.Client.App>(RenderMode.Server))
    </app>

    <script type="text/javascript" src="blazor.polyfill.min.js"></script>
    <script id="blazorMode"></script>
    <script>
        function isIE() {
            ua = navigator.userAgent;
            /* MSIE used to detect old browsers and Trident used to newer ones*/
            var is_ie = ua.indexOf("MSIE ") > -1 || ua.indexOf("Trident/") > -1;

            return is_ie;
        }

        document.getElementById("blazorMode").src =
            isIE() ? "_framework/blazor.server.js" : "_framework/blazor.webassembly.js";
    </script>

<!-- BlazorStyled is used by BlazorStrap documentation site -->
<script async defer src="https://buttons.github.io/buttons.js"></script>

    <!-- The below two files are needed by BlazorStrap -->
    <script src="_content/BlazorStrap/blazorStrap.js"></script>
    <script src="_content/BlazorStrap/popper.min.js"></script>
</body>
</html>
```

I'm using the BlazorDualMode as described here: https://github.com/Suchiman/BlazorDualMode (not sure if that matters or not).

I'm using BlazorStrap 1.0.105.

When the modal is supposed to show, it only shows the backdrop. I have the following code in my .razor file:
```html
  <BSModal @ref="ValidationInProgressModal" IgnoreClickOnBackdrop="true" IsCentered="true" IgnoreEscape="true">

            <BSModalHeader>Analyse gestartet...</BSModalHeader>

            <BSModalBody>
                <p style="font-size:14px;">
                    Bei einer großen Anzahl von zu importierenden Datensätzen kann es vorkommen, dass die Seite zeitweilig nicht mehr auf Benutzereingaben reagiert.
                    Klicken Sie in diesem Fall ggf. auf die Schaltfläche "Warten" und warten Sie, bis die Analyse beendet ist.
                </p>
                <BSProgress Value="100" IsStriped="true" IsAnimated="true">Datei wird analysiert...</BSProgress>
            </BSModalBody>

        </BSModal>

        <BSModal @ref="ImportInProgressModal" IgnoreClickOnBackdrop="true" IsCentered="true" IgnoreEscape="true">

            <BSModalHeader>Import gestartet...</BSModalHeader>

            <BSModalBody>
                <p style="font-size:14px;">
                    Bitte warten Sie, während die ausgewählten Datensätze in die Datenbank importiert werden...
                </p>
                <BSProgress Value="100" IsStriped="true" IsAnimated="true">Import...</BSProgress>
            </BSModalBody>

        </BSModal>
```

and I'm calling it from within that razor file like so:
```csharp
ValidationInProgressModal.Show();
```

This all works fine in Client (WebAssembly) BlazorStrap.

Sorry for this being rather vague, if you need any more information, please ask.

**Comment by DubRave** [comment]
I'm having the same issue. A little investigation and comparing the modal example to my own result I notice that the main div for the modal is rendered without inline style `style="display: block; padding-right: 17px;"`. I Also thnik the css class "show" is missing when rendered.

**Comment by jbomhold3** [comment]
Going to leave this open for reference for the workaround. However, I don't want to add a bunch of tweaks to support a dated browser. I know some companies still use it, most are finally moving away . Since as there is a working workaround and it would require browser-dependent code I don't see a reason to do this.  We will continue to take feedback on it and this issue will stay open so it's easy to find.

**Comment by DubRave** [comment]
This is not just an Internet Explorer issue, I was having the same issue using Chrome.

**Comment by tobbi** [comment]
Changed title as per https://github.com/chanan/BlazorStrap/issues/244#issuecomment-559465454

**Comment by zbecknell** [comment]
> This is not just an Internet Explorer issue, I was having the same issue using Chrome.

I'm also having this issue on Chrome and Firefox.  I just started dual-targetting both CSB and SSB, and SSB fails to show the modal (but does display the backdrop).

**Comment by zbecknell** [comment]
Ahh, turns out I just needed to follow instructions.  When I created my server-side host view I didn't include the JS:

```html
<script src="_content/BlazorStrap/blazorStrap.js"></script>
```

**Comment by DubRave** [comment]
@zbecknell thanks, seems I missed that step as well :)

**Comment by tobbi** [comment]
I'm sorry, but this issue is not resolved.

I figured out why it's happening: Upon loading the blazorStrap.js file, the following error occurs:
```
SCRIPT1003: ':' expected
blazorStrap.js (115,22):
```

**Comment by zbecknell** [comment]
@tobbi If you haven't updated to `preview4` Blazor packages I would suggest it.  I believe your problem MAY be because you're dual-booting and prior to preview4 only SSB needed the script tag.  Now that preview4 is out, both SSB/CSB need the script tag included, as CSB before was grabbing the needed JS itself (which may've been the source of your problem?).
