### ISSUE TITLE
Displayed sample code is obsolete

### ISSUE THREAD

**Issue by rpskelton2** [chanan/BlazorStrap#246]
At least on the carousel page...  If you copy & paste the code from the demo site there are a bunch of malformed tags and some missing javascrip.  If I pull the code directly from github source it's fine.

**Comment by jbomhold3** [comment]
Thanks, for reporting we will fix the snippet .

**Comment by SayusiAndo** [comment]
Other pages also obsolete. If I can get access to the page I'm happy to invest some time to fix the samples.

**Comment by chanan** [comment]
That would be awesome!

The sample site is at: https://github.com/chanan/BlazorStrap/tree/master/src/SampleCore/Pages
The code snippets are at: https://github.com/chanan/BlazorStrap/tree/master/src/SampleCore/wwwroot/snippets

You can easily run it locally by cloning the whole repo, opening up the solution in VS Studio, then running either the project in Sample (Client side), or the project in ServerSideSample (server side obviously).

**Comment by SayusiAndo** [comment]
Thanks, I'll take a look at it soon.

**Comment by SayusiAndo** [comment]
I created a PR (#257) for Modal fixes. In the following days I'm going through all components.
