### ISSUE TITLE
No way to turn of carousel auto slide

### ISSUE THREAD

**Issue by rpskelton2** [chanan/BlazorStrap#247]
As described here, in bootstrap you can set interval=false or data-interval=false.  Blazorstrap uses an int for that parameter so false is not possible.  data-interval= false is ignored.  If you want to keep a strongly typed int Interval then another way need to be provided to turn off auto slide changing.

https://stackoverflow.com/questions/14977392/bootstrap-carousel-remove-auto-slide

**Comment by chanan** [comment]
If we allow 0 to mean turn off auto slide would that work?

**Comment by rpskelton2** [comment]
Works for me!  Maybe just Interval < 1 means off?  Either way is fine.

**Comment by jbomhold3** [comment]
Interval = 0 will disable auto slide

**Comment by bigabdoul** [comment]
> Interval = 0 will disable auto slide

I tried version 1.3.2 with no luck now I'm using version 1.3.3-Preview-03 from Nuget and this still does not work. The timer doesn't allow 0. In the browser dev tools' console:

**Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Invalid value '0' for parameter 'interval'.
System.ArgumentException: Invalid value '0' for parameter 'interval'.
  at System.Timers.Timer..ctor (System.Double interval) <0x3ae8b08 + 0x0004e> in <filename unknown>:0 
  at BlazorStrap.BSCarouselBase.OnInitialized () <0x3ae89f8 + 0x00018> in <filename unknown>:0 
  at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync () <0x2d48d90 + 0x00030> in <filename unknown>:0**

**Comment by bigabdoul** [comment]
I took a look at the source code and realized that you initialize the Timer component with **Interval**. If Interval == 0 the Timer's constructor will throw an exception.
```C#
protected override void OnInitialized()
{
    if (Timer == null)
    {
        Timer = new Timer(Interval);
        Timer.Elapsed += OnTimerEvent;
        Timer.AutoReset = true;
        if (Interval == 0)
            return;
        Timer.Start();
    }
}
```
You should consider changing this to:
```C#
protected override void OnInitialized()
{
    if (Timer == null)
    {
        Timer = new Timer { AutoReset = true };
        Timer.Elapsed += OnTimerEvent;
        if (Interval > 0)
        {
            Timer.Interval = Interval;
            Timer.Start();
        }
    }
}
```

**Comment by mark-at-tusksoft** [comment]
This should be reopened, as it is still broken. I guess i'll just set the interval to int.MaxValue for now ¯\_(ツ)_/¯

**Comment by mark-at-tusksoft** [comment]
@jbomhold3 Reason for closing? Was this fixed?
