### ISSUE TITLE
Modal body not showing when open modal

### ISSUE THREAD

**Issue by mghanem-itg** [chanan/BlazorStrap#248]
This is the example :

```
<BSButton Color="Color.Primary" OnClick="@(() => LiveDemo.Show())">Launch demo modal</BSButton>
   <BSModal @ref="LiveDemo">
       <BSModalHeader OnClick="@(() => LiveDemo.Hide())">Modal title</BSModalHeader>
       <BSModalBody><p>Modal body text goes here.</p></BSModalBody>
       <BSModalFooter>
           <BSButton Color="Color.Secondary" OnClick="@(() => LiveDemo.Hide())">Close</BSButton>
           <BSButton Color="Color.Primary" OnClick="@(() => LiveDemo.Hide())">Save Changes</BSButton>
       </BSModalFooter>
   </BSModal>

@code {
   BSModal LiveDemo;
}

```

when click on the button UI blocked as expected but modal body is not showing.

**Comment by jbomhold3** [comment]
Not Able to repo what browser?

**Comment by mghanem-itg** [comment]
@jbomhold3 I'm using chrome.
I think this is similar opened issue  https://github.com/chanan/BlazorStrap/issues/244

**Comment by jbomhold3** [comment]
Make sure you have the script included

**Comment by rrvanleeuwen** [comment]
I have exactly the same here.
All worked with .netstandard2.0 and older aspnetcore blazor preview.
After upgrade the project from .netstandard 2.0 to 2.1 and latest aspnetcore.blazor 3.1.0-preview4.19579.2 it stopped working. 
UI disabled, but no popup. In both browsers: chome and edge
I tried also to copy the content folder from netstandard2.0\dist\_content to netstandard2.1\dist\_content, no difference

**Comment by rrvanleeuwen** [comment]
OK, after reading #244 I tested to include <script src="_content/BlazorStrap/blazorStrap.js"></script> also in index.html and it worked. 
Strange thing that before updating to .netstandard 2.1 it worked withoud this script included...

**Comment by mghanem-itg** [comment]
Issue fixed by adding the js reference, thanks!

**Comment by jainrishabh67** [comment]
I already have the script reference added to Index.html but still has the above-mentioned problem

**Comment by gavnlh** [comment]
@jainrishabh67 I've just had the same problem after creating a new project with BlazorStrap v 1.3.3 .  I reverted to version 1.3.2 and the modal appeared.
Also, to get the right Script tags,  etc. I find this to be a great example:   https://github.com/thbst16/BlazorCrud

**Comment by jainrishabh67** [comment]
@gavnlh Thanks for the reply 💯 
Yeah, I am not sure what is the problem, also this issue is closed anyway, looks like I should raise another case.

**Comment by farzad528** [comment]
I am having the exact same issue.

**Comment by jbomhold3** [comment]
Can someone provide a example project with the issue. Not seeing this behavior in core.
