### ISSUE TITLE
Investigate using cascading values and parameters

### ISSUE THREAD

**Issue by chanan** [chanan/BlazorStrap#25]

**Comment by BlackFenix2** [comment]
This can work really well with Toasts, Cards and Modals. i can make a PR for Toasts and work from there.

**Comment by chanan** [comment]
Please do!Most of the time i had to work on this lately has been going towards what to do with forms and inputs

**Comment by chanan** [comment]
This is too broad of an issue. We now use Cascading values in some places. Closing this in favor of opening specific issues such as #106
