### ISSUE TITLE
Can someone give an example of using MRAuto?

### ISSUE THREAD

**Issue by bholland314** [chanan/BlazorStrap#256]
I'm trying to do a 2 column layout with the first col taking up 11 columns and I want a single column on the far right. Normally this is done with class="mr-auto", but I can't seem to get it to work with BlazorStrap's MRAuto property.
Thanks

**Comment by jbomhold3** [comment]
<BSRow Class="d-flex flex-row">
    <BSCol MDMRAuto="true">Test 1</BSCol>
    <BSCol MD="1">Test 2</BSCol>
</BSRow>
