### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by SayusiAndo** [chanan/BlazorStrap#258]
I'd like to offer my help because I have a few hours in a week for working on for example this project, since my project leverages on this too. Before I jump in and start doing anything, possibly messing up something, I'd like to get some info about the next steps. What plans do you guys have for the next release? What should be fixed, enhanced etc? Is there a roadmap for the future? Could you pull together these tasks in a project?

**Comment by chanan** [comment]
Hi @SayusiAndo,

Other than the items in issues we dont have anything big planned right now. We want to have feature parity with react bootstrap libraries (there are 2), which we are pretty close, just need to re-review and find any gaps.

One item that is not on the list is to upgrade to the latest cssBuilder library that was just released (https://github.com/EdCharbeneau/CssBuilder) - which should be simple.

Both John and I would appreciate the help - we both got pretty busy lately with other things and haven't been able to devote a lot of time to BlazorStrap.
