### ISSUE TITLE
Question - How to actually use BlazorStrap with a Blazor Site

### ISSUE THREAD

**Issue by drewid** [chanan/BlazorStrap#26]
A dumb question most likely, but how do you actually use BlazorStrap with a Blazor site?

What are the steps for getting going?

**Comment by drewid** [comment]
Getting the following error when running the Sample project in Visual Studio 2017 with the latest necessary to run Blazor - "No process is associated with this object".

Also, with just looking at the code, is not clicking how the bootstrap and blazor mix, when trying to use a bootsrap template

**Comment by chanan** [comment]
@drewid I dont know what that error means. Are you using VS 2017 V 15.9.2 (release) and are you sure you have Blazor 0.7 installed?

The sample projects help show the usage as well as the docs: https://chanan.github.io/BlazorStrap/

The basics: 

1. Start a new (client side, haven't tested with server side) Blazor project
2. Install from nuget the latest version of BlazorStrap: Install-Package BlazorStrap -Version 0.7.0
3. Add the tag helper to your _ViewImports.cshtml: @addTagHelper *, BlazorStrap
4. Use the tags in your views for example:

```
<Alert Color="Color.Primary">
    This is a primary alert — check it out!
</Alert>
```

**Comment by drewid** [comment]
Tried it in two projects - one I am getting the same error, the other I am getting:
`The name 'Color' does not exist in the current context` in the file index.cshtml and index.g.cs

**Comment by chanan** [comment]
You are right I missed a step. In your view or in _ViewImports add:
```
@using BlazorStrap
```

Sorry about that.

**Comment by nic0l45** [comment]
CS0433	The type 'IWebAssemblyHostBuilder' exists in both 'Microsoft.AspNetCore.Blazor.Browser, Version=0.7.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Blazor, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'	MercuryRepRH.Client	


I have this error, when i build my solution, using Blazor 3.0.0-preview4-19216-03

**Comment by chanan** [comment]
It seems like the error is saying that the solution still have Blazor V7 in it, I will recheck BlazorStrap but I don't think its coming from there, can you check your solution and any Blazor deps you might have to see if it comes from somewhere else?

**Comment by nic0l45** [comment]
> It seems like the error is saying that the solution still have Blazor V7 in it, I will recheck BlazorStrap but I don't think its coming from there, can you check your solution and any Blazor deps you might have to see if it comes from somewhere else?

I''ll check, thank you.

**Comment by nic0l45** [comment]
![image](https://user-images.githubusercontent.com/48603062/57387655-bc487e00-7184-11e9-9365-15e1a81e0135.png)

Hi i have this error too, the first one that i reported was solved, but when i try to add the tag helper to the _Imports.razor page happens this. Thanks in advance.

**Comment by chucker** [comment]
Starting with ASP.NET Core 3.0 Preview 4, you don’t use a tag helper any more. Just import the namespace.

**Comment by nic0l45** [comment]
![image](https://user-images.githubusercontent.com/48603062/57390490-7a223b00-718a-11e9-8851-65f8002d0190.png)

I have this now.

**Comment by zwei222** [comment]
Your BlazorStrap is ver.0.7.1?
The solution is to install the preview version. I solved it with that.

**Comment by chanan** [comment]
Closing this now, but please feel free to ask anymore questions.
