### ISSUE TITLE
Setup docs mistake

### ISSUE THREAD

**Issue by MichaelSL** [chanan/BlazorStrap#261]
It seems like there was an error in Setup documentation using `Client side` for both client and server side setup:

![image](https://user-images.githubusercontent.com/2205113/73131675-2506ad80-3fd5-11ea-9466-3de211ef58a9.png)

**Comment by chanan** [comment]
Thanks for letting us know, will update shortly

**Comment by MasterSkriptor** [comment]
@chanan Is this issue still open. It looks to have been corrected.

**Comment by frogcrush** [comment]
@MasterSkriptor it looks like it's still the same for me, I've just started looking at using the project and got kinda confused by which was which.

**Comment by chanan** [comment]
Updated the instructions to include that services.AddBootStrapCss is required now
