### ISSUE TITLE
Updated to Web Assembly 3.2.0 preview1

### ISSUE THREAD

**Issue by chanan** [chanan/BlazorStrap#264]

**Comment by chanan** [comment]
When running in client side, navmenu and sidebar aren't showing.

**Comment by stanac** [comment]
I would add that BsModal isn't showing after upgrade (only backdrop)

**Comment by chanan** [comment]
I haven't been able to migrate to 3.2 at all yet, so I am not surprised some things won't right if you take the 3.1 version of blazorstrap and put in a 3.2 preview version

**Comment by stanac** [comment]
I don't have a lot of front-end code, that might be the reason why it's partially working (I am trying to remember where BS components are used, if they are at all in the app, beside the modal), to run the app I had to comment out `bootstrapCSS.SetBootstrapCSS("4.3.1")`

**Comment by chanan** [comment]
@jbomhold3 I need a second pair of eyes on this. Everything is fine in server mode, but in client mode, the top nav and left nav are hidden. No idea why.

**Comment by jbomhold3** [comment]
Ok will take a look

**Comment by chucker** [comment]
@stanac hmm, the modal works for me. Make sure you have `<script src="_content/BlazorStrap/blazorStrap.js"></script>` in your `index.html` or `_Host.cshtml` (depending on WASM or Server). This requirement is new for Blazor WASM in .NET Core 3.1 final, alas.

**Comment by chanan** [comment]
Just keep in mind that we haven't recompile BlazorStrap to 3.2 preview 1 yet due to an issue running the client side docs site.

**Comment by stanac** [comment]
@chucker thanks, modals are working after adding the script tag.

**Comment by chucker** [comment]
@chanan yes, I see what is presumably your issue if I don't include the CSS.

**Comment by chanan** [comment]
weird, i will keep workng on it, this week has been late nights at work, so couldnt do it yet.
