### ISSUE TITLE
Q: up for grabs

### ISSUE THREAD

**Issue by grahamehorner** [chanan/BlazorStrap#27]
I would love to help out with this project; it would be good to mark issues or items in backlog as 'up for grabs'

**Comment by chanan** [comment]
@grahamehorner Feel free to grab anything right now, I have 2 other Blazor projects that I am havinig issues upgrading past 0.5.0 that I need to work on, so go for it! I would love help working on this!

**Comment by grahamehorner** [comment]
@chanan cool more than happy to assist with this project, are there any issues or features that you would do as a priority?

**Comment by chanan** [comment]
@grahamehorner Go for what ever you like! :)

**Comment by chanan** [comment]
Closing this now, but please everyone submit PRs :)
