### ISSUE TITLE
Correction documentation 

### ISSUE THREAD

**Issue by fabianus76** [chanan/BlazorStrap#271]
Here: 
https://blazorstrap.io/dropdowns

in the "Directions" section

there is confusion between BSButtonGroup and BSDropdown

![image](https://user-images.githubusercontent.com/18581848/75855911-894a3780-5df3-11ea-9280-40be5d0a45c1.png)

**Comment by chanan** [comment]
It looks right to me based on the code in https://github.com/chanan/BlazorStrap/blob/master/src/SampleCore/Pages/Dropdowns.razor#L202-L219
