### ISSUE TITLE
Alert Dismiss

### ISSUE THREAD

**Issue by MasterSkriptor** [chanan/BlazorStrap#273]
Is there plans for adding the ability to close an alert through an event, so that it can be closed using a timer for example?

Unless I am missing something I do not see a way to do this.

**Comment by chanan** [comment]
Hi @MasterSkriptor - Yes, that is is an oversight. Would you like a method on the alert to close it?

**Comment by MasterSkriptor** [comment]
That would be great!

**Comment by chanan** [comment]
Exposed IsOpen property on the BSAlert tag to show and hide the alert. It's available in 1.3.0 that was just released

**Comment by MasterSkriptor** [comment]
Works beautifully. Thanks.
