### ISSUE TITLE
Why it is: Cannot process pending renders after the renderer has been disposed.?

### ISSUE THREAD

**Issue by win32nipuh** [chanan/BlazorStrap#277]
> The thread 0x6cc4 has exited with code 0 (0x0).
> Exception thrown: 'System.Net.Internals.SocketExceptionFactory.ExtendedSocketException' in System.Net.Sockets.dll
> Exception thrown: 'System.ObjectDisposedException' in Microsoft.AspNetCore.Components.dll
> Exception thrown: 'System.ObjectDisposedException' in Microsoft.AspNetCore.Components.dll
> Exception thrown: 'System.ObjectDisposedException' in System.Net.Sockets.dll
> Exception thrown: 'System.ObjectDisposedException' in System.Private.CoreLib.dll
> Exception thrown: 'System.ObjectDisposedException' in Microsoft.AspNetCore.Components.dll
> Exception thrown: 'System.ObjectDisposedException' in Microsoft.AspNetCore.Components.dll
> Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer: Warning: Unhandled exception rendering component: Cannot process pending renders after the renderer has been disposed.
> Object name: 'Renderer'.
> 
> System.ObjectDisposedException: Cannot process pending renders after the renderer has been disposed.
> Object name: 'Renderer'.
>    at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessPendingRender()
>    at Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToRenderQueue(Int32 componentId, RenderFragment renderFragment)
>    at Microsoft.AspNetCore.Components.ComponentBase.StateHasChanged()
>    at Microsoft.AspNetCore.Components.ComponentBase.Microsoft.AspNetCore.Components.IHandleEvent.HandleEventAsync(EventCallbackWorkItem callback, Object arg)
>    at Microsoft.AspNetCore.Components.EventCallback`1.InvokeAsync(TValue arg)
>    at BlazorStrap.BSTabGroupBase.<set_Selected>b__27_0()
>    at BlazorStrap.BSTabGroupBase.set_Selected(BSTabBase value)
>    at BlazorStrap.BSTabBase.Dispose(Boolean disposing)
>    at BlazorStrap.BSTabBase.Dispose()
>    at Microsoft.AspNetCore.Components.RenderTree.Renderer.Dispose(Boolean disposing)
> Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost: Error: Unhandled exception in circuit 'SzDr4Ttn-Jzl6vkAuVn8H5n71ohL4LK9VjKOkst8VrA'.
> 
> System.ObjectDisposedException: Cannot process pending renders after the renderer has been disposed.
> Object name: 'Renderer'.
>    at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessPendingRender()
>    at Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToRenderQueue(Int32 componentId, RenderFragment renderFragment)
>    at Microsoft.AspNetCore.Components.ComponentBase.StateHasChanged()
>    at Microsoft.AspNetCore.Components.ComponentBase.Microsoft.AspNetCore.Components.IHandleEvent.HandleEventAsync(EventCallbackWorkItem callback, Object arg)
>    at Microsoft.AspNetCore.Components.EventCallback`1.InvokeAsync(TValue arg)
>    at BlazorStrap.BSTabGroupBase.<set_Selected>b__27_0()
>    at BlazorStrap.BSTabGroupBase.set_Selected(BSTabBase value)
>    at BlazorStrap.BSTabBase.Dispose(Boolean disposing)
>    at BlazorStrap.BSTabBase.Dispose()
>    at Microsoft.AspNetCore.Components.RenderTree.Renderer.Dispose(Boolean disposing)
> Exception thrown: 'System.Net.Internals.SocketExceptionFactory.ExtendedSocketException' in System.Net.Sockets.dll
>

**Comment by chanan** [comment]
Can you supply a small repro?

**Comment by win32nipuh** [comment]
There is my draft page which generates the exception. I need to have 2 TabPages but now I removed the 2nd but even  for one TabPage it generates an exception:

```
@page "/customers"
@using BlazorStrap
@using S3Blazor.ColumnCollections
@using S3Blazor.Models
@using S3Blazor.Resources
@using S3Blazor.Services
@using S3Blazor.Pages
@using Microsoft.Extensions.Primitives
@using System.Globalization
@inject ICustomerService CustomerService
@inject NavigationManager NavigationManager
@inject IModalService Modal
@inject IS3LibraryService s3Svc


<h1>Customers</h1>

<p>
    Customers List
</p>
@if (true)//_task1.IsCompleted)// && _task2.IsCompleted)
{
    <BSTabGroup ShowEvent="@Show" HiddenEvent="@Hidden" HideEvent="@Hide" ShownEvent="@Shown">
        @*<BSTabList IsPills="true" IsList="true">*@
        <BSTabList>
            <BSTab>
                <BSTabLabel>File List</BSTabLabel>
                <BSTabContent>
                    <button @onclick="ShowModal" class="btn btn-primary">Upload new</button>
                    <div class="row">
                        <div style="margin:20px">
                            @if (_task.IsCompleted)
                            {
                                <GridComponent @ref="Customer2GridComponent" T="Customer2" Grid="@_grid" OnRowClicked="@CustomerItemDetails" CustomFilters="@_customFilters"></GridComponent>
                            }
                            else
                            {
                                <p><em>Loading...</em></p>
                            }
                        </div>
                        <div class="col-md-3">
                            <h4>
                                Customer details
                            </h4>
                            <CustomerItemInfo @ref="_customerItemInfo" ReturnUrl="Customers" OnRefreshMainGrid=@OnUpdateMainGrid GridState="@_grid.GetState()"></CustomerItemInfo>
                        </div>
                    </div>
                </BSTabContent>
            </BSTab>
            @*<BSTab>
                    <BSTabLabel>Upload file</BSTabLabel>
                    <BSTabContent>
                        <p>
                            Folder: <input type="text" @bind="FolderName" /><br />
                            Bucket: <input type="text" @bind="BucketName" /><br />
                        </p>
                        <button @onclick="CreateBucket">Create Bucket</button>

                        <button @onclick="BucketsList">List</button>
                        <h3>FileInput</h3>
                        <InputFile OnChange="HandleFileSelected" />
                        @if (file != null)
                        {
                            <p>Name: @file.Name</p>
                            <p>Size in bytes: @file.Size</p>
                            <p>File type: @file.Type</p>
                        }
                    </BSTabContent>
                </BSTab>*@
        </BSTabList>
        <BSTabSelectedContent />
    </BSTabGroup>
}
else
{
    <p><em>Loading...</em></p>
}

@code {
    private Task _task1;
     public GridComponent<Customer2> Customer2GridComponent;

    private CustomerItemInfo _customerItemInfo;

    private IQueryDictionary<Type> _customFilters = new QueryDictionary<Type>();

    [Parameter]
    public string Customer2GridState { get; set; }

    [Parameter]
    public string Customer2DetailGridState { get; set; }

    private CGrid<Customer2> _grid;
    private Task _task;

    protected override async Task OnParametersSetAsync()
    {
        var locale = CultureInfo.CurrentCulture;
        SharedResource.Culture = locale;

        Action<IGridColumnCollection<Customer2>> columns = c =>
        ColumnCollections2.Customer2ColumnsWithEdit(c, "editrows");

        var query = new QueryDictionary<StringValues>();
        //query.Add("grid-page", "2");

        var client = new GridClient<Customer2>(q => CustomerService.GetCustomer2GridRows(columns, q), query, false, "customersGrid", columns, locale)
          .Sortable()
          .Filterable()
          .ClearFiltersButton(true)
          .Selectable(true, true)
          .Groupable(true)
          .Searchable(true, false, false)
          .SetStriped(true)
          .ChangePageSize(true)
          .WithMultipleFilters()
          .WithGridItemsCount();

        _grid = client.Grid;

        //_customFilters.Add(ColumnCollections.CompanyNameFilter, typeof(CustomersFilterComponent<S3Library2>));
        // Set new items to grid
        _task = client.UpdateGrid();
        await _task;
    }

    protected void CustomerItemDetails(object item)
    {
        if (item.GetType() == typeof(Customer2))
        {
            _customerItemInfo.CustomerItem = (Customer2)item;
        }
        else
        {
            _customerItemInfo.CustomerItem = null;
        }
        _customerItemInfo.Refresh();
    }


    private void Show(BSTabEvent e)
    {
        Console.WriteLine($"Show   -> Activated: {e.Activated?.Id.ToString()} , Deactivated: {e.Deactivated?.Id.ToString()}");
    }
    private void Shown(BSTabEvent e)
    {
        Console.WriteLine($"Shown  -> Activated: {e.Activated?.Id.ToString()} , Deactivated: {e.Deactivated?.Id.ToString()}");
    }
    private void Hide(BSTabEvent e)
    {
        Console.WriteLine($"Hide   ->  Activated: {e.Activated?.Id.ToString()} , Deactivated: {e.Deactivated?.Id.ToString()}");
    }
    private void Hidden(BSTabEvent e)
    {
        Console.WriteLine($"Hidden -> Activated: {e.Activated?.Id.ToString()} , Deactivated: {e.Deactivated?.Id.ToString()}");
    }


    public void Refresh()
    {
        StateHasChanged();
    }

    private void OnUpdateMainGrid(int value)
    {
        //LastMultipleOfThree = value;
        Refresh2();
    }

    public void Refresh2()
    {
        //await
        Customer2GridComponent.UpdateGrid();
        StateHasChanged();
    }
}


```

**Comment by chanan** [comment]
Thanks for the Repro - I will take a look at it this evening

**Comment by win32nipuh** [comment]
I am not sure that the exception is in BlazorStrap, but its API calls are in the stack. Thats why I thought it can be connected with BlazorStrap. I understand you cannot run it, I will check if I can create a small app to reproduce

**Comment by jbomhold3** [comment]
Attempt the following change please  OnParametersSetAsync   to OnInitializedAsync   . OnParametersSetAsync happens anytime a parameter. The description states it should be within the render cycle. However, I ran into this many times with different projects. So as a general rule of thumb anything that renders does not live inside that life cycle.. Not sure if this has been fixed or not but try it out.   

Can you make a small repo with this issue on it going to guess its the grid comp and the tab not playing nice together.  So we can look into fixing this properly

**Comment by chanan** [comment]
@win32nipuh Did you try @jbomhold3 suggestion? Did it help?

**Comment by SteveHindmarsh** [comment]
I am also receiving this error, it occurs when the user clicks on the Tab before the page has fully rendered. My page with the Tabs is not using OnParametersSetAsync but a component placed in the default Tab ChildRenderFragment is awaiting some tasks in OnAfterRenderAsync, clicking while that is awaiting causes the Tab error? Please ask if you need more.
System.ObjectDisposedException: Cannot process pending renders after the renderer has been disposed.
Object name: 'Renderer'.
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessPendingRender()
   at Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer.ProcessPendingRender()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToRenderQueue(Int32 componentId, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.ComponentBase.StateHasChanged()
   at Microsoft.AspNetCore.Components.ComponentBase.Microsoft.AspNetCore.Components.IHandleEvent.HandleEventAsync(EventCallbackWorkItem callback, Object arg)
   at Microsoft.AspNetCore.Components.EventCallback`1.InvokeAsync(TValue arg)
   at BlazorStrap.BSTabGroupBase.<set_Selected>b__27_0()
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContextDispatcher.InvokeAsync(Func`1 workItem)
   at Microsoft.AspNetCore.Components.ComponentBase.InvokeAsync(Func`1 workItem)
   at BlazorStrap.BSTabGroupBase.set_Selected(BSTabBase value)
   at BlazorStrap.BSTabBase.Dispose(Boolean disposing)
   at BlazorStrap.BSTabBase.Dispose()
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.Dispose()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.Dispose(Boolean disposing)

**Comment by chanan** [comment]
Interesting. Any chance you can get a small reproduction?

Off hand I am not sure how to deal with this but haven’t check it carefully yet.
