### ISSUE TITLE
[Feature] Add Modal options IsBottomSheet, IsFullWidth and IsFullScreen.

### ISSUE THREAD

**Issue by arivera12** [chanan/BlazorStrap#279]
Hi,

It would be cool to add an option `IsBottomSheet `and display modal as a bottom sheet. 

I created a fiddle with the 2 classes/styles that needs to be added to display modal as a bottom sheet. 

This option is cool for mobile devices please consider it.

http://jsfiddle.net/wod0r5v1/

It would be good too to have an option `IsFullWidth` modal when ever is needed.

Also a `IsFullScreen` option would be very very nice also.

**Comment by chanan** [comment]
Would you like to submit a PR? :)

**Comment by arivera12** [comment]
I let a fiddle. Is it enough or not?

**Comment by arivera12** [comment]
I haven't forked this project.

**Comment by chanan** [comment]
Yes I can use the fiddle, just asking if you want to submit a PR for it.

**Comment by arivera12** [comment]
I need to fork it then PR?

**Comment by chanan** [comment]
That is correct

**Comment by arivera12** [comment]
Give me some minutes. brb

**Comment by arivera12** [comment]
@chanan I submitted a PR.

**Comment by chanan** [comment]
Merged! Thanks! Released as 1.3.1
