### ISSUE TITLE
Bootstrap CSS

### ISSUE THREAD

**Issue by grahamehorner** [chanan/BlazorStrap#28]
The boot strap css files shouldn't be required in the site project; but added as a resource to the BlazorStrap project and injected into the pages via the interop typescript.

**Comment by chanan** [comment]
@grahamehorner Interesting idea, but I want to make sure that if the developer wants to provide his own bootstrap we will use that instead. The reason is that the developer might want to use a different bootstrap theme, like one of the free ones here: https://bootswatch.com/ 

Can we do this in a way that will support the default bootstrap and allow it to be overridden?

**Comment by grahamehorner** [comment]
FYI 
https://zellwk.com/blog/css-values-in-js/

**Comment by grahamehorner** [comment]
I'd love to (in fact I've just started this ;) ) will do a PR for this soon

**Comment by chanan** [comment]
embedding CSS assets is possible now in Blazor. Will add the CSS in the next release with documentation that it can be used from the library or an external bootstrap css can be used (from a CDN for example or if a themed bootstrap is wanted)

Also should consider embedding bootswatch?
And if so, create a themeswitcher?

**Comment by jbomhold3** [comment]
I wouldn't put more then the core bootstrap stuff in. We can always add a Blazorstrap.Extensions project for all the extra goodies. I have a few in mind that would fit that project and not the core

**Comment by chanan** [comment]
What I think would be nice to have (and yes can be an extra project) would be something like this in StartUp.cs (all optional):

```
services.AddBootstrapCSS()  //Writes a link to the head to latest version bootstrap on the CDN

services.AddBootStrapCSS("some version number") //Same as above but a specific bootstrap version

services.AddBootSwatchCSS("some named bootswatch theme") //Adds latest named bootswatch theme 

services.AddBootSwatchCSS("some named bootswatch theme", "some version number")
```

That way, users dont have to include anything in the head and dont need to ship the bootstrap CSS anymore.

Lastly, once we have that we can provide a way to switch themes (component and API) something along the lines of: https://react-bootswatch.firebaseapp.com/

**Comment by jbomhold3** [comment]
I get you now. I would keep this in core then.

**Comment by chanan** [comment]
Going to submit a PR for this tonight or tomorrow.

**Comment by chanan** [comment]
PR #111 addresses this. Will go out in 1.0.0-preview6-21
