### ISSUE TITLE
Modal Source code example is throwing 404.

### ISSUE THREAD

**Issue by arivera12** [chanan/BlazorStrap#281]
Something went wrong on site deployment. 

Please check whats is wrong with the url paths. 

Did I miss something? on my machine works perfectly.
![image](https://user-images.githubusercontent.com/5600102/78189560-3f7b5e00-7440-11ea-8a02-c69b7a1bd2fc.png)

**Comment by chanan** [comment]
Sorry, thanks for catching this, forgot to upload _contnet! should be there in a sec

**Comment by arivera12** [comment]
Working now!
![image](https://user-images.githubusercontent.com/5600102/78190058-3c34a200-7441-11ea-871b-344731084605.png)
