### ISSUE TITLE
BSBasicInput Issue

### ISSUE THREAD

**Issue by gaoa1991** [chanan/BlazorStrap#285]
I'm trying to create some auto save on top of the existing EditForm and BSBasicInput Components. For some reason the BSBasicInput is thowing this error

System.ArgumentException: Delegate to an instance method cannot have null 'this'.
   at System.MulticastDelegate.ThrowNullThisInDelegateToInstance()
   at System.MulticastDelegate.CtorClosed(Object target, IntPtr methodPtr)

When I remote the "T" param and just use the @bind-Value (No catching of the change event) it works fine,

@using Microsoft.AspNetCore.Components;
@using System.Threading.Tasks;

<BSBasicInput
         T=string
         InputType="InputType"
         Value="Value"
         IsReadonly="IsReadonly"
         ChildContent="ChildContent"
         ValueChanged="@(async (item) => await AutoSaveValueChangedSync(item))"/>

@code {
    [CascadingParameter]
    protected AutoSaveEditForm autoSaveEditForm { get; set; }

    [Parameter] public InputType InputType { get; set; } = InputType.Text;
    [Parameter] public string Value { get; set; }
    [Parameter] public EventCallback<string> ValueChanged { get; set; }
    [Parameter] public bool IsReadonly { get; set; }

    // [Parameter] public string Class { get; set; }
    [Parameter] public RenderFragment ChildContent { get; set; }

        protected override void OnParametersSet()
        {
            base.OnParametersSet();
        }

    private async Task AutoSaveValueChangedSync(string item)
    {
        Value = item;
        await autoSaveEditForm.ContextChanged.InvokeAsync(null);
    }
}

**Comment by jbomhold3** [comment]
BSBasicInput should only be used if you do not have a editcontext...    BSInput can be used with EditForm you will have a lot more luck this way.
