### ISSUE TITLE
Carousel Issues

### ISSUE THREAD

**Issue by MasterSkriptor** [chanan/BlazorStrap#289]
I would like to eventually be able to use custom svg files in the carousel. Currently using a BSCarouselItem forces you to use the img tag.  Prehaps you can make a feature that allows you to use an ItemTemplate for the BSCarousel component.

Forgive me if I am asking too much. I don't mind making a pull request of my own if it would help.

**Comment by chanan** [comment]
Sounds good. We can add it.

If you want to submit a PR then it will be even faster
