### ISSUE TITLE
Popover jumps when opening

### ISSUE THREAD

**Issue by TehGM** [chanan/BlazorStrap#294]
I have a very basic input component, that needs to show validation errors as user types. I want the errors to be displayed in a Popover when the text input is focused. To do this, I have a fairly simple piece of code:
```razor
<input id="@_id.ToString()" class="form-control" @oninput="ValueChanged" @bind="Value" placeholder="@Placeholder" type="@(IsPassword ? "password" : "text")" @onfocus="OnFocus" @onblur="OnBlur" />

@if (ValidationResults?.Any() == true)
{
    <BlazorStrap.BSPopover IsOpen="_showTooltip" Placement="BlazorStrap.Placement.Right" Target="@_id.ToString()">
        <BlazorStrap.BSPopoverBody>
            @foreach (InputValidationResult validationResult in ValidationResults)
            {
                <div class="text-@(validationResult.IsError ? "error" : "success") form-group">
                    <span class="oi oi-@(validationResult.IsError ? "x" : "check")"></span>
                    @validationResult.Text
                </div>
            }
        </BlazorStrap.BSPopoverBody>
    </BlazorStrap.BSPopover>
}
...
private bool _showTooltip;

private void OnFocus()
{
    _showTooltip = true;
}

private void OnBlur()
{
    _showTooltip = false;
}
```

The popover does appear when the input is focused, and disappears when input loses focus. However, when it's being opened, it briefly appears in default place, before moving to the right as intended. Unfortunately, this is very noticeable (it happens more often than on the attached gif, gif lost a few frames due to the compression).
![GIF2](https://user-images.githubusercontent.com/9112561/79603568-85911c80-80e4-11ea-9d53-2341c596ba41.gif)

Note: not sure if it matters, but it's Blazor Server-side.

**Comment by chanan** [comment]
Thanks for the repro. I will take a look at what we can do about this. 

Either see if the position changes after we call popover and if that’s not the case see if we can hide it till it’s in the correct position.

**Comment by xXBuilderBXx** [comment]
You can temp fix this by adding this css which will show the popover outside of the screen first and then go to the correct position.
.popover {
        left: -300px;
    }
