### ISSUE TITLE
Border Line On Model Window when click 

### ISSUE THREAD

**Issue by aqkhana2002** [chanan/BlazorStrap#296]
![image](https://user-images.githubusercontent.com/5283983/79705617-aaaaa880-82f9-11ea-87b0-8d1fcbc59329.png)

how can i get rid of this border line , this line appear when model window is activated and you click any where in white area.

AQEEL

**Comment by jbomhold3** [comment]
try including <link rel="stylesheet" href="_content/BlazorStrap/css/cromefix.css">

**Comment by TomJD** [comment]
I can confirm the "chromefix.css" fixes it
