### ISSUE TITLE
Carousel sliding not working on click (any non-first click)

### ISSUE THREAD

**Issue by digrizzz** [chanan/BlazorStrap#297]
When clicking BSCarouselControl not first time carousel sliding doesn't work. To reproduce it:
click 'Next slide' button here https://blazorstrap.io/carousels two or more times

**Comment by chanan** [comment]
Hi @digrizzz I cannot reproduce this. When I click any Carousel on that page any number of times it always advances to the next slide. What browser are you using? I tried it on the new Edge and on Chrome.

**Comment by digrizzz** [comment]
Hi @chanan i'm using Chrome 81.0.4044.113 on Windows. After receiving your comment, i've tried this on Edge 42.17134.1098.0 - everything works as expected. Any ideas why this might happen for Chrome? (my version looks like not latest one but not too old)

**Comment by chanan** [comment]
No idea yet but I will try it again on chrome today and get back to you

**Comment by jbomhold3** [comment]
I can't reproduce it Version 81.0.4044.122 (Official Build) (64-bit)

**Comment by digrizzz** [comment]
@chanan  I've attached video report. Possibly this could help you to debug
https://github.com/digrizzz/filestorage/raw/master/bandicam%202020-04-27%2013-55-19-396.mp4

**Comment by chanan** [comment]
@digrizzz Is this happening on WASM or server side? (and if WASM are you on latest preview version)?

**Comment by masoudafar** [comment]
hi plz update https://blazorstrap.io/

> <BSCarouselIndicators NumberOfItems="@items.Count" ActiveIndexChangedEvent="@indexChanged"> ??????????????
what is **@indexChanged**?
where is it؟
**BSCarouselIndicators** not working
