### ISSUE TITLE
Intermittently unresponsive BSButton in component

### ISSUE THREAD

**Issue by jaldinger** [chanan/BlazorStrap#298]
I have the following strange issue. I have created a component with detail button inside each table row like this:
`<BSButton Size="Size.Small" Color="Color.Info"><span class="oi oi-chevron-right" @onclick="(() => SelectReimbursementRequest(e))"></span></BSButton>`
The code is quite simply an EventCallback:
```
[Parameter]
public EventCallback<ReimbursementRequestModel> OnSelectReimbursementRequest { get; set; }

private async Task SelectReimbursementRequest(ReimbursementRequestModel r)
{
    await OnSelectReimbursementRequest.InvokeAsync(r);
}
```
In the page itself, I insert the component like this:
```
<ReimbursementRequestTable Title="Solicitudes de reembolso en proceso"
                            pettyCashAccount="_pettyCashAccount"
                            reimbursementRequests="_reimbursementRequests"
                            OnSelectReimbursementRequest="@SelectReimbursementRequest">
</ReimbursementRequestTable>
```
And then show a detail form like this:
```
private void SelectReimbursementRequest(ReimbursementRequestModel r)
{
    _reimbursementRequestModel = r;
    _visibleForm = VisibleForm.PrintReimbursementRequest;
    this.StateHasChanged();
}
```
However, the button is now behaving unreliably, in the sense that sometimes the click event occurs on the 1st click, sometimes it takes 2 or 3 clicks, and sometimes up to 10 clicks until the action executes. I've set breakpoints, but it really simply just doesn't seem to fire at all, no exceptions are happening anywhere as far as I can see. Here's a short clip demonstrating the situation: 
https://youtu.be/izx6M6hYEYg

Is this something that may be related to the BlazorStrap? Or to the way I am setting this up? Or maybe something Blazor-generic...? Any suggestions on where the problem could be?

Thanks in advance,

Joerg.

**Comment by jbomhold3** [comment]
This has nothing to do with the button... your binding the span so you have to click exactly on the span content remove the onclick from the span and move it to the button

**Comment by jaldinger** [comment]
You are absolutely right. It seems I have accidentally added the handler to the wrong item when I refactored the table into the other component. Thank you for catching this!
