### ISSUE TITLE
Modal closes on all sessions when escape is pressed

### ISSUE THREAD

**Issue by timbze** [chanan/BlazorStrap#299]
Using latest BlazorStrap in nuget.

When IgnoreEscape is not added to BSModal, pressing escape when modal is open causes the same modal in all other sessions (if open) to close as well.

Calling modal.Hide() works and does not close other session modals.

**Comment by chanan** [comment]
What do you mean by all open sessions? Do you mean browser tabs?

**Comment by timbze** [comment]
Yes, even on other devices.

**Comment by chanan** [comment]
Wow.. ok so that's weird. Is this on a SSB or CSB?

**Comment by timbze** [comment]
Sorry I don't recognize those letters

**Comment by timbze** [comment]
I'm checking on blazorstrap.io and it's not happening there as far as I can find out.

Mine is ServerPrerendered mode, not sure if that makes a difference

**Comment by chanan** [comment]
That would make sense, BlazorStrap.io is client side - it cant interact with the any other device. Server side on the other hand can.

**Comment by timbze** [comment]
It is very weird, cause the modal.Hide() works exactly as expected, but once escape is enabled and pressing it, it closes every single one of that same modal that is open elsewhere. I couldn't believe my eyes :)

**Comment by chanan** [comment]
Kind of cool feature :)

My first few guesses about what it can be didn't pan out yet. Still looking.

**Comment by chanan** [comment]
Ok, I think I found the issue (can't run it right this second, still doing my day job), I beleive this issue is these lines in https://github.com/chanan/BlazorStrap/blob/master/src/BlazorStrap/Util/BlazorStrapInterop.cs#L10-L13:

```
public static Func<Task> OnEscapeEvent { get; set; }
public static Func<string, Task> OnAnimationEndEvent { get; set; }
public static Func<string, string, Task> OnAddClassEvent { get; set; }
```

In the case of the modal, its the first line. Those variables should not be `static` because in server side, they will be shared by **ALL** users on the server as @timbze is seeing.

**Comment by timbze** [comment]
I was just going to report another one that might be related.

When I have one modal open, and then open another modal from it, after closing second modal, the first modal cannot scroll but the main page behind it does scroll.

**Comment by chanan** [comment]
I will try that out when I change those 3 vars. I dont think I can do that tonight though, we have a code release tonight at work, sorry.

**Comment by timbze** [comment]
No problem! I played around with it a bit myself, but I guess there will need to be some work-around because as it is, JS is calling net [JSInvokable] method on Escape press, and that way the method has to be static.

Just my thoughts, but haven't done much in JS myself. Either have some GUID attached to each modal so we know which one to close, or some total other work-around probably...
