### ISSUE TITLE
BlazorStrap: Resize modals using window corners and move them around the screen

### ISSUE THREAD

**Issue by tobbi** [chanan/BlazorStrap#304]
Does BlazorStrap support resizing / moving around windows? So far I haven't found a way to achieve that.

**Comment by chanan** [comment]
We (mostly) only support what is in bootstrap "proper". If that is something you can do with base bootstrap and we missed it let us.

If it is not, and you are suggestion a new feature that you can point us to a website that describes that feature (and has the CSS and JS) - we can consider adding it. Also we always are happy to accept PRs :)
