### ISSUE TITLE
Popover placement on mobile bad when set to Placement.Right

### ISSUE THREAD

**Issue by timbze** [chanan/BlazorStrap#306]
This is what it shows on mobile when set to Placement.Right. Don't know what would be the right way to handle this, but I would have preferred Placement.Right for computer and Placement.Auto for mobile. (I'm just using Placement.Auto since that will be ok for now)

![image](https://user-images.githubusercontent.com/35117769/80593377-592ba900-89de-11ea-9df5-504259eff279.png)

**Comment by chanan** [comment]
Detecting the viewport width in JavaScript is easy to do, the question is what should we do in the case. I will check the official bootstrap site on mobile and see if they did anything. Probably not though. So any suggestion are welcome

**Comment by timbze** [comment]
I think it should switch to Auto when it's too narrow so that it would be either top of bottom depending on where it's at on the screen.

I don't know JS too well and don't know how it handles viewport width, but just need to keep this in mind, the browser can be open at different widths, and in my case show or hide the side bar, so that makes a difference too: (pic 3 and 4 browser are lesser width than 1 and 2)
![image](https://user-images.githubusercontent.com/35117769/80596799-2dabbd00-89e4-11ea-9317-97f3b30937c4.png)
![image](https://user-images.githubusercontent.com/35117769/80596744-166ccf80-89e4-11ea-944f-43260f83ff60.png)
![image](https://user-images.githubusercontent.com/35117769/80596948-621f7900-89e4-11ea-857f-b9859c5b44c9.png)
![image](https://user-images.githubusercontent.com/35117769/80596985-6f3c6800-89e4-11ea-9952-f50b93b81af4.png)

**Comment by chanan** [comment]
@jbomhold3 Any objection to changing the Placement automatically for the user to Auto when the screen is mobile sized? I hate to change stuff for the user, but on the other hand, adding a param ChangeIfMobile="true" doesnt sit with me well either - mainly because either everyone will forget to set it, or they will set it all the time to true anyway. Thoughts?
