### ISSUE TITLE
Uncaught ReferenceError: Popper is not defined

### ISSUE THREAD

**Issue by dbowser** [chanan/BlazorStrap#307]
This worked for me before but after installing the latest it is not working.
When I mouse over a ToolTip I have defined I get:

Uncaught ReferenceError: Popper is not defined
    at showPopper (blazorStrap.js:135)
    at HTMLInputElement.mouseoverHandler (blazorStrap.js:71)

**Comment by chanan** [comment]
Do you have the script included in your page and do you have AddBootStrapCss added to your services?

**Comment by dbowser** [comment]
I have added:     <script src="_content/BlazorStrap/blazorStrap.js"></script> to my index.html head section and have added  _ = builder.Services.AddBootstrapCss(); in the main of my program.cs
I also added '@inject IBootstrapCss BootstrapCss' 
and added ' await BootstrapCss.SetBootstrapCss("4.3.1"); ' to OnInitializedAsync() of MainLayout.rajor

**Comment by dbowser** [comment]
It is not working. I get the above error. 
What should I send? Should I create the template project and see if I get the same error and send that or ?

**Comment by chanan** [comment]
Code snippet is fine. Or if you want to link to a repo it’s a small project that works too

**Comment by dbowser** [comment]
It is a big project and isn't in a repo where I could do that unfortunately 

The only snippit I can think to send is:

                            <td><input id="partNumFilterInp" @bind-Value="@PartNumFilter" @bind-Value:event="oninput" type="text" /></td>

<BSTooltip Target="partNumFilterInp" Placement="Placement.Right">@((MarkupString)FilterStringText)</BSTooltip>

Is there anything else that would be interesting to send?

**Comment by chanan** [comment]
The error isn’t occurring on a tooltip?

**Comment by dbowser** [comment]
Sorry, it isn't showing what I am pasting

**Comment by dbowser** [comment]
Check the .txt file I added

**Comment by dbowser** [comment]
That example is a little elaborate because I am using formatted html but other cases with simple text do the same thing.

**Comment by dbowser** [comment]
I have to run out. Will be back in a bit.

**Comment by dbowser** [comment]
Are you able to reproduce it?

**Comment by chanan** [comment]
@dbowser No, I haven't been able to reproduce this issue. I tried it both in server side and client side projects (WASM)

**Comment by chanan** [comment]
Sure, no problem, always glad to help out. I will try to do this shortly.

**Comment by dbowser** [comment]
OK, I downloaded the latest VS 2019, created the template Blazor WebAssembly app added BlazorStrap and tested and get the same error. 
My test project is here (minus the obj and bin folders so it isn't too big):

[ECIS_Web.zip](https://github.com/chanan/BlazorStrap/files/4565828/ECIS_Web.zip)

**Comment by chanan** [comment]
Thanks! Trying it now

**Comment by chanan** [comment]
I am seeing the tooltip Both when I run it as server or running the client directly. Are you not seeing the tooltip?

![image](https://user-images.githubusercontent.com/472554/80844739-a8cbc980-8bc4-11ea-88f4-a30c4257d43e.png)

**Comment by dbowser** [comment]
Yes I see the tooltip. 
However, in the console I see the error message every time I mouse over...

**Comment by chanan** [comment]
Ok, got it now! Looking into it

**Comment by chanan** [comment]
Add this to your `index.html`: `<script src="_content/BlazorStrap/popper.min.js"></script>`

1. We will update out documentation to point that out.
2. I have no clue why it worked even without that line yet printed an error to the log

**Comment by dbowser** [comment]
Ah OK thanks!
