### ISSUE TITLE
Freaky Popover behavior

### ISSUE THREAD

**Issue by AnaStepic** [chanan/BlazorStrap#309]
Clicks seem to activate wrong popovers and multiple wrong popovers at that.

Screen capture from https://blazorstrap.io/popovers
![popovers](https://user-images.githubusercontent.com/7997858/80760613-732dce80-8b39-11ea-8972-65aff7133303.gif)

I've also tried it in my own app. The first time a popover appears, everything seems fine. But the next popover to appear will cause the former popover to also pop up. Very bizarre.

I've tried multiple browsers and the same thing happens so it isn't a browser issue.

**Comment by chanan** [comment]
Freaky for sure! I will take a look at it tonight with the other popover issue.

**Comment by chanan** [comment]
I always click outside the popper to close it, that's why I never noticed this behavior. 

Closed, will be in the next release
