### ISSUE TITLE
I hate CSS...

### ISSUE THREAD

**Issue by richbryant** [chanan/BlazorStrap#31]
I'll post without actual hope but hey, you never know.

I am making a demo application using a whole lot of Blazor and associated bits including Fluxor, Db and especially BlazorStrap.  I have a licence for a template that hgas bits of what I want to do but I'm finding it impossible to replicate them in BlazorStrap.

Here's the image of the toolbar I am wrestling with
![toolbar_view](https://user-images.githubusercontent.com/2277883/49748460-9c786100-fc9d-11e8-83da-77950e68e8d3.PNG)

and here's the source of that particular bit.

![toolbar](https://user-images.githubusercontent.com/2277883/49748484-b023c780-fc9d-11e8-8884-968890e3ac4c.PNG)

Does anyone have any advice?  I can do the code, that's fine.  I've written a dynamic clanedar component - that one does BlazorStrap - but I can't seem to manage styling.  Drives me insane.

**Comment by chanan** [comment]
I will give it a shot later today, did you start converting to BlazorStrap components yet?

**Comment by richbryant** [comment]
Yeah, I did this bit but the columns within the toolbar are not right and god only knows how one gets a magnifying glass into a BlazoreStrap textbow.
```

<Container IsFluid="true">
    <Row>
        <BlazorCol LG="1" XS="3" SM="2" MD="2">
            <Image Src="img/logo.jpg" alt="logo"/>
        </BlazorCol>
        <BlazorCol LG="3" XS="9" SM="5" MD="3" class="pull-left">
            <Navbar IsExpand="true" IsDark="false" Color="Color.Light">
                <NavbarBrand Href="#">Navbar</NavbarBrand>
                <NavbarToggler onclick="@onclick" />
                <Collapse isOpen="@IsOpen" IsNavbar="true">
                    <BlazorNav IsList="true" Class="mr-auto" IsNavbar="true">
                        <NavItem IsDropdown="true">
                            <DropdownToggle onclick="@onclick2" IsOpen="@IsOpen2" Color="Color.Light">Dropdown link</DropdownToggle>
                            <DropdownMenu IsOpen="@IsOpen2">
                                <DropdownItem>Action</DropdownItem>
                                <DropdownItem>Another Action</DropdownItem>
                                <DropdownItem>Yet Another Action</DropdownItem>
                            </DropdownMenu>
                        </NavItem>

                    </BlazorNav>
                </Collapse>
            </Navbar>
        </BlazorCol>
        <BlazorCol LG="4" MD="3" class="pull-right hidden-xs hidden-sm selecttopic">
            <BlazorForm IsInline="true" Class="my-2 my-lg-0">
                <BlazorInput InputType="InputType.Search" PlaceHolder="Search" Class="mr-sm-2" />
                <BlazorButton IsOutline="true" Color="Color.Success" ButtonType="ButtonType.Submit" Class="my-2 my-sm-0">Search</BlazorButton>
            </BlazorForm>
        </BlazorCol>
    </Row>
</Container>
```

**Comment by chanan** [comment]
Ok, thanks, I will use that as a starting point.

**Comment by richbryant** [comment]
No, all the thanks go to you.  I'm genuinely stuck.

**Comment by chanan** [comment]
Can you paste the original CSS as text as well please? I would like to compare the two.

**Comment by richbryant** [comment]
here's the custom CSS - 

```
.headernav {
    height: 70px;
    border-bottom: 1px solid #c9cccd;
}


.content {
    background-color: #ecf0f1;
    border-top: solid 1px #e0e4e5;
}

.selecttopic {
    line-height: 69px;
    font-family: 'Open Sans Semibold', sans-serif;
    font-size: 16px;
    color: #363838;
}

.selecttopic select {
    border: none;
}

.selecttopic .dropdown-menu {
    margin-top: -20px;
}

.headernav .search {
    color: #363838;
    font-size: 14px;
    font-family: 'Open Sans Light', sans-serif;
    margin-top: 16px;
    height: 38px
}

.headernav .search  .wrap {
    background-color: #f3f5f9;
    border-radius: 3px;
}

.headernav .search .txt {
    width: 85%;
}

.headernav .search input {
    border: none;
    box-shadow: none;
    background-color: #f3f5f9;
    color: #363838;
    font-size: 14px;
    padding: 8px 19px;
    height: 38px;

}


.headernav .search button {
    border: solid 1px #697683;
    box-shadow: none;
    background-color: #697683;
    color: #ffffff;
    font-size: 18px;
}

/*--- Avatar ---*/
.avt {
    margin-top: 16px;
    height: 38px;
}

.avt button {
    height: 38px;
    border: none;
    box-shadow: none;
    color: #ffffff;
    font-size: 14px;
    font-family: 'Open Sans Bold', sans-serif;
    padding-left: 30px;
    padding-right: 30px;
    background-color: #1abc9c;
}

.avt .btn-primary:hover, 
.avt .btn-primary:focus, 
.avt .btn-primary:active, 
.avt .btn-primary.active{
    background-color: #1abc9c;


    border: none;
    box-shadow: none;

}

.env {
    font-size: 18px;
    color:#cfd5d7;
    line-height: 38px;
    padding: 0 20px;
}

.avatar {
    position: relative;
}

.avatar img {
    border-radius: 50%;
}

.avatar .status {
    position: absolute;
    right: 0;
    top: 0;
    width: 12px;
    height: 12px;
    line-height: 12px;
    border-radius: 50%;
    border: solid 2px #ffffff;
}

.dropdown.avatar .status {
    right: 14px;
}
.caretl {
    color:#363838;
    font-size: 14px;
    line-height: 38px;
    padding: 0 15px;
}


.avatar .green {
    background-color: #80d3ab;
}

.avatar .red {
    background-color: #f27777;
}

.avatar .yellow {
    background-color: #ecd346;
}
```

**Comment by richbryant** [comment]
I'll try this as soon as my real work is over - thank you very much!

**Comment by chanan** [comment]
@richbryant Thanks for the CSS, I will give it a shot today. One more thing to note other than what I already mentioned, is that it doesnt actually use nav bars, its a custom implementation, so what you will get in BlazorStrap won't be pretty...

**Comment by chanan** [comment]
Ok, I think I took it as far as I can. It still doesnt look right, but the major reason for that is that I think the CSS you have is based on Bootstrap3, so I am not sure how to get it to look right in bootstrap4. The second sample is in /sample/navbars2

Things to note:
1. I added your css file to wwwroot/css/issue31.css
2. The two images I am using are a snip of your big image above, if you used the real assets that part will look better.
3. As I pointed out, your page is from bootstrap3, you can tell because it uses pull-left/right, which has been removed in bootstrap4. I am not sure that is the cause of the some of the issues, but maybe
4. I didnt look at it with font awesome css, so a few images aren't showing like the envelope. You will want to get the font awesome css and put a link to it in your index.html

I think with a bit more work, it can be made to work using navbar2.cshtml as a basis.

**Comment by richbryant** [comment]
It's looking very, very close.  Thanks for this, I'll do some more work on it.  You've been a huge help.
