### ISSUE TITLE
Tooltip arrow pointing in the wrong direction

### ISSUE THREAD

**Issue by AnaStepic** [chanan/BlazorStrap#311]
When you create a tooltip and set its preferred placement, if such placement cannot be achieved due to available space limitations, the tooltip will be put automatically where it can. However, the arrow of the tooltip will still be pointing in the direction of preferred placement.

In the example below I set the preferred placement to Top but the element that activates the tooltip is too close to the top of the page so the tooltip can't fit above it:
![Tooltip](https://user-images.githubusercontent.com/7997858/80831084-71701380-8bea-11ea-97ed-36e29c350279.gif)

The same thing happens with all other preferred placements that have an arrow in case there isn't enough available space. 

P.S. When is the next NuGet release so I can update my project with the recently applied fixes? :)

**Comment by chanan** [comment]
Weird, I havent seen this. Is there anything special about the way you have the tool tip?

We are going to release another preview this weekend

**Comment by AnaStepic** [comment]
The same thing happens on https://blazorstrap.io/popovers site. If you want to reproduce it on there, just change the window size to be small enough.

**Comment by chanan** [comment]
oh! Is this the same issue: #306 ?

**Comment by AnaStepic** [comment]
Yeah. It isn't a mobile-only issue though. It happens on desktop too if the popup target is too close to the sides of the screen.

**Comment by chanan** [comment]
Yes, agreed. I think its the same issue/solution - to change the placement to Auto (Does that fix it for you)? I want to talk to @jbomhold3 before we change the user's selection when the screen is small

**Comment by AnaStepic** [comment]
I'm not sure whether what you are thinking is the same as what I'm thinking but the solution that I would like is that if the preferred tooltip placement can't be done, they are repositioned automatically like how they would be positioned through Placement.Auto.

**Comment by chanan** [comment]
Yep. That’s what we thought in that other issue. Do you mind if we close this one and track only the other one?

**Comment by AnaStepic** [comment]
Don't mind.
