### ISSUE TITLE
Avoid is-valid applied to BSInput

### ISSUE THREAD

**Issue by jaldinger** [chanan/BlazorStrap#312]
Posting as an issue to better keep track of this, as mentioned on gitter.

I have a simple BSInput field
`<BSInput Id="Comments" InputType="InputType.Text" @bind-Value="_expenseModel.Comments" ValidateOnChange="false"></BSInput>`
that applies the "is-valid" class when I leave the field, even if it's empty. I want to apply my own logic to the validation (which includes blocking empty values). I am not using DataAnnotationsValidator, but rather handling my own OnSubmit method to mark fields as invalid if they are. According to @jbomhold3 an if needs to be applied to this line to fix this issue:

https://github.com/chanan/BlazorStrap/blob/37aaa66e565da1f30a44ec0f094364acfa0e977e/src/BlazorStrap/Components/Forms/BSInput.cs#L166

Since I don't know the correct condition and I'm not familiar with PRs at all, I don't fix it myself.

Thanks,

Joerg

**Comment by jbomhold3** [comment]
This was fixed

**Comment by jaldinger** [comment]
Excellent, Thanks!
