### ISSUE TITLE
Animation in Collapse never ends

### ISSUE THREAD

**Issue by ASemenov1977** [chanan/BlazorStrap#314]
Animation in Collapse never ends,  because the @ontransitionend event is not called.
Any idea, what is wrong?

**Comment by jbomhold3** [comment]
Was a bug in last versions  js make sure you reload without cache to get the update

**Comment by ASemenov1977** [comment]
Thank you, it helped. Now works well

**Comment by chanan** [comment]
Closing as this seems resolved
