### ISSUE TITLE
Little suggestion according to Your documentation with Razor/Blazor "at" symbols.

### ISSUE THREAD

**Issue by kamilk91** [chanan/BlazorStrap#315]
Hi, to make your docs more Blazorized, and C#-ed i suggest you to change

```
        <td>@fat</td>
        <td>@twitter</td>
```

to 

```
        <td>@@fat</td>
        <td>@@twitter</td>
```

> Start with @ symbol to write server side C# or VB code with Html code. For example, write @Variable_Name to display a value of a server side variable. For example, DateTime.Now returns a current date and time. So, write @DateTime.Now to display current datetime as shown below. A single line expression does not require a semicolon at the end of the expression.

[Razor syntax is described in aspnetcore official docs](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/razor?view=aspnetcore-3.1)

Great job anyway. :)

**Comment by chanan** [comment]
Will update in the upcoming release
