### ISSUE TITLE
StopPropagation on controls?

### ISSUE THREAD

**Issue by markgould** [chanan/BlazorStrap#320]
I have buttons inside a collapsible container, which expands/collapses on click. I don't want this to happen when clicking on buttons inside the container though.

I'm able to do this with standard inputs by doing the following:

`<button @onclick="whatever" @onclick:stopPropagation />`

Is there anyway to pass this to the BlazorStrap components?

**Comment by chanan** [comment]
BlazorStrap tags propergate extra attributes down to their "base tag". So a BSButton should propagate "style" (for example) down to button.

Two things: 

1. These are special attributes, they should work like any other attribute, but I haven't tried it.
2. If you mean down from a different tag than a button, that won't work (out of the box)

If you tried it already and its not work, send a code snippet and we will look into it

**Comment by markgould** [comment]
Thanks for the quick reply!

I may just be doing it wrong (new to Blazor) but the examples for BSButton show using OnClick instead of @onclick

I've tried it both of these two ways:

`<BSButton OnClick="(() => SomeMethod(context))" @onclick:stopPropagation/>`

``<BSButton @onclick="(() => SomeMethod(context))" @onclick:stopPropagation/>``

I get this error:

>       Error RZ10010: The component parameter 'OnClick' is used two or more times for this component. Parameters must be unique (case-insensitive). The component parameter 'OnClick' is generated by the '@onclick:stopPropagation' directive attribute. (166, 48)

I will note that I do not have this problem with the BSDropdown - I'm able to use it like this:

`<BSDropdown @onclick:stopPropagation>`

And then I can use @onclick on the BSDropdownItems just fine

**Comment by chanan** [comment]
That seems to be an error from Blazor itself.

Like it says it sees to @onclick - BSDropdown doesnt have an onclick so it's not giving you that error.

It's also possible that the mechnisim we use to transfer the attribute is messing up and trafsering it as onclick="stopPropgration" or something foolish like that.

I will try to take a look at it today, hopefully it is an easy fix.

**Comment by markgould** [comment]
I think I see the issue.

In BSButton you have an OnClick event: https://github.com/chanan/BlazorStrap/blob/master/src/BlazorStrap/Components/Forms/BSButton.razor

In BSDropdownItem it's OnClickEvent: https://github.com/chanan/BlazorStrap/blob/master/src/BlazorStrap/Components/Dropdown/BSDropdownItem.razor

Having it called OnClick seems to be conflicting.

**Comment by chanan** [comment]
I don't think that should matter, but we will take a look for sure.

**Comment by jbomhold3** [comment]
@onclick:stopPropagation does not seem to count as an extra attribute I have run into the same issue, Will look into seeing how it can be fixed without changing a ton of code up.

**Comment by markgould** [comment]
Yeah - one workaround I believe is just to put a div around the button and put the  @onclick:stopPropagation on the div. Not pretty but it should work.

**Comment by jbomhold3** [comment]
https://github.com/dotnet/aspnetcore/issues/18460#issuecomment-577175682  
So we are going to have to add 2 bools to controls with a click event
OnClickStopPropagation 
OnClickPreventDefault
then in the link or button
@onclick:preventDefault="OnClickPreventDefault"
@onclick:stopPropagation="OnClickStopPropagation"

**Comment by chanan** [comment]
Agreed

**Comment by chanan** [comment]
PaginationLink has a similar problem. If you remove the href and just use onclick it loses its formatting. If you leave Href="#" you need the PreventDefault

**Comment by MasterSkriptor** [comment]
There may be other components that suffer from this issue, if so please let me know and I'll take care of it.
