### ISSUE TITLE
Feature Request: <BSToast AutoHide=true Delay=500>

### ISSUE THREAD

**Issue by Tiberriver256** [chanan/BlazorStrap#321]
Love the library. Just a thought that it would be cool to have the Bootstrap 4 toast autohide functionality built in.

**Comment by Tiberriver256** [comment]
Looks like that PR was only for BSAlert, unless I'm missing something @jbomhold3

**Comment by jbomhold3** [comment]
No, you not got a little close happy it seams. This post was referenced in the pr.
