### ISSUE TITLE
BSModel Clicking shade makes model stuck open

### ISSUE THREAD

**Issue by jbomhold3** [chanan/BlazorStrap#324]
BSModel Clicking shade makes model stuck open

**Comment by chanan** [comment]
@jbomhold3 Is this with the latest code? I changed something regarding that recently in the javascript.

**Comment by jbomhold3** [comment]
Haven't noticed happening now. I have noticed sometimes the class does not get removed from the body locking up the scroll bar

**Comment by chanan** [comment]
Yes that is what I fixed
