### ISSUE TITLE
BSDataTable and DataTables library error

### ISSUE THREAD

**Issue by bdovaz** [chanan/BlazorStrap#334]
I suppose you know the following library: https://datatables.net/

The problem I'm having is that when I don't have data I have no way not to define a "\<tr>" attribute since in the following code it is hardcoded:

https://github.com/chanan/BlazorStrap/blob/master/src/BlazorStrap.Extensions.BSDataTable/Components/BSDataTable/BSDataTable.razor#L25

DataTables library doesn't expectr this so it crashes.

In the following example you can see the error it gives in the console. Remove inside "\<tbody>" the "\<td>" and you will see the errors:

Uncaught TypeError: Cannot set property '_DT_CellIndex' of undefined

https://codepen.io/bdovaz/pen/XWmQMEa

**Comment by jbomhold3** [comment]
Fixed in BSDataTable 1.0.1-Preview-01 now accepts no empty template given.
