### ISSUE TITLE
Add short name support for tables

### ISSUE THREAD

**Issue by jbomhold3** [chanan/BlazorStrap#335]
| Current | Option 1| Option 2|
|---------|-------------|------|
| BSTableHead | BSthead | BS_thead|
| BSTableRow | BStr | BS_tr |
| BSTableBody | BStbody | BS_tbody |
| BSTableHeadCell| BSth | BS_th |
| BSTableCell | BStd | BS_td |
| BSTableFooter|  BStfoot | BS_tfoot |

**Comment by jbomhold3** [comment]
This should be in addition to not a breaking change

**Comment by jbomhold3** [comment]
Personally like option 2 easier to read

**Comment by chanan** [comment]
Check if it is an allowed tag name (hyphen might be allowed if not?)

**Comment by jbomhold3** [comment]
I did it changed it the _

**Comment by jbomhold3** [comment]
think we should also look into doing a enum flags to support BS_div common bootstrap type. Think its a bit more natural for people for example <BS_div Class="Class.Col | Class.MD-4"> just a thought

**Comment by chanan** [comment]
Yes, that would be a good edition. There is a project that someone did that had all of that - Not sure if he maintains it anymore, also I forget the name...

**Comment by jbomhold3** [comment]
Or maybe even hook the string values of a class IG <BS_div Class="col md-12">  then someone could just rename <div class in their template to <BS_div Class and they would be ported it to blazorstrap. Can tell what a class should be doing by it's name it navlink would render the navlink component with all the others being additional classes.   Just working thoughts it might not be super practical. As people do use bootstrap classes to do things it's not intended for

**Comment by jbomhold3** [comment]
Though I think the more realistic option is the flags and only use it for layout items

**Comment by chanan** [comment]
We already have enums for many other things, like the obvious one - color. We can add enums for Col - there are just more options here, but should still be doable.
