### ISSUE TITLE
BSRemoteTable: Add "WindowSize"

### ISSUE THREAD

**Issue by chanan** [chanan/BlazorStrap#336]
I added a WindowSize property to our work copy of Remote Table (which we will get rid of and use BlazorStrap once this is added in) - Just need to copy the changes into BlazorStrap

**Comment by jbomhold3** [comment]
Remote is intended to load the data as you click the next page correct?

**Comment by chanan** [comment]
Maybe Paginated Table is a better name? It emits a uri with a page number and leaves the task of loading data to the developer.

**Comment by chanan** [comment]
Added in next release
