### ISSUE TITLE
BSDropdown broken in 1.3.2

### ISSUE THREAD

**Issue by rusty-boffin** [chanan/BlazorStrap#339]
`    <BSDropdown>`
`        <BSDropdownToggle Color="Color.Primary">Generate</BSDropdownToggle>`
`        <BSDropdownMenu>`
`            <BSDropdownItem OnClick="@GenerateC">C</BSDropdownItem>`
`            <BSDropdownItem OnClick="@GenerateCS">C#</BSDropdownItem>`
`            <BSDropdownItem OnClick="@GeneratePas">Delphi</BSDropdownItem>`
`            <BSDropdownItem OnClick="@GenerateJson">JSON</BSDropdownItem>`
`            <BSDropdownItem OnClick="@GenerateXml">XML</BSDropdownItem>`
`        </BSDropdownMenu>`
`    </BSDropdown>`

In 1.3.1 this works fine, but in 1.3.2 I get a System.InvalidOperationException during rendering.

**Comment by jbomhold3** [comment]
WASM or Server?

**Comment by jbomhold3** [comment]
Error: System.InvalidOperationException: Cannot provide a value for property 'BlazorStrapInterop' ?
Add Services.AddBootstrapCss(); to your services.

**Comment by jbomhold3** [comment]
@chanan  We really should look at renaming. To me, that's bringing in the Bootstrap css not registering the Interop service.. Think simply AddBlazorStrap would be best.

**Comment by rusty-boffin** [comment]
That fixed it, thanks
