### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by jbomhold3** [chanan/BlazorStrap#341]
Dropdowns looking at docs we have Currently only buttons are supported as dropdowns. See: https://github.com/aspnet/Blazor/issues/715  this is resolved we need to enable the support here. I think we need to list all our components and start modernizing them away from all the hacks we had to do in beta.

**Comment by MasterSkriptor** [comment]
Any way I can help?

**Comment by jbomhold3** [comment]
Going to list all the components we have tomorrow. We will talk about what can be done to improve/ remove any beta bits left in the codebase. ext.

**Comment by jbomhold3** [comment]
| Components | Javascript Used | Documented missing features | Comments |
|---------------|------------------|------------------------------------|-------------|
| BSAlert         | None                | None | |
| BSBadges | None | None||
| BSBreadcrumb | None | None ||
| BSButtons | None | Addressed with 1.3.3 previews ||
| BSButtonGroups| None | None ||
| BSCards | None | None | We use a enum here for body,header,footer and never do this again else where. Maybe something to look into on other components to make them one tag IG tables.|
| BSCarousel | For animation complete | None | |
| BSCollapse | Yes for animations known bug removing collapsing needs fixed. | None | |
| BSDropdowns | None | Yes | Need to add a tags in 1.3.3|
| BSFigures | None | None | |
| BSImage | None | None | |
| BSJumbotron | None | None | None | |
| BSRow, BSCol, ext  | None | None | Can be combined into. BSDiv or something of that nature with  enum flags |
| BSListGroup | None | Many needs reviewed | again think we could enum flag this name BSList flags item and group |
|BSMedia | None | None | No changes need but we honestly could combine bsimage into this component|
|BSModal | Yes body and padding | None | |
| BSNav | None | None | |
| BSNavbar | None | Not sure the shortcoming is still valid | |
| BSPagination | None | None | We could do some work here to enable people to pass in a int and create the pages for them. Just a thought |
| BSPopover | Yes has issues | dismiss on click needs addressed | |
| BSProgress  | None | None ||
| BSSvg | None | None | This one could be moved to core and out of ext has no dependency |
| BSTable | None | None | Flags here would shorten the number of components we have to maintain.  
| BSTab | None | None | |
| BSToast | None | None | Docs need away to create a toast and remove the forever message. We also really need to look into creating a toast component that functions not just the style |
| BSToolTips | Yes | None | Has issues with this on my app seems to be working correctly on docs. Where changes made? |

## Extentions 
BSDataTable and BSTree can really be moved into the core as they have no extra dependencies.

## Themes 
Documentation is out of date.

## Documentation
I think we should better style out docs to look more like bootstraps own website. We also need to add API for each component at the bottom of the page. A list of all parameters a component has.  If it's a public method we need to add it to the docs. We also need to go in and add comments over each method so it shows up in IntelliSense.

**Comment by MasterSkriptor** [comment]
I think it would be really nice if we could do something like microsoft does with thier docs, where people could make pull request and change the docs without to open visual studio and/or set up a forked repo. I also think I'm asking a lot...

**Comment by chanan** [comment]
Not sure how to do that because in our case our docs are a Blazor client app. Although... I wonder if our Blazor page can render a markdown file directly from github... we would want to make sure though that it can still render Blazor controls... not sure that can work but it would be awesome if it could!

**Comment by MasterSkriptor** [comment]
I have a utility that converts markdown into html and sanitizes it.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by MasterSkriptor** [comment]
I used it here. https://www.rondamgabb.com/Services

**Comment by chanan** [comment]
Right the md -> html will work, but the issue is we want to render the Blazor controls on the page to show it to the user - and also it is our test bed to make sure everything is working. That’s the part I am not sure how we can do. 

Well... actually. As I was writing that I figured we can do it. 

Ok, so if we had a control that read MD and converted to html but when it got to a special string, let’s say !! Or something it knew it was a Blazor controls it could render it with any attributes. 

Let’s say:

!!bsTable hover=“true”!!

It might work..
Maybe...

**Comment by MasterSkriptor** [comment]
We should probably save that for when we have some time... It's a bucket load of technical debt. It is a cool thought though.

**Comment by jbomhold3** [comment]
Can use docfx to generate the statics and just read them the same as we are doing with the snippets. In the app it's self. So basically have no landing page for docfx and just import them into the docs.

**Comment by jbomhold3** [comment]
Or we just move all our api information to a wiki on the repo and link to it at the end of each page.
