### ISSUE TITLE
BSInput ValidateOnchange and ValidateOnBlur

### ISSUE THREAD

**Issue by tonibabieka** [chanan/BlazorStrap#342]
When ValidateOnBlur  fires, the field itself is validated.
When ValidateOnChange fires, "all the fields" are validated.
Is it posible to validate only the field when changed?
If ValidateOnBlur validation fails, the control displays in danger color but does not display in success color if the validation succeed, it returns to the default. It should be a nice behaviour to display the success color in a field or control basis. May be a ValidateFieldOnChange property? Or it is posible now?
Thanks

**Comment by jbomhold3** [comment]
Fixed in latest preview.
