### ISSUE TITLE
ElementReference fails in BsInput

### ISSUE THREAD

**Issue by tonibabieka** [chanan/BlazorStrap#343]
I got an error trying to reference a BsInput via @ref:
`<BsInput @ref=SomeRef />`
In the code there is the ElementReference:
`ElementReference SomeRef { get; set; }`
The error is:
"Error CS0029: cannot implicitly convert type 'BlazorStrap.BsInput<string>' to 'Microsoft.AspNetCore.Components.ElementReference'"
Don´t know if I´m using it incorrectly.
Thanks

**Comment by chanan** [comment]
Element Refs only work for html elements. I dont think we currently expose the base input element under BSInput, but we can certainly add that (Also feel free to send a PR exposing it).

If you need the ref to the BSInput control, you can get a Component reference.

**Comment by tonibabieka** [comment]
I was trying to set focus to an input.

**Comment by jbomhold3** [comment]
PR #340 is in the preview build
