### ISSUE TITLE
Compatibility with Blazor 0.8 (prerelease)

### ISSUE THREAD

**Issue by chucker** [chanan/BlazorStrap#35]
Various namespaces and packages have changed, including:

* the package reference to `Microsoft.AspNetCore.Blazor.Browser` becomes `Microsoft.AspNetCore.Components.Browser`
* `BootstrapComponentBase` now needs to inherit from `ComponentBase` instead of `BlazorComponent`

**Comment by chucker** [comment]
So I did some of the work and ran into https://github.com/aspnet/AspNetCore/issues/7159.

Specifically, `CarouselIndicators` cannot be used for now, because of this line:

```csharp
<CarouselIndicatorItem IsActive="@{i == ActiveIndex}" Index="@i" bind-ActiveIndex="@ClickEventActiveIndex" />
```

The `@{}` syntax is currently broken. Opening that file will crash VS, and compiling while it's closed will cause the stacktrace in the above issue.

**Comment by IvanJosipovic** [comment]
I was able to fix this issue by using @()
`<CarouselIndicatorItem IsActive="@(i == ActiveIndex)" Index="@i" bind-ActiveIndex="@ClickEventActiveIndex" />`

**Comment by chanan** [comment]
@IvanJosipovic & @chucker you both submitted PRs for 0.8.0 (initial) support. I haven't had a chance to take a look yet (slammed at work sorry) - Are they both more or less the same?

**Comment by IvanJosipovic** [comment]
It appears they are almost identical, apart from, mine has the CarouselIndicatorItem fix mentioned above.
I didn't realize there was another PR until I made mine, sorry!

**Comment by chucker** [comment]
Mine doesn’t support CarouselIndicator due to the bug on Microsoft’s end (which incidentally has been fixed last night). Ivan put in a workaround. Other than that, I just skimmed the changes and the differences are marginal (though Ivan may be using async/Task more correctly than I am).

Shouldn’t matter much but I say go with Ivan’s and proceed from there. :)

**Comment by chanan** [comment]
Merged, Release shortly.
