### ISSUE TITLE
PlaceHolder

### ISSUE THREAD

**Issue by mirfanpaki** [chanan/BlazorStrap#351]
There should be a parameter property to pass the Placeholder value, particularly, for BSInput.

**Comment by jbomhold3** [comment]
Blazor supplies additional attributes. You can simply pass in the placeholder value. That being said noted and will be added so it does show up in intelliSense

**Comment by mirfanpaki** [comment]
Thanks Chanan,

I am already using it within the code itself.  What you understood is right
that I meant it to be available part of intelligence only.



Regards,

Muhammad Irfan
+971(52) 6494099
