### ISSUE TITLE
Incorrect Tooltip location rendering

### ISSUE THREAD

**Issue by domferrari** [chanan/BlazorStrap#353]
I added BlazorStrap to a client-side application I'm writing and found that the tooltip doesn't render properly. So I created a new project with the basic template to see if I added something that may have caused the problem, but I still see the same thing.

In my code, I added a tooltip right under the counter button like so:

`<button class="btn btn-primary" @onclick="IncrementCount" id="testtest">Click me</button>
<BSTooltip Target="testtest" Placement="Placement.Top">Tooltip on Top</BSTooltip>`

This is what I get:
![image](https://user-images.githubusercontent.com/19365801/83946988-357c2f80-a7e2-11ea-8306-90cb453648e2.png)

Any ideas what I'm doing wrong?

**Comment by domferrari** [comment]
I figured out that I needed to add the following in my index.html file. 

`<script src="_content/BlazorStrap/popper.min.js"></script>`

Maybe that should be added to the installation instructions.

**Comment by chanan** [comment]
Yes we need to update the install instructions. Also the reader.md is out of date
