### ISSUE TITLE
BSBasicInput removed trailing zeros on step

### ISSUE THREAD

**Issue by dxn4259** [chanan/BlazorStrap#356]
BSBasicInput removes the trailing zeros when the step is used. If I enter a number of **101.09** and click on step up, it displays **101.1** instead of **101.10** . 

`<BSBasicInput InputType="InputType.Number" @bind-Value="@bank.Amount" step="0.01" />`

**Comment by jbomhold3** [comment]
Your passing in a double your getting back a double/float the extra zero is going to go away. If you pass it in as a string it will keep whatever format you like.

**Comment by dxn4259** [comment]
bank.Amount was currently a decimal. After creating a new string property to test it out i get the same behavior, the zero on 109.10 disappears when i click on the up arrow on the step. 

`<BSBasicInput InputType="InputType.Number" @bind-Value="@bank.AmountFormatted" step="0.01" />`

`private string _amountFormatted;

  public string AmountFormatted
  {
       get
        {
            return _amountFormatted;
        }
        set
        {
            _amountFormatted = value;
            OnPropertyChanged();
        }
`

![image](https://user-images.githubusercontent.com/46577079/84099414-29a19080-a9cf-11ea-85e2-c1edf245f1dc.png)

**Comment by jbomhold3** [comment]
ok will take a look and get something worked out in the next preview

**Comment by jbomhold3** [comment]
Sorry this is the browsers behavior not blazorstrap's. 

Working Solution add and reference format.js.
``` javascript
function fixedplaces(el, places)
{
	el.value = parseFloat(el.value).toFixed(places);
}
```
``` html
<BSBasicInput InputType="InputType.Number" @bind-Value="@bank.AmountFormatted" step="0.01"  onchange="fixedplaces(this, 2)"/>
```
https://stackoverflow.com/questions/22641074/html5-number-input-always-show-2-decimal-places
