### ISSUE TITLE
Support nullable bools in selects

### ISSUE THREAD

**Issue by pelshen** [chanan/BlazorStrap#362]
In one of the 1.3.3 previews, support was added for `bool`s in `BSInput` and `BSBasicInput` for `InputType.Select`. I'm a bit confused why the support doesn't extend to nullable `bool`s since I think a very normal use case is wanting to be able to represent the state of having not chosen Yes or No. To me this is the obvious use case over using a checkbox. Looking at the code (it has since been refactored, now in Util/TryParseString.cs) I can't work out why when most other nullable versions of types are parsed, nullable `bool`s aren't. Is this a limitation somewhere? Is there an obvious other way of doing this I haven't thought of?

**Comment by jbomhold3** [comment]
Not a limit just not an anticipated scenario. Assuming your doing "" as null?

**Comment by pelshen** [comment]
Yes, before this was added I had implemented this as a `string` which I then parsed to a `bool?` and was using `value=“”` but then if parsing failed assumed it was intended to be null (so any non true/false value would be interpreted as null - possibly too generous).

**Comment by jbomhold3** [comment]
will get this fix into next preview

**Comment by pelshen** [comment]
Any news on when the next preview or even release will be?

**Comment by chanan** [comment]
I think we can get one out by the end of the weekend.

**Comment by chanan** [comment]
Update: due to unforeseen circumstances I have not had time to work on the release this weekend. Sorry about that. My upcoming work week looks light, so hopefully I can sneak in a few hours during the next few days.

**Comment by pelshen** [comment]
Thanks for the update, appreciate this isn't your day job!

**Comment by pelshen** [comment]
Sorry to pester, but any update on a release?

**Comment by pelshen** [comment]
Hi there, I really need to know if and when there will be a new release, as otherwise I will need to make alternate plans to get the fixes.

**Comment by jbomhold3** [comment]
Will be a new release friday. However, the current preview release has this.

**Comment by jbomhold3** [comment]
https://gyazo.com/d0014d11b6955808c471ff8969dbd27a   working will be out Friday.

**Comment by jbomhold3** [comment]
Use value=""  in a bool? type if you want to be able reassign to null.

**Comment by jbomhold3** [comment]
I went ahead and just did a preview build with this update in it. https://www.nuget.org/packages/BlazorStrap/1.3.3-Preview-04
