### ISSUE TITLE
ReferenceError: Popper is not defined

### ISSUE THREAD

**Issue by TomJD** [chanan/BlazorStrap#364]
I have a `BSTab` component with a Popover on each Tab. When hovering over them, Developer Console on either Chrome or Firefox shows an error:

`ReferenceError: Popper is not defined`

with link to the JS file `blazorStrap.js`

**Comment by chanan** [comment]
I think this might not be clear in the docs but you also need to reference popper.min.js (sorry on the phone can’t get the exact line)

**Comment by chanan** [comment]
Now that I am by a computer here is an example: https://github.com/chanan/BlazorStrap/blob/master/src/Sample/wwwroot/index.html#L47

We will update the docs to make this more clear (Or if possible auto inject that into the head)

**Comment by TomJD** [comment]
Thank you, I can confirm that does the job!
