### ISSUE TITLE
Collapsibles - start uncollapsed on load

### ISSUE THREAD

**Issue by jordanwilcox** [chanan/BlazorStrap#367]
Hello,

Is there currently functionality to start collapsible collapsed rather than collapsed?

I thought it may have been "IsInverse" in the <BSCard> element but had no luck.

I am currently unaware if I can override this via CSS either.

Below is the collapsible I am using (the one which mimics the bootstrap accordion):

            <BSCollapseGroup>
                <BSCollapseItem >
                    <BSCard CardType="CardType.Header" Class="content-box-child2" @onclick="SettingsMenuClick" >
                        <BSCollapseToggle Class="inf-accordion-card" IsLink="true">
                            <h5 class="text-heading inline-h-top">
                                <i class="fa fa-cog fa-lg main-theme-accent" />
                                &nbsp;
                                VIDEO SETTINGS
                                &nbsp;
                                @if (settingsShown)
                                {
                                    <i class="fa fa-angle-up " />
                                }
                                else
                                {
                                    <i class="fa fa-angle-down" />
                                }
                            </h5>
                        </BSCollapseToggle>
                        <hr />
                        Collapsible content...
                    </BSCard>
                </BSCollapseItem>
            </BSCollapseGroup>

**Comment by MasterSkriptor** [comment]
I have the feeling I am not understanding exactly what you are saying. But IsOpen on the BSCollapseItem should do what you are trying to do if I understand it correctly. IsOpen="false" will start the item collapsed, IsOpen="true" will start the item closed.

**Comment by jordanwilcox** [comment]
> I have the feeling I am not understanding exactly what you are saying. But IsOpen on the BSCollapseItem should do what you are trying to do if I understand it correctly. IsOpen="false" will start the item collapsed, IsOpen="true" will start the item closed.

Yes you are correctly understanding my issue. I have tried using the IsOpen attribute on the <BSCollapseItem> as you mentioned but there doesn't seem to be an attribute named this in BSCollapseItem. However I have tried it anyway:

`<BSCollapseItem IsOpen="False">`

When trying to load the page with the collapsible in I then get the error: 

`Error: System.InvalidOperationException: Object of type 'BlazorStrap.BSCollapseItem' does not have a property matching the name 'IsOpen'.` which I think I expected as it's not an attribute.

Any ideas?

**Comment by MasterSkriptor** [comment]
I see, I am working on it. Will get back to you when I have something that works.

**Comment by MasterSkriptor** [comment]
Have you tried putting your collapseable content into a BSCollapse? It has an IsOpen property that you can  set to @settingsShown which seems to work for me. Like this:

```
<BSCollapseGroup>
           <BSCollapseItem >
                <BSCard CardType="CardType.Header" Class="content-box-child2" @onclick="SettingsMenuClick" >
                    <BSCollapseToggle Class="inf-accordion-card" IsLink="true">
                        <h5 class="text-heading inline-h-top">
                            <i class="fa fa-cog fa-lg main-theme-accent" />
                            &nbsp;
                            VIDEO SETTINGS
                            &nbsp;
                            @if (settingsShown)
                            {
                                <i class="fa fa-angle-up " />
                            }
                            else
                            {
                                <i class="fa fa-angle-down" />
                            }
                        </h5>
                    </BSCollapseToggle>
                    <hr />
                    <BSCollapse IsOpen="@settingsShown">Collapsible content...</BSCollapse>
                </BSCard>
            </BSCollapseItem>
        </BSCollapseGroup>

```

**Comment by jordanwilcox** [comment]
Putting IsOpen on the BSCollapse tag has worked!

Thank you.
