### ISSUE TITLE
Input with type Email fails to render validation styles correctly

### ISSUE THREAD

**Issue by shawty** [chanan/BlazorStrap#371]
Given the following simple form created using Blazor Strap v1.3.2

![image](https://user-images.githubusercontent.com/1876454/87096400-a1671300-c23a-11ea-8a76-14167c27b1a0.png)

We get the following expected view when we open the page containing the form

![image](https://user-images.githubusercontent.com/1876454/87096456-ca87a380-c23a-11ea-97f8-55c625a70aa6.png)

The browser dev tools confirm the field is being rendered correctly as an Email type

![image](https://user-images.githubusercontent.com/1876454/87096529-f4d96100-c23a-11ea-8dfe-1a890e20ae63.png)

If we enter a non email value and tab out of the field

![image](https://user-images.githubusercontent.com/1876454/87096601-1a666a80-c23b-11ea-8ce9-47a45168d06d.png)

We see that (What appears to be BlazorStrap) passes the validation, but (What Appears to be Bootstrap) applies the invalid styling.

Browser tools show expected BS4 styles (Consistent with a valid input) in the class attributes 

![image](https://user-images.githubusercontent.com/1876454/87096774-76c98a00-c23b-11ea-97bd-256cea1eba70.png)

If we click back in to the input, the red highlight disappears

![image](https://user-images.githubusercontent.com/1876454/87096824-96f94900-c23b-11ea-8583-285e4837b6a6.png)

And no apparent difference in the rendered browser output

![image](https://user-images.githubusercontent.com/1876454/87096876-b2645400-c23b-11ea-9750-f14fceace9db.png)

App is Serverside blazor, and is pulling in most uptodate BS4 from CDN

![image](https://user-images.githubusercontent.com/1876454/87096950-eccdf100-c23b-11ea-94ae-0c939ef8be60.png)

Test browser is Firefox 77 64bit under win 10

![image](https://user-images.githubusercontent.com/1876454/87097012-0ec77380-c23c-11ea-967e-4c079d05c9b7.png)

Not yet (As I write this) been tested on other browsers, but will confirm if occurs and report back here.

Strange enough, while researching this issue, I noticed that "Blazorize" has a similar problem

![image](https://user-images.githubusercontent.com/1876454/87097279-bcd31d80-c23c-11ea-9c3e-6ca1b305f053.png)

But not with the email control, only with the "Pattern" control.

Which leads me to suspect maybe a browser thing.

**Comment by chanan** [comment]
I briefly looked at this yesterday along with @shawty - I am unlcear how this happens since it doesn't *seem* that the box is getting the wrong class. I will try to look at this weekend now that I am back home.

**Comment by shawty** [comment]
@chanan no worries.  I've gone back to my previous method of applying bootstrap validation classes in blazor.  :-)

I previously did it by overriding the input base myself just for the handful of inputs I needed.

I briefly looked at blazorise too, but dang ...  too much nesting :-)

I didn't get chance to check it in other browsers as I had to finish the feature demo for my client for today, and check I could apply the styles correctly.

So for now I'm back to using custom controls, I'll look to switching back to this in the future.

**Comment by jbomhold3** [comment]
Working in latest build. Have not back tested this with older dotnet versions.
        [Required]
        [EmailAddress]
        public string Email { get; set; };

**Comment by shawty** [comment]
sweet, if I get time over the christmas break, I'll test with my previous use cases.
