### ISSUE TITLE
Setting bootstrap version needs clarification

### ISSUE THREAD

**Issue by mark-at-tusksoft** [chanan/BlazorStrap#377]
On the home page, to override the version, the third items is as follows:

> Call `await BootstrapCss.SetBootstrapCss("4.3.1");`

It is not clarified if this is supposed to be placed in a code block and if it should be in an `OnAfterRenderAsync()` override method.

**Comment by chanan** [comment]
Thanks, will update that next update to the docs.

In the meantime, if anyone is wondering, here is an example: https://github.com/chanan/BlazorStrap/blob/master/src/SampleCore/Shared/MainLayout.razor#L14-L36

**Comment by jbomhold3** [comment]
@chanan What was the issue causing the expect prerendering? Nothing is thrown under latest build so seams unnecessary.
