### ISSUE TITLE
Feature Request: BSComboBox

### ISSUE THREAD

**Issue by davidnmbond** [chanan/BlazorStrap#382]
It would be great if there were a BSComboBox (a cross between a Text input and a dropdown, with text autocomplete).

**Comment by MasterSkriptor** [comment]
I have been really busy as of late, but if I get a chance I will take a look at this. If anyone else has some free time feel free to submit a pr.

**Comment by timbze** [comment]
Here's something similar that could be used as an example: https://github.com/loresoft/LoreSoft.Blazor.Controls
