### ISSUE TITLE
Carousel never notifies animation finished when site opened in browser over RDP

### ISSUE THREAD

**Issue by mark-at-tusksoft** [chanan/BlazorStrap#383]
I know this is a pretty far-fetched edge-case, but I just ran into it today while doing a demo.
After the first advance of a slide it appears the JSInterop is never notified of the animation finish event.
If I reload the same browser page that was opened over RDP once I have physically logged in, the issue goes away.

It could also be completely on Blazor or WASM for that matter. If you determine that is the case I will open an issue elswhere accordingly.

My carousel attrs:
`<BSCarousel NumberOfItems="3" Interval="int.MaxValue" Wrap="false" Pause="false" Fade="true">`

I am using custom navigation buttons (though I highly doubt these are the cause as they are essentially the same behavior as the built-in controls), see below:

BSCarouselCustomControls.razor

```
@namespace MyApp.Client.Components
@inherits BSCarouselCustomControlsBase

<DynamicElement @attributes="@UnknownParameters" TagName="div" class="@Classname" role="navigation">
    <div class="col-auto">
        @if (CurrentSlide == NumberOfItems && NumberOfItems > 1)
        {
            <button type="button" class="btn btn-primary" @onclick="StartOver">Go Back</button>
        }
        @if (CurrentSlide + 1 <= NumberOfItems)
        {
            <button type="button" class="btn btn-primary" @onclick="NavigateForwards">Next Step</button>
        }
    </div>
</DynamicElement>
```

BSCarouselCustomControls.razor.cs

```
using BlazorComponentUtilities;
using BlazorStrap;
using Microsoft.AspNetCore.Components;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace MyApp.Client.Components
{
    public abstract class BSCarouselCustomControlsBase : ComponentBase
    {
        [Parameter(CaptureUnmatchedValues = true)] public IDictionary<string, object> UnknownParameters { get; set; }

        protected string Classname =>
         new CssBuilder("carousel-controls row justify-content-center py-5")
             .AddClass(Class)
         .Build();

        [Parameter] public int NumberOfItems { get; set; }
        [Parameter] public string Class { get; set; }
        [CascadingParameter] internal BSCarousel Parent { get; set; }

        [Parameter] public EventCallback<int> ActiveIndexChanged { get; set; }

        public int CurrentSlide => Parent.ActiveIndex + 1;

        protected async Task NavigateForwards()
        {
            if (Parent.AnimationRunning || Parent.ActiveIndex + 1 > Parent.NumberOfItems) return;
            Parent.ResetTimer();
            Parent.ActiveIndex++;
            await ActiveIndexChanged.InvokeAsync(Parent.ActiveIndex).ConfigureAwait(false);
        }

        protected async Task NavigateBackwards()
        {
            if (Parent.AnimationRunning || Parent.ActiveIndex - 1 < 0) return;
            Parent.ResetTimer();
            Parent.ActiveIndex--;
            await ActiveIndexChanged.InvokeAsync(Parent.ActiveIndex).ConfigureAwait(false);
        }

        protected async Task StartOver()
        {
            if (Parent.AnimationRunning) return;
            Parent.ResetTimer();
            Parent.ActiveIndex = 0;
            await ActiveIndexChanged.InvokeAsync(Parent.ActiveIndex).ConfigureAwait(false);
        }
    }
}
```

**Comment by chanan** [comment]
Are you sure this only happens on RDP? There is another issue we found with animation finished with accordion that doesn't fire, maybe this is a similar issue and it's just more noticeable on RDP?

**Comment by mark-at-tusksoft** [comment]
@chanan Link?

**Comment by chanan** [comment]
#330

**Comment by mark-at-tusksoft** [comment]
> Are you sure this only happens on RDP? There is another issue we found with animation finished with accordion that doesn't fire, maybe this is a similar issue and it's just more noticeable on RDP?

It's feasible. I wouldn't be surprised if FF has some way of knowing its in an RDP session and turns on reduced animations. I am unfamiliar with the feature. Also, I am at the machine right now with no method to RDP into it. Since this is an edge case and a low priority, I can wait until #363 is released and up on NuGet; ping me here when it is up and I'll test.

**Comment by mark-at-tusksoft** [comment]
@chanan Just to follow up, I tested the 1.3.3 patch from NuGet and the issue persists over RDP
