### ISSUE TITLE
IE11 syntax error - arrow function used

### ISSUE THREAD

**Issue by ashickton** [chanan/BlazorStrap#387]
BlazorStrap Version: 1.3.2

The following error occurs in IE 11:
SCRIPT1002: Syntax error blazorStrap.js (67,47)

The problem seems to be caused by the use of arrow function notation:

`   closeOtherPoppers: function(popperId) {
        window.blazorStrap.poppers.forEach(**p =>** {
            if (p !== popperId) {
                var el = document.getElementById(p);
                if (el) {
                    el.style.visibility = "hidden";
                    el.style.pointerEvents = "none";
                }
            }
        });
        if (window.blazorStrap.poppers.indexOf(popperId) === -1) {
            window.blazorStrap.poppers.push(popperId);
        }
    },`

**Comment by chanan** [comment]
this should be converted to (pseudo code):

```
for(var i=0; i < window.blazorStrap.poppers.length - 1; i++)
```

**Comment by garrywma** [comment]
Any news on this one. Have a client that still needs IE11 - although trying to wean them off.
