### ISSUE TITLE
Modal break scrollbar when closed before modal fully load

### ISSUE THREAD

**Issue by RomainAn** [chanan/BlazorStrap#388]
Hi guys,

I come to you because i have some issue with the modal.
When having a page with a scrollbar, if i open a modal and close it right after i open it, the scrollbar stay hidden and i can't scroll anymore.

is there any way to fix this behavior ?

Thank you
Have a great day !

**Comment by jbomhold3** [comment]
Though we had this one fixed. What version of blazorstrap are you using?

**Comment by RomainAn** [comment]
Hello jbomhold3 ! I'm currently using 1.3.2 !

**Comment by jbomhold3** [comment]
Can create a test branch and check if the issue clears up in version 1.3.3-Preview-03

**Comment by RomainAn** [comment]
Hi, i tried the 1.3.3-Preview-03 version, and i have no more modal displaying at all.
The "shadow div" is appearing but nothing else

**Comment by RomainAn** [comment]
It's working smoothly now ( I had the clear the cache )
Only issue i see now, if i close the modal using Esc key, i get :
- Cannot read property 'func' of undefined at HTMLDocument.func

**Comment by jbomhold3** [comment]
Yea thats a minor bug in the javascript trying to remove the nested modals func from the array after its already removed can safely ignore it. Will get it worked out

**Comment by RomainAn** [comment]
Thank you for your help and your great work on BlazorStrap, we all appreciate it !

Have a great day and stay safe !
