### ISSUE TITLE
Border pops up around modal when clicking outside of a button

### ISSUE THREAD

**Issue by pauladiazl** [chanan/BlazorStrap#389]
Hi All - whenever I click somewhere that is not any type of button in the modal, a black and white border pops up and it won't disappear until a button is selected. Please see screenshot attached

![ModalBorder-Bug](https://user-images.githubusercontent.com/68753067/91078744-ae806b80-e608-11ea-99c8-d702a8ed2e0c.png)
. 

Is there a way to stop that border from popping up or to make it transparent? 

Thanks in advance!

**Comment by jbomhold3** [comment]
include _content/BlazorStrap/css/cromefix.css   it will remove the border.. 

https://github.com/chanan/BlazorStrap/blob/master/src/BlazorStrap/wwwroot/css/cromefix.css
The file is here you could also simply add it to your existing site css

**Comment by pauladiazl** [comment]
That worked, thank you!
