### ISSUE TITLE
Consider changing project structure to add Blazor server side 

### ISSUE THREAD

**Issue by chanan** [chanan/BlazorStrap#39]

**Comment by jtmueller** [comment]
I guess it's now called Razor Components, which can be hosted either server-side in ASP.NET Core, or client-side in Blazor. I think working in both environments would be a valuable feature.

https://docs.microsoft.com/en-us/aspnet/core/razor-components/?view=aspnetcore-3.0

**Comment by pjmagee** [comment]
I'm using RazorComponents at the moment and I'm using BlazorStrap. What needs to change?

**Comment by chanan** [comment]
Closing this as I duplicated it in #74 which I am about to fix and include a minimal SSB sample
