### ISSUE TITLE
[Feature] Navigate to other tab programmatically

### ISSUE THREAD

**Issue by timbze** [chanan/BlazorStrap#390]
I know of the `InitialSelection` parameter in BSTab component

**I would like to have a link that says "Go back to main tab"** that would do the same thing as clicking the Info tab in screenshot below, I want my save button for the modal to only be on the main "Info" tab. Maybe it can already be done, but I don't find it documented.
Example:
![Screenshot from 2020-09-01 09-55-53](https://user-images.githubusercontent.com/35117769/91875993-70eb9600-ec39-11ea-9366-b324bce8575e.png)

**Comment by chanan** [comment]
Can you set the `Selected` property of BSTabGroup to be the BSTab of Info?

**Comment by timbze** [comment]
Yes, just looked through the code a bit. That way I would have to get a reference to each tab. And if I get reference to the tab then I can also do `tabReference.Select()`

My proposal is to add a new method in BSTabGroup like this (I have it ready for a PR if you think it's a good idea):
```csharp
public void SelectTabById(string tabId)
{
    Selected = Tabs.Find(i => i.Id == tabId) ?? 
        throw new ArgumentOutOfRangeException($"The tab with Id { tabId } does not exist");
}
```

**Comment by chanan** [comment]
Yes, that sounds good
