### ISSUE TITLE
Build issue - html tag without value

### ISSUE THREAD

**Issue by timbze** [chanan/BlazorStrap#392]
https://github.com/chanan/BlazorStrap/blob/535ee8b4dbc782bd0d6e6daf74c09d9b6c4230b3/src/BlazorStrap/Components/Model/BSModalHeader.razor#L6

My latest preview version of VS 2019 could not build BlazorStrap before removing the `autofocus` tag in this line. Seems like it should have a value, but interesting that it has been working all this time.

**Comment by chanan** [comment]
That is curious, it looks like syntax that works in react - so in that case, ost likely my fault :)

Since you said you are doing a PR anyway, can you add that please.

**Comment by timbze** [comment]
Sure

**Comment by timbze** [comment]
I don't see the purpose for autofocus here, but do you want me to keep it, or remove it? I can do `autofocus="autofocus"`
