### ISSUE TITLE
Modal opens too wide when viewport is narrow but page content is wide

### ISSUE THREAD

**Issue by timbze** [chanan/BlazorStrap#394]
I have a modal that opens perfectly on a computer screen, but on a phone it opens much wider.

**Here's what happens:**
- The modal is set to regular width
- Computer screen is 1920 pixels
- Phone screen is about 450 pixels wide
- Html content on screen is about 1200 pixels wide
- Content on phone screen also shows about 1200 pixels (it's not enhanced for small screens)

**When opening modal on computer screen:**
- Modal is about 500 pixels wide

**When opening modal on phone screen:**
- Modal is about 1200 pixels wide

**Expected:**
It should be the width of phone screen (for sure not wider than what it's showing on computer screen)

**Comment by chanan** [comment]
That is weird, we will need to trace down the same exact CSS in bootstrap and see it on the phone to see what we missed.
