### ISSUE TITLE
BSDataTable RemotePagination usage documentation?

### ISSUE THREAD

**Issue by Flash619** [chanan/BlazorStrap#395]
I am trying to add pagination to a `BSDataTable`. I found a `RemotePagination` class as included within the `BSDataTable` component. Unfortunately I am unable to find any usage examples for the `RemotePagination` component. I attempted the following, however it caused an error rendering the page.

```c#
            <BSDataTable Items="@_tableRows" Context="location" IsResponsive="true" IsStriped="true">
                <HeaderTemplate>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Name</th>
                        <th scope="col">Alternate Name</th>
                        <th scope="col">Enabled</th>
                    </tr>
                </HeaderTemplate>
                <NoDataTemplate>
                    <td colspan="4">No locations found.</td>
                </NoDataTemplate>
                <ItemTemplate>
                    <th scope="row">@location.ScopedId</th>
                    <td>@location.Name</td>
                    <td>@location.AlternateName</td>
                    <td>@location.Enabled</td>
                </ItemTemplate>
                <FooterTemplate>
                    <RemotePagination Page="1" TotalRecords="200" RecordsPerPage="10"/>
                </FooterTemplate>
            </BSDataTable>

@code {
    private IEnumerable<Location>? _tableRows;
    public LocationBasicInfoForm? LocationBasicInfoForm { get; set; }

    protected override async Task OnInitializedAsync()
    {
        var result = await LocationApiService.GetLocations();
        _tableRows = result.Data;
        StateHasChanged();
    }
}
```

 The exact error was as follows...

> Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
>       Unhandled exception rendering component: Object reference not set to an instance of an object.
> System.NullReferenceException: Object reference not set to an instance of an object.
>   at BlazorStrap.Extensions.BSDataTable.RemotePagination.GetUrl (System.Int32 page) <0x3a50640 + 0x00016> in <filename unknown>:0 
>   at BlazorStrap.Extensions.BSDataTable.RemotePagination+<>c__DisplayClass31_0.<BuildRenderTree>b__5 (Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder3) <0x3a6d058 + 0x00042> in <filename unknown>:0 
>   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.AddContent (System.Int32 sequence, Microsoft.AspNetCore.Components.RenderFragment fragment) <0x3555110 + 0x0001e> in <filename unknown>:0 
>   at BlazorStrap.BSPaginationItem.<BuildRenderTree>b__0_0 (Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder2) <0x3a50148 + 0x00026> in <filename unknown>:0 
>   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.AddContent (System.Int32 sequence, Microsoft.AspNetCore.Components.RenderFragment fragment) <0x3555110 + 0x0001e> in <filename unknown>:0 
>   at BlazorStrap.Util.Components.DynamicElement.BuildRenderTree (Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder builder) <0x37eca40 + 0x00082> in <filename unknown>:0 
>   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0 (Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder builder) <0x33829b8 + 0x0001a> in <filename unknown>:0 
>   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch (Microsoft.AspNetCore.Components.Rendering.RenderBatchBuilder batchBuilder, Microsoft.AspNetCore.Components.RenderFragment renderFragment) <0x33823d8 + 0x00062> in <filename unknown>:0 
>   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch (Microsoft.AspNetCore.Components.Rendering.RenderQueueEntry renderQueueEntry) <0x3381dd8 + 0x0004c> in <filename unknown>:0 
>   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue () <0x3381310 + 0x00098> in <filename unknown>:0 

Seems to me that the `UrlPattern` parameter is required... but again, I'm not sure I'm actually using this properly to begin with. 🤔

**Comment by angelru** [comment]
no documentation for this extension

**Comment by markstraw** [comment]
Still no documentation 3 and half years later.
