### ISSUE TITLE
Need to be able to use this fully offline

### ISSUE THREAD

**Issue by dbowser** [chanan/BlazorStrap#398]
We are trying to run our app fully offline in a secure intranet. 
The BlazorStrap dll is having issues that I think are coming from the following:
            link.href = "https://stackpath.bootstrapcdn.com/bootstrap/" + version + "/css/bootstrap.min.css";
            link.href = "https://stackpath.bootstrapcdn.com/bootswatch/" + version + "/" + theme + "/bootstrap.min.css";
We need a way to use a local copy for fully offline operation.

Thanks

**Comment by chanan** [comment]
Are you calling `SetBootstrapCss` ?

**Comment by dbowser** [comment]
Yes. Should I not have been?

**Comment by chanan** [comment]
setBootStrapCss will use a cdn to set the CSS and allows you to switch themes.

Remove the call and set your own CSS in the head of the index.html

An improvement might be to allow you to store 1 or more CSS themed files and use them in conjunction with setBootStrapCss - but that only matters if you want to allow your end user to switch themes, so unless that is your use case, it is not needed. However, if you want to submit a PR...

**Comment by dbowser** [comment]
OK, thank you. I will try to get that working. I am still trying to get my arms around all the aspects of CSS and how they interrelate.

**Comment by jbomhold3** [comment]
Is this issue safe to close?

**Comment by dbowser** [comment]
Yes thanks. I was able to get it to use all local css.
