### ISSUE TITLE
net5.0 InvalidOperationException: EditForm requires a Model parameter, or an EditContext parameter, but not both.

### ISSUE THREAD

**Issue by jespersh** [chanan/BlazorStrap#399]
I'm testing out net5.0-rc1 and BlazorStrap and noticed this started appearing:
`InvalidOperationException: EditForm requires a Model parameter, or an EditContext parameter, but not both.`

If you intend to test the repo, then you'll need VS 16.8.0 **Preview** 3.2

Sample here: https://github.com/jespersh/BlazorStrap-Issue/blob/master/BlazorApp2/Pages/Index.razor#L10

Possible offending code: https://github.com/chanan/BlazorStrap/blob/f26f11fd26c49a7137a1da0ae4dfc0b1df900b0b/src/BlazorStrap/Components/Forms/BSForm.cs#L49-L50

**Comment by jbomhold3** [comment]
Will be releasing a .net 5 update soon. But under staffed at work so it's delaying everything else.

**Comment by jbomhold3** [comment]
1.5.0-preview-01 has the changes

**Comment by jespersh** [comment]
I see net5-rc2 was literally just released. I'll update the packages once I gloss it over

**Comment by jbomhold3** [comment]
Any breaking changes that would prevent the preview I just push from working with rc2?

**Comment by laubfall** [comment]
Hi,

i just hit this issue with NET5 and Blazorstrap in my project. I tried the 1.5.0-preview-01 release but the exception occurs again. So just for my understanding: should this preview release fix the issue?

**Comment by jespersh** [comment]
> Hi,
> 
> i just hit this issue with NET5 and Blazorstrap in my project. I tried the 1.5.0-preview-01 release but the exception occurs again. So just for my understanding: should this preview release fix the issue?

I'll check it out this weekend. I've been preoccupied with nonblazor things since net5s release

**Comment by jespersh** [comment]
@laubfall could you check with https://github.com/jespersh/BlazorStrapExampleFormProject? I couldn't get the exception on `1.5.0-preview-01`

**Comment by laubfall** [comment]
> @laubfall could you check with https://github.com/jespersh/BlazorStrapExampleFormProject? I couldn't get the exception on `1.5.0-preview-01`

Hi Jesper,

the exception disappeared, i think the reason was that my binary was not build correctly with the new Blazorstrap Dependency. Sorry for that and thanks for your quick reply.

Greetings,
Daniel
