### ISSUE TITLE
Receiving error "Could not find 'setPopper' in 'window.blazorStrap'."

### ISSUE THREAD

**Issue by domferrari** [chanan/BlazorStrap#402]
I just upgraded to version 1.3.3 and when I run my wasm application, I receive the error **Could not find 'setPopper' in 'window.blazorStrap'.**

When I look at the content of blazorStrap.js in the browser's **Sources** tab, I don't see a setPopper function. I see it in the GitHub repository's version of blazorStrap.js. Did the 1.3.3 NuGet package get the latest blazorStrap.js version?

**Comment by chanan** [comment]
Is blazorStrap.js loading at all?
Or in other words, in your index.html are you referencing blazorStrap.js?

**Comment by domferrari** [comment]
Yes, my index.html has:

 

<script src="_content/BlazorStrap/blazorStrap.js"></script>

 

Interestingly, I don’t get the error after I grabbed the blazorStrap.js from GitHub and put it in wwwroot and changed the script tag to:

 

<script src="blazorStrap.js"></script>
