### ISSUE TITLE
Multiple modal headers generate multiple close buttons in the top right.

### ISSUE THREAD

**Issue by TheAnachronism** [chanan/BlazorStrap#403]
I was playing around with the modal component and discovered, that using multiple BSModalHeader components, not only generates multiple headers (of course that's what I want) but also multiple close buttons in the top right. So when setting the OnClick event on the first one, it gets overridden by the second and so on.
By using multiple headers a modal can get quite some nice design so it would be cool to support something like this.

**Comment by jbomhold3** [comment]
https://gyazo.com/b27c4fc2ff10556cd39e01c3b1185e0e
You got it. will be in next version
``` html
<BSModal @ref="LiveDemo">
    <BSModalHeader OnClick="@(() => LiveDemo.Hide())">Modal title</BSModalHeader>
    <BSModalHeader HideCloseButton="true">Modal title2</BSModalHeader>
    <BSModalHeader HideCloseButton="true">Modal title3</BSModalHeader>
    <BSModalBody><p>Modal body text goes here.</p></BSModalBody>
    <BSModalFooter>
        <BSButton Color="Color.Secondary" @onclick="@(() => LiveDemo.Hide())">Close</BSButton>
        <BSButton Color="Color.Primary" @onclick="@(() => LiveDemo.Hide())">Save Changes</BSButton>
    </BSModalFooter>
</BSModal>
```

**Comment by jbomhold3** [comment]
Ready and will be in next release closing.
