### ISSUE TITLE
Modal dialog is not showing in .net core 3.1.9

### ISSUE THREAD

**Issue by dsapoznik** [chanan/BlazorStrap#405]
Today I upgraded my Blazor Server Side app to .net core 3.1.9.  Then I noticed that the BSModel is not shwoing anymore.

I tested with BlazorStrap version 1.3.3 and then I tried the 1.5.0 Preview with the same issue.

There was no error in the browser console.

Then I created a new Blazor app from scratch to test again the BSModel and is the dialog is not showing anymore.

Other BlazorStrap controls works fine.

Any idea what could be the problem ?

**Comment by farzad528** [comment]
I am having the same issue. This worked just fine on Client-side for me but not server-side

**Comment by jbomhold3** [comment]
Anyone have repo project available? Client side / Server side are both working right in core project.

**Comment by mterwoord** [comment]
I'm also seeing this. I tried to make a simple test project (clean one) but couldn't reproduce there. Did anyone find a work around for this?
