### ISSUE TITLE
How to set option container with popovers/tooltips?

### ISSUE THREAD

**Issue by XzaR90** [chanan/BlazorStrap#406]
How to set option container with popovers? Setting the data attribute data-container="body" does not work.

How can we set the option  `container: 'body'`? Using popover in list-group does not work without this option.

```
$(function () {
  $('.example-popover').popover({
    container: 'body'
  })
})
```

**Comment by TrieBr** [comment]
@jbomhold3 You marked this as complete, but I don't see the option. All my tooltips are obscured by other elements without being able to specify attaching it to the body element.

**Comment by jbomhold3** [comment]
You're referencing a 1.0 issue cleaned up when V5 came out. However, I added PopperOptions parameter to VNext .
https://www.nuget.org/packages/BlazorStrap/5.2.100-Preview2b
Example 
https://popper.js.org/docs/v2/constructors/
```html 
<BSPopover Placement="Placement.Left" Target="popoverLeft" PopperOptions="@(new { strategy = "fixed"})">
```
