### ISSUE TITLE
Multiple Carousel items

### ISSUE THREAD

**Issue by imflitch** [chanan/BlazorStrap#409]
Isn't it possible to make more than 1 item in a Carousel - like 3?

**Comment by chanan** [comment]
Doesn't the demo page have more than one item? https://blazorstrap.io/carousels

**Comment by imflitch** [comment]
Hi.
No, maybe i wasn't clear enough.
I want to make multiple slides - for example so it shows 3 slides at a single time instead of a single

**Comment by jbomhold3** [comment]
Based on the question. Your wanting slide 1, 2, 3 for example to show 33% width each so they fix under one view?

**Comment by imflitch** [comment]
Yes

tir. 1. dec. 2020 kl. 14.58 skrev John Bomhold <notifications@github.com>:

**Comment by jbomhold3** [comment]
At the moment you would have to do this manually. But will look into getting this added by next release.

**Comment by jbomhold3** [comment]
Please test in BlazorStrap 1.5.101-Preview-2 close if fixed
