### ISSUE TITLE
typeof Popper === undefined is false

### ISSUE THREAD

**Issue by saber-wang** [chanan/BlazorStrap#413]
https://github.com/chanan/BlazorStrap/blob/dfd2afe6c7e44d9e1bd6d8ee5629f3b31bd98294/src/BlazorStrap/wwwroot/blazorStrap.js#L215

error:
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Cannot set property 'src' of undefined
      TypeError: Cannot set property 'src' of undefined

typeof Popper === typeof undefined is true

**Comment by jemprince** [comment]
++ this issue

**Comment by Ted-Lapkin** [comment]
Having this issue on 1.5.0-preview-02 when trying to use a tooltip.

**Comment by jbomhold3** [comment]
Ran into the issue testing recent changes. It will be fixed in next release

**Comment by jbomhold3** [comment]
Ready and will be in next release closing.
