### ISSUE TITLE
Carousel wonta accept Interval="0"

### ISSUE THREAD

**Issue by jemprince** [chanan/BlazorStrap#415]
should be:
 protected override void OnInitialized()
        {
            if (Timer == null)
            {
// move this before Timer() created
                if (Interval == 0)
                    return;

                Timer = new Timer(Interval);
                Timer.Elapsed += OnTimerEvent;
                Timer.AutoReset = true;
                  Timer.Start();
            }
        }

**Comment by jbomhold3** [comment]
Thank you for the feedback. However, this solution would cause a null reference error in  DoAnimations, ResetTimer, ext.  Working on this issue now and will be in next release.

**Comment by jbomhold3** [comment]
Ready and will be in next release closing.
