### ISSUE TITLE
Use of ConfigureAwait(false) in blazor components. Is it recommended?

### ISSUE THREAD

**Issue by Alvaromah** [chanan/BlazorStrap#422]
The method ConfigureAwait(false) is used in most awaited task in components. But as of the following issue in aspnetcore, it is not necessary:
[Guidance on using ConfigureAwait(...) in async life-cycle methods in Razor component](https://github.com/dotnet/aspnetcore/issues/13545#issuecomment-526266322)

Is this guidance taken into consideration?

**Comment by chanan** [comment]
No it's not. Those configure awaits have been there since the alpha versions of Blazor pre 1.0. If they aren't needed we can remove them
