### ISSUE TITLE
BSCollapse causes JS error

### ISSUE THREAD

**Issue by pelshen** [chanan/BlazorStrap#423]
I haven't been able to reproduce on a minimal example, but in two completely unrelated projects I've hit an issue where at some point when navigating away from a page with `BSCollapse`, or removing them from a page conditionally when wrapped in an `@if`, you get a JS error from `collapsingElementEnd` where the passed in element is `undefined`, crashing the whole app. It doesn't happen consistently which makes me think timing is involved. This is called by `ClearOffsetHeight` in `BlazorStrapInterop.cs`, called by the `AnimationEnd` in `BSCollapse.razor.cs` which is the callback for `@ontransitionend` in `BSCollapse.razor`. I haven't been able to work out why this is being called at that time - when the element no longer exists - at a guess some cleanup is trying to happen?

Pull request wrapping the contents of the JS function with an `if (element) {}` to follow. This fix isn't going to cause any problems even if it seems to be covering up an issue, rather than properly solving. I just don't have any more time to work out what is going on. If someone has a better idea to fix it higher up the chain, I'm all ears.

**Comment by pelshen-bankuet** [comment]
When do you think we will have a release with this fix?

**Comment by jbomhold3** [comment]
Yes going to take a weeks vacation soon from real Job so will have time to test and get a full release out.

**Comment by Tiberriver256** [comment]
If anyone runs across this and needs a monkey patch to keep this error from happening while we wait for a patch this should work in your site.js file. Just make sure it loads after the blazorStrap.js file from this library:

```js
window.blazorStrap["_collapsingElementEnd"] = window.blazorStrap["collapsingElementEnd"];
window.blazorStrap["collapsingElementEnd"] = function (element) {
    if (element == null) {
        return true;
    }
    return window.blazorStrap["_collapsingElementEnd"](element);
}
```

**Comment by jbomhold3** [comment]
Released Sorry about the delay hopefully will get back to a better release cadence with things normalizing out a little bit.
