### ISSUE TITLE
Inject Modal with component

### ISSUE THREAD

**Issue by georgeemr** [chanan/BlazorStrap#425]
Capacity to call a modal with a custom component as a body.
For example:

Modal.Show<MyComponent>(Title, Configuration, Parameters);

**Comment by jbomhold3** [comment]
Modals can be so many things knowing what your looking for would help with designing it.
I'm assuming you want to do something like Model.Show("Are you sure?", BSModalType.Confirm, new BSModalParamters() { IsCentered = true};
