### ISSUE TITLE
How to Update Dynamic Tabs?

### ISSUE THREAD

**Issue by scubakiz** [chanan/BlazorStrap#429]
I have the following vertical tab list (using BootStrap):

```
<div class="row">
   <BSTabGroup>
      <div class="col-md-3" style="padding-left: 0px">
           @lock (ActiveServices)
           {
                <BSTabList IsPills="true" IsList="true" IsVertical="true">
                         @foreach (var service in ActiveServices)
                         {
                              <BSTab>
                                    <BSTabLabel>@service.Metadata.Name</BSTabLabel>
                                    <BSTabContent>
                                         <ServiceComponent CurrentService="@service" ServicePods="@GetServicePods(service.Metadata.Name)"></ServiceComponent>
                                   </BSTabContent>
                              </BSTab>
                         }
                  </BSTabList>
            }
        </div>
        <div class="col-md-9">
              <BSTabSelectedContent />
        </div>
    </BSTabGroup>
</div>
```
This works perfectly except that it doesn't update when the list is changed.  I manually call StateHasChange after any changes:

```
InvokeAsync(StateHasChanged);
```

If I remove a tab (item from ActiveServices), the tab disappears but the content remains, so all the other tabs are out of sync after that (all the tabs following the removed one display the wrong content).

I added an event hander to the ServiceComponent to see if it gets the changes and it fires every time:

```
 protected override async Task OnAfterRenderAsync(bool firstRender)
 {
        if (!string.IsNullOrEmpty(ServiceName))
            Logger.LogInformation($"Service Rendered: {ServiceName}");
 }
```

However, the content on the tab content remains unchanged.  

If I remove the tab list and have the items flow down the page, they're updated correctly when StateHasChanged is called.   How do I force this tab list/content to refresh correctly?

Thanks

**Comment by jbomhold3** [comment]
change <BSTab> to <BSTab @key="service"> so blazor tracks your foreach changes correctly.

**Comment by jbomhold3** [comment]
Better example:
``` HTML
<div class="row">
    <BSTabGroup @ref="TabGroup">
        <div class="col-md-3" style="padding-left: 0px">
            @lock (ActiveServices)
            {
                <BSTabList IsPills="true" IsList="true" IsVertical="true" >
                    @foreach (var service in ActiveServices)
                    {
                        <BSTab @key="service" @ref="service.Tab">
                            <BSTabLabel>@service.Name <a href="javascript:void(0);" @onclick="() => Remove(service.Name)">(X)</a></BSTabLabel>
                            <BSTabContent>
                                @service.Name
                            </BSTabContent>
                        </BSTab>
                    }
                </BSTabList>
            }
        </div>
        <div class="col-md-9">
            <BSTabSelectedContent />
        </div>
    </BSTabGroup>
</div>
```
``` C#
@code {
    IList<CustomService> ActiveServices { get; set; }
    BSTabGroup TabGroup { get; set; }
    protected override void OnInitialized()
    {
        ActiveServices = new List<CustomService>();
        ActiveServices.Add(new CustomService(){Name = "Bob"});
        ActiveServices.Add(new CustomService(){Name = "Frank"});
        ActiveServices.Add(new CustomService(){Name = "Jim"});
    }

    void Remove(string name)
    {
        var tab = ActiveServices.FirstOrDefault(q => q.Name == name);
        if (tab != null)
        { 
        ActiveServices.Remove(tab);
        if (TabGroup.Selected == tab.Tab)
            TabGroup.Selected = ActiveServices.First().Tab;
        }
    }

    void Add()
    {
        var name = Guid.NewGuid().ToString();
        ActiveServices.Add(new CustomService(){Name = name});
    }

    public class CustomService
    {
        public BSTab Tab { get; set; }   
        public string Name { get; set; }
    }
}
```

**Comment by scubakiz** [comment]
The Remove now works correctly and I can move to the first tab when another is deleted:
```
var firstTab = ServicesTabGroup.Tabs.FirstOrDefault();
if (firstTab != null)
{
    ServicesTabGroup.Selected = firstTab;
}
```

Thank you for that.

However, the update doesn't refresh if I'm on the tab when the update occurs.  If I go to another tab and come back, the changes are reflected correctly.  

What's I'm looking for is something like this to add to my Update event:
```
ServicesTabGroup.Selected.Content.Refresh();
```
Or trick Blazor into thinking the component needs to be re-rendered.

Can you please provide an Update example to your sample above?

Thanks

**Comment by jbomhold3** [comment]
The 2nd example does just that. I have a reference to bstab inside the model. then checking it to see if it's the selected tab with the reference to bstabgroup if it is it removes it then sets it to first. this will cause a state has changed for the entire tabgroup

**Comment by scubakiz** [comment]
Thank you!!  I don't have control of the model (external library), so modifying was not an option.  I tried created an inherited version, but the casting kept failing.  So I created a container instead:

```
 public class TabService
    {
        public TabService(Service innerService)
        {
            InnerService = innerService;
        }

        public Service InnerService { get; set; }
        public BSTab HostTab { get; set; }
    }
```
And loaded the container during the initial load:


Then the references work correctly:

```
<BSTabList IsPills="true" IsList="true" IsVertical="true">
      @foreach (var service in ActiveServices)
      {
          <BSTab @key="service" @ref="service.HostTab">
              <BSTabLabel>@service.InnerService.Metadata.Name</BSTabLabel>
              <BSTabContent>
                  <ServiceComponent CurrentService="@service.InnerService" ServicePods="@GetServicePods(service.InnerService.Metadata.Name)"></ServiceComponent>
              </BSTabContent>
          </BSTab>
      }
</BSTabList>
```

**Comment by jbomhold3** [comment]
Will leave this open. I do want to add first class support for dynamic tabs. Will work on it this week and try and get something out.

**Comment by scubakiz** [comment]
If you're going to native support, than here are few more details:

I implement a function that moves to different segments in my app which causes all the tabs to be removed and recreated with a new set.

1. I found that when I delete an item from the list, the Tab still remains.  It's not shown, but it still appears in a breakpoint.  I saw 50+ tabs after switching segments.  Had to add this to the Remove event to manually remove the tabs:
```
if (ServicesTabGroup != null)
{
     lock (ServicesTabGroup.Tabs)
     {
          ServicesTabGroup.Tabs.Remove(oldService.HostTab);
          if ((ServicesTabGroup.Selected == oldService.HostTab)
              || !ActiveServices.Select(x => x.HostTab?.Id).Contains(ServicesTabGroup.Selected?.Id))
          {
               ServicesTabGroup.Selected = ActiveServices.FirstOrDefault()?.HostTab;
          }
      }
}
```
2. This presented a situation where no tabs were selected after switching (and the old content remained).   It seems that TabGroup.Selected and the individual Selected properties of the tabs is out of sync.  Had to force the first one to be selected after refresh because setting TabGroup.Selected = tab doesn't work.
 
```
protected override void OnAfterRender(bool firstRender)
{
    if ((ServicesTabGroup != null)
         && ActiveServices.Any()
         && !ServicesTabGroup.Tabs.Select(x => x.Selected).Contains(true))
          {
                lock (ActiveServices)
                {
                    ActiveServices.FirstOrDefault().HostTab.Select();
                }
           }
}
```
This updated the content to the new tab.

If you can think of a better way to accomplish this, please let me know.

**Comment by jbomhold3** [comment]
Still working on this update just busy updating my own project at the moment. My design goal with the update is to only have to manage your list. That way you don't have to make BSTabs aware of your changes at all. This is working to a point. What i'm currently having issues with is figuring out track the selected tab properly. I'm probably making this harder on myself then needed. However, I feel it's important for BlazorStrap to do the leg work here so you can just focus on your code vs code around all the methods in the framework. We will see how this turns out I might end up.
