### ISSUE TITLE
Navbar dropdown hides behind other content in mobile

### ISSUE THREAD

**Issue by mkontula** [chanan/BlazorStrap#436]
Looking at blazorstrap.io demo site with current Chrome Version 89.0.4389.82 (Official Build) (32-bit) to me it seems dropdown menu is hiding behind other content when opened. Double-checked the behavior with my Samsung S10, and it's the same. 

![image](https://user-images.githubusercontent.com/1148526/110455664-5fe07d80-80d1-11eb-8ed2-46f08bcf0d6d.png)

Might this have something to do with header element overflow css settings when in mobile break-point?

**Comment by jbomhold3** [comment]
Was the navbar-nav-scroll class in the demo.css just removed it wasn't really needed
