### ISSUE TITLE
Consider Prefixing all Components

### ISSUE THREAD

**Issue by pjmagee** [chanan/BlazorStrap#44]
With a mixture of things popping up on Intellisense, and the possibility of namespace collision, would it be worth prefixing all components, or is there a way to do this with the tagHelper import?

**Comment by chucker** [comment]
FWIW:

> is there a way to do this with the tagHelper import?

As I understand it, the tagHelper approach [will go away](https://github.com/aspnet/AspNetCore/issues/5577) in the next Blazor release, and to your point, one of the ToDo items is:

>Components can bind with an alias `(using Foo = Bar)`

**Comment by chucker** [comment]
Relevant: https://github.com/aspnet/AspNetCore/issues/9860

**Comment by chanan** [comment]
Re Button versus button - that's the way it is in React. Also you can do the using Foo = Bar.

It would be awesome if Blazor had both those. That's why I am not doing anything on this issue yet, till we see where the chips fall. It looks like the issue you linked should fix some of this.

**Comment by chucker** [comment]
Steve just answered this.

So, IMHO, we should go forward with instead prefixing _none_ of the components and relying entirely on namespaces.

**Comment by chanan** [comment]
That's awesome! I was hoping for that solution - like React.

When its released, I will rename all components back to their "real" names.

**Comment by chanan** [comment]
Not 100% related by the syntax for a dictionary of attributes is going to change as well: https://github.com/aspnet/AspNetCore/issues/5071 So hopefully I can do both at the same time (That is internal to the library and shouldnt change the user facing API)

**Comment by thijstijsma** [comment]
> When its released, I will rename all components back to their "real" names.

Do you also mean that instead of this

```
<Card CardType="CardType.Card" />
    <Card CardType="CardType.Body">
        <Card CardType="CardType.Title">Card title</Card>
```

We will have this?

```
<Card />
    <CardBody>
        <CardTitle>Card title</CardTitle>
```

Or is there another reason for the first approach?

**Comment by chanan** [comment]
After more discussion, we decided to do this in the 1.0.0-preview7-01

**THIS WILL BE A BREAKING CHANGE**
