### ISSUE TITLE
Not seeing animation

### ISSUE THREAD

**Issue by rgamage** [chanan/BlazorStrap#440]
Sorry, new to this lib, so probably doing something wrong.  But I'm not seeing animation of the Collapse component, even on the demo page.

When I look at the Bootstrap site, here:
[https://getbootstrap.com/docs/4.0/components/collapse/](url)

I see the content below the collapse smoothly shift downward.  

When I look at the BlazorStrap demo site, here:
[https://blazorstrap.io/collapse](url)

I don't see that animation, it just abruptly inserts the content.

Am I missing something, or is this library supposed to support these smooth transitions?

Thanks,
Randy

**Comment by jbomhold3** [comment]
What browser are you using? Seeing all animations on that page work fine.
