### ISSUE TITLE
BSInput controls not working in Photino

### ISSUE THREAD

**Issue by matthewfitzmaurice** [chanan/BlazorStrap#446]
Not sure if i'm doing something wrong..
I have a small crud app that I built using Blazor Web Assembly and BlazorStrap - I'm currently moving it to run under https://www.tryphotino.io/.

I can't seem to get any of the BSInput controls to work.

The following code used to work:

    <BSFormGroup>
        <BSLabel For="@nameof(AppSettings.Name)">Name</BSLabel>
        <BSInput Id="@nameof(AppSettings.Name)" InputType="InputType.Text" PlaceHolder="Enter Name" Value="@AppSettings.Name" />
        <BSFormFeedback For="@(() => AppSettings.Name)" />
    </BSFormGroup>

Now I have to use the standard Input control:

    <BSFormGroup>
        <BSLabel For="@nameof(AppSettings.Name)">Name</BSLabel>
        <InputText id="@nameof(AppSettings.Name)" PlaceHolder="Enter Name" @bind-Value="AppSettings.Name" />
        <BSFormFeedback For="@(() => AppSettings.Name)" />
    </BSFormGroup>

**Comment by jbomhold3** [comment]
One of two things there wrapper isn't loading something we are depending on. IDK without diving into it. 
Or if your not using a model and BSForm. If thats the case you need to be using BSBasicInput.


" This project represents Blazor functionality on top of Photino.NET (**the .NET 5 wrapper** for the Photino.Native project), which makes it available for all operating systems (Windows, macOS, Linux). This library is used for the Blazor sample projects: https://github.com/tryphotino/photino.Samples

If you made changes to the Photino.Native or Photino.NET projects, or added new features to them, you will likely need this repo to expose the new functionality to the Photino.Blazor wrapper. In all other cases, you can just grab the nuget package for your projects: https://www.nuget.org/packages/Photino.Blazor"
