### ISSUE TITLE
Update to 3.0.0-preview4

### ISSUE THREAD

**Issue by Hawxy** [chanan/BlazorStrap#45]
Upgrade instructions [here](https://devblogs.microsoft.com/aspnet/blazor-now-in-official-preview/) and changelog [here](https://github.com/aspnet/aspnetcore/issues?q=is%3Aissue+milestone%3A3.0.0-preview4+label%3Afeature-components+label%3A%223+-+Done%22+label%3Abug)

Thanks for your work.

Edit: I went ahead and did it in #46

**Comment by chanan** [comment]
Thanks for the PR @Hawxy !
