### ISSUE TITLE
HiddenEvent of BSModal is not working

### ISSUE THREAD

**Issue by MuTsunTsai** [chanan/BlazorStrap#453]
`BSModal` class has this `HiddenEvent` property, which supposedly fires when the hiding animation is over. But I just noticed that this event is never triggered, and a quick search in the source code of this repo suggests that, in fact, `HiddenEvent` is never invoked anywhere in the source code. There used to be a line of code that invokes it, but it was removed in the commit on Sep 27, 2019. Please investigate this issue. Thanks.

**Comment by uecasm** [comment]
At least in the current version, it has `OnHidden`, which does work.

**Comment by jbomhold3** [comment]
V1 Use HideEvent
HiddenEvent/HideEvent in V1 did the same thing affectively with a timed delay. There isn't any javascript functions that hooked transition ends in V1. At best we delayed the HiddenEvent from firing until a reasonable time has passed when the animation "should" be complete on some components. Likely why the event ended up overlooked being fired.  

As noted by the respond above V5 does hook transition events in JavaScript and call back to Blazor then we Trigger onHidden as it should have been. I will say a lot of the core V1 features were constantly being reworked to react to changes from the previews and over all release during that time. But I can't speak to the exact reason we never did end up creating this logic in V1. I'm not sure it would be worth back porting the entire new event handling system just for HiddenEvent to function properly.  VS bringing Bootstrap 4 support into V5. Giving us a better foundation to react to new versions of Bootstrap.
