### ISSUE TITLE
Nullable Bool Checkbox raises an error.

### ISSUE THREAD

**Issue by arivera12** [chanan/BlazorStrap#456]
I am using latest version v1.5.1

![image](https://user-images.githubusercontent.com/5600102/123709263-c503de80-d83a-11eb-8a88-6a4759b22235.png)

Tiene ERX and IsOpen24Hours are nullable bool values and when is clicked then raises this error.

![image](https://user-images.githubusercontent.com/5600102/123709470-2035d100-d83b-11eb-97f4-767a0f94acb4.png)

I setup a default value to the checkbox and after that it works but when is null its throws this error.

**Comment by arivera12** [comment]
I forked the project and tried to fix myself but for some reason the value always stays false, not sure if I am missing something did someone had took a look already? This bug should be considered as high priority cause makes nullable bool unusable.

**Comment by arivera12** [comment]
Any news on this? Please I need this to support nullable bool.

**Comment by arivera12** [comment]
@chanan or @jbomhold3 please validate my PR I need this ASAP in a new nuget package version. Please help!

**Comment by jbomhold3** [comment]
Included in Preview-6

**Comment by arivera12** [comment]
Working as expected! Closing!
