### ISSUE TITLE
Dropdown doesn't disappear on click elsewhere

### ISSUE THREAD

**Issue by pelshen** [chanan/BlazorStrap#459]
I'm not sure when this has happened as #7 suggests it was working at some point, but now if you open a BSDropdown and then click away to lose focus the dropdown doesn't close. I tried to debug this but I couldn't get LostFocus() to trigger, so think this may be the issue, but I don't understand why this has stopped working - maybe this is because of a change in Blazor?

Using Esc does still work.

The samples reproduce this issue (all of them), as does the simplest use of the dropdown, eg 

```
<BSDropdown>
    <BSDropdownToggle>Click here</BSDropdownToggle>
    <BSDropdownMenu>
        <BSDropdownItem>Item 1</BSDropdownItem>
    </BSDropdownMenu>
</BSDropdown>
```

**Comment by jbomhold3** [comment]
wrap the above in <BSButtonGroup>

**Comment by pelshen** [comment]
Not sure why but in the above comment, the full text is not displayed. It should say wrap the above in `BSButtonGroup`, which does fix the issue, though I'm not sure why and this isn't well documented.

**Comment by jbomhold3** [comment]
because my goofballness forgot to add markup tags
