### ISSUE TITLE
Navbar is responding slowly

### ISSUE THREAD

**Issue by sahzudin** [chanan/BlazorStrap#460]
Navbar component responds slowly on click, hover, input selection, etc. Simply said, it's unusually laggy. I have tried it with some custom code. Also, I copy-pasted an example code from the demo site and there are issues with the example code too. 
I have checked [this issue](https://github.com/chanan/BlazorStrap/issues/14), but any of the solutions doesn't work for me. 

![image](https://user-images.githubusercontent.com/41241940/129099218-5151f793-94d6-4d79-b615-694dbdbff9e9.png)

**Comment by jbomhold3** [comment]
Can you provide an example project with the described behavior?

**Comment by sahzudin** [comment]
The whole project, or just a razor component where I used Navbar?

**Comment by jbomhold3** [comment]
My first thoughts on whats your experiencing is the number of times the view is redrawing. If you can reproduce the behavior in a new project would be  great. I don't think one component is causing it by its self. I think its how your handle state changes as a whole. But we can start with the component the navbar is housed in.

**Comment by sahzudin** [comment]
I created a new project and I just copy-paste Navbar component code in Index.razor 
Here is the example project. Maybe I am doing something wrong, I am new to blazor. 
[blazor-navbar.zip](https://github.com/chanan/BlazorStrap/files/6977133/blazor-navbar.zip)
