### ISSUE TITLE
Typo on BSCollapseToggle Component

### ISSUE THREAD

**Issue by chanandrew96** [chanan/BlazorStrap#461]
On line 16-17, both HiddenClass and ShownClass will be added when card open, should the HiddenClass added only when Card Closed?

` .AddClass(HiddenClass ?? "", CollapseItem?.Collapse?.IsOpen ?? false && HiddenClass != null)  `
` .AddClass(ShownClass ?? "", CollapseItem?.Collapse?.IsOpen ?? false && ShownClass != null) `

**Comment by jbomhold3** [comment]
it's a typo fixed in next push

**Comment by jbomhold3** [comment]
will be fixed when rc2 comes out and I can pack a project again....

**Comment by jbomhold3** [comment]
Fixed in current release
