### ISSUE TITLE
BSTooltip throwing JSException on page load?

### ISSUE THREAD

**Issue by Freshmintyy** [chanan/BlazorStrap#463]
I think there is an issue where the BSTooltip causes a JSException, it's a weird one though because after I reload the page a few times it doesn't error anymore. Attached is the screenshot of the error:

![image](https://user-images.githubusercontent.com/4752086/135534262-ba856781-ce4e-4bda-9c55-66ed1b26a05c.png)

Any ideas?

**Comment by jbomhold3** [comment]
I completely reworked the Javascript handling for popovers and tooltips in the least release. This should solve all issues with tooltips and popovers. I know this is a very last reply but if your still able to test the new release please do so and let me know if your issues are solved.
