### ISSUE TITLE
Package Changes

### ISSUE THREAD

**Issue by jbomhold3** [chanan/BlazorStrap#469]
V1x Targets ```Bootstrap 4``` if your using ```Bootstrap 4``` **do not** upgrade to the V5x series
 V5x Targets ```Bootstrap 5``` use this package is your using ```Bootstrap 5```.

> If you use V5.x in a existing V1.x project you will get a ton of compile errors. Just change your package version back to a 1x package.

**Comment by CatalinAdlerDF** [comment]
I actually upgraded an existing v1 to v5 and did make lots of changes to various components.
But i am now facing a funky problem: the `blazorStrap.js` file is overridden in prod by the `_Host.cshtml` content, so no client-side scripts work.

Any clues?
