### ISSUE TITLE
Installing 1.0.0-preview4 shows internal .razor files

### ISSUE THREAD

**Issue by IvanJosipovic** [chanan/BlazorStrap#47]
After installing BlazorStrap 1.0.0-preview4, I can see every BlazorStrap component in my projet.

![image](https://user-images.githubusercontent.com/9521987/56518564-a5ebc280-64f4-11e9-9199-0b0e2380a0ec.png)

Repro Steps

1. Create a new Blazor Client Side App

1. Install BlazorStrap 1.0.0-preview4

**Comment by chanan** [comment]
I noticed that as well, I have no idea why that is yet

**Comment by chanan** [comment]
Open an issue in the Aspnet repo: https://github.com/aspnet/AspNetCore/issues/9650

**Comment by chanan** [comment]
A workaround is detailed here: https://github.com/aspnet/AspNetCore/issues/9577
