### ISSUE TITLE
BSDataTable doesn't pass Class to underlying BSTable

### ISSUE THREAD

**Issue by pelshen** [chanan/BlazorStrap#473]
BSDataTable exposes a Class parameter, but this isn't passed down to the BSTable so the class is never added to the eventual `<table>` element. I think this just requires a `Class="@Class"` in BSDataTable.razor to fix.

**Comment by jbomhold3** [comment]
Your right and will fix and will add the missing additional attributes to it as well. Then get it pushed out tonight.

**Comment by jbomhold3** [comment]
https://www.nuget.org/packages/BlazorStrap.Extensions.BSDataTable/1.5.1
