### ISSUE TITLE
Modal ".Show()" and ".Hide()" function missing in BlazorStrap 5

### ISSUE THREAD

**Issue by NewNekoy** [chanan/BlazorStrap#477]
Hello, a very useful function is no longer present in the new version of BlazorStrap. Is there an alternate version, or does it not exist at all?
And if not, will it be re-added over time?

**Comment by jbomhold3** [comment]
.ShowAsync() / .HideAsync still exist

**Comment by jbomhold3** [comment]
To go into more detail. Ensuring the transition starts is the limiting factor to why there is no Sync method for it. There is a micro delay given when toggling a modals,collapse, carousel, ext..  to see if the transition starts or not. To tell if the computer is capable of animations. Regardless it hits a InvokeAsync(StateHasChanged) at the end. So it "should" be safe to fire and forget, use Task.Run, or use any other method of invoking a async call over sync. That's if you really need to do the call in a sync operation. Let me know if you run into a use case where this simply will not work for you.
