### ISSUE TITLE
V 1.5.1 BSTabcontent Not rendering anything

### ISSUE THREAD

**Issue by draco1986** [chanan/BlazorStrap#478]
Hello,
I've been trying to set up a new Blazor project and cannot seem to find the correct answer.  No matter what I put into the Tabcontent on the tab group it renders as blank.  Latest I tried was the example code, but still nothing.  Tabs all show up and events inside Show, Shown Hide Hidden all work.  We have another project that is using Tabs with no issue.  Followed all the set instructions for this second project as well.

```
@using System.Diagnostics;
@using MatBlazor;
@using BlazorProject1;
@using BlazorStrap;
@using BlazorDateRangePicker;

@page  "/Subscribing"




<h3>Subscribing</h3>
<br />
<label>Hello @Common.username3</label>



<BSTabGroup ShowEvent="@Show" HiddenEvent="@Hidden" HideEvent="@Hide" ShownEvent="@Shown">
    <BSTabList>
        <BSTab>
            <BSTabLabel>Home</BSTabLabel>
            <BSTabContent>Et et consectetur ipsum labore excepteur est proident excepteur ad velit occaecat qui minim occaecat veniam. Fugiat veniam incididunt anim aliqua enim pariatur veniam sunt est aute sit dolor anim. Velit non irure adipisicing aliqua ullamco irure incididunt irure non esse consectetur nostrud minim non minim occaecat. Amet duis do nisi duis veniam non est eiusmod tempor incididunt tempor dolor ipsum in qui sit. Exercitation mollit sit culpa nisi culpa non adipisicing reprehenderit do dolore. Duis reprehenderit occaecat anim ullamco ad duis occaecat ex.</BSTabContent>
        </BSTab>
        <BSTab>
            <BSTabLabel>Profile</BSTabLabel>
            <BSTabContent>Nulla est ullamco ut irure incididunt nulla Lorem Lorem minim irure officia enim reprehenderit. Magna duis labore cillum sint adipisicing exercitation ipsum. Nostrud ut anim non exercitation velit laboris fugiat cupidatat. Commodo esse dolore fugiat sint velit ullamco magna consequat voluptate minim amet aliquip ipsum aute laboris nisi. Labore labore veniam irure irure ipsum pariatur mollit magna in cupidatat dolore magna irure esse tempor ad mollit. Dolore commodo nulla minim amet ipsum officia consectetur amet ullamco voluptate nisi commodo ea sit eu.</BSTabContent>
        </BSTab>
        <BSTab>
            <BSTabLabel IsDisabled="true">Contact</BSTabLabel>
            <BSTabContent>Sint sit mollit irure quis est nostrud cillum consequat Lorem esse do quis dolor esse fugiat sunt do. Eu ex commodo veniam Lorem aliquip laborum occaecat qui Lorem esse mollit dolore anim cupidatat. Deserunt officia id Lorem nostrud aute id commodo elit eiusmod enim irure amet eiusmod qui reprehenderit nostrud tempor. Fugiat ipsum excepteur in aliqua non et quis aliquip ad irure in labore cillum elit enim. Consequat aliquip incididunt ipsum et minim laborum laborum laborum et cillum labore. Deserunt adipisicing cillum id nulla minim nostrud labore eiusmod et amet. Laboris consequat consequat commodo non ut non aliquip reprehenderit nulla anim occaecat. Sunt sit ullamco reprehenderit irure ea ullamco Lorem aute nostrud magna.</BSTabContent>
        </BSTab>
    </BSTabList>
    
</BSTabGroup>
```

@code {
    
    IList<Employee> EmpList = new List<Employee>();
    public Employee employee = new Employee();

    private void Show(BSTabEvent e)
    {
        Console.WriteLine($"Show   -> Activated: {e.Activated?.Id.ToString()} , Deactivated: {e.Deactivated?.Id.ToString()}");
    }
    private void Shown(BSTabEvent e)
    {
        Console.WriteLine($"Shown  -> Activated: {e.Activated?.Id.ToString()} , Deactivated: {e.Deactivated?.Id.ToString()}");
      // EmpList = SubscribingMethods.GetEmps(SelectedEmployee.login);  Removed for testing of tabcontent
    }
    private void Hide(BSTabEvent e)
    {
        Console.WriteLine($"Hide   ->  Activated: {e.Activated?.Id.ToString()} , Deactivated: {e.Deactivated?.Id.ToString()}");
    }
    private void Hidden(BSTabEvent e)
    {
        Console.WriteLine($"Hidden -> Activated: {e.Activated?.Id.ToString()} , Deactivated: {e.Deactivated?.Id.ToString()}");
    }

  
    protected override void OnInitialized()
    {

        

       
    }

    

}

**Comment by jbomhold3** [comment]
In V1 add  <BSTabSelectedContent/> to your TabGroup that is the component that renders the selected tab
