### ISSUE TITLE
ColumnMedium of BSCol does not shown in rendered html

### ISSUE THREAD

**Issue by Jtfk** [chanan/BlazorStrap#479]
**Version:** 5.0.101

Hello, I'm having an issue for displaying the width for `BSCol` using the `ColumnMedium` parameter. Below is the sample.
```razor
<div class="border border-dark w-50">
    <BSCol ColumnMedium="5" Class="border badge-danger">
        <span>Test</span>
    </BSCol>
</div>
```
**After Blazor rendering**: the `col-md-*` does not shown as expected.
```html
<div class="border border-dark w-50">
    <!--!-->
    <div class="border badge-danger">
        <!--!-->
        <span>Test</span>
    </div>
</div>
```

#### **Possible cause** 
`ColumnSmall` is used to validate for adding `col-md-*`, instead of `ColumnMedium`.
https://github.com/chanan/BlazorStrap/blob/c2cb50981f38cb96ca73a8c4267e96a757c5c718/src/BlazorStrap/Components/Layout/BSCol.razor.cs#L34

**Edit:** `BSLabel` has the same issue

**Comment by jbomhold3** [comment]
Woot faulty human error. Thanks will get it fixed. To workaround it for the moment just drop col-md-5 into the Class

**Comment by jbomhold3** [comment]
Fixed in https://www.nuget.org/packages/BlazorStrap/5.0.102
