### ISSUE TITLE
Migration to v5 and issue with tabs

### ISSUE THREAD

**Issue by stiankroknes** [chanan/BlazorStrap#480]
Hi,

Have issue figuring out how to use tabs in v5. Is this supposed to work?

```html
<BSNav IsTabs="true">
	<BSNavItem>
		<TabLabel>Test</TabLabel>
		<TabContent><p>test</p></TabContent>
	</BSNavItem>

	<BSNavItem>
		<TabLabel>Test2</TabLabel>
		<TabContent><p>test2</p></TabContent>
	</BSNavItem>

	<BSNavItem>
		<TabLabel>Test3</TabLabel>
		<TabContent><p>test3</p></TabContent>
	</BSNavItem>
</BSNav>
```
The tabs is rendered but only content for the first Test tab is shown. Tab Test2 and Test3 does not respond to click (not clickable).

**Comment by jbomhold3** [comment]
Fixed in https://www.nuget.org/packages/BlazorStrap/5.0.102

**Comment by stiankroknes** [comment]
Can confirm the fix worked. Thanks! 😄

**Comment by stiankroknes** [comment]
Closed
