### ISSUE TITLE
V5 BSInput 'InputType.Number' unable to get nullable int value

### ISSUE THREAD

**Issue by Jtfk** [chanan/BlazorStrap#483]
**Version:** 5.0.103

When BSInput `InputType.Number` binds with a nullable int, the bind value is not updated when input is changed.
```razor
<p>Integer received: @nullableInt</p>
<BSInput InputType="InputType.Number" @bind-Value="nullableInt"></BSInput>

@code
{
    private int? nullableInt;
}
```

**Possible cause**

In line 151 of `TryParseString`, The `int?` conversion resets the updated value to the default type value.
https://github.com/chanan/BlazorStrap/blob/bda1ec9e9c1b0d83e89ec15778f90f42dd8c38f8/src/BlazorStrap/Utilities/TryParseString.cs#L143-L154

**Comment by jbomhold3** [comment]
hum that code is directly from 1.0. There was probably a reason at the time why we didn't support it but will take a look but its been ages. Will do some testing to make sure its safe and get it added in.

**Comment by jbomhold3** [comment]
This work fine now in https://www.nuget.org/packages/BlazorStrap/5.0.104

**Comment by Jtfk** [comment]
Thanks, confirmed it is fixed.
