### ISSUE TITLE
Dynamic class arguments are ignored

### ISSUE THREAD

**Issue by NichUK** [chanan/BlazorStrap#484]
If an element uses a dynamically created class string, BlazorStrap seems to overwrite it.

`<BSCol Column="2" class="@MyDynamicClassFunction()"></BSCol>`

is rendered as

`<div class="col-2"></div>`

The results from MyDynamicClassFunction are ignored or overwritten.

**Comment by jbomhold3** [comment]
Class not class

**Comment by jbomhold3** [comment]
Two weeks no response closing issue
