### ISSUE TITLE
 Unable to resolve service for type 'System.Net.Http.HttpClient'

### ISSUE THREAD

**Issue by SandroRiz** [chanan/BlazorStrap#486]
Adding the middleware in a blazor server side .net 6 project (program.cs)

builder.Services.AddBlazorStrap();

it crashes with this error

Unhandled exception. System.AggregateException: Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: BlazorStrap.Utilities.ISvgLoader Lifetime: Scoped ImplementationType: BlazorStrap.Utilities.SvgLoader': Unable to resolve service for type 'System.Net.Http.HttpClient' while attempting to activate 'BlazorStrap.Utilities.SvgLoader'.)

**Comment by jbomhold3** [comment]
details please. What version of Blazorstrap? What version of dotnet? Blazor Server side of WASM?

**Comment by jbomhold3** [comment]
~~~ C# 
// Server Side Blazor doesn't register HttpClient by default
if (!builder.Services.Any(x => x.ServiceType == typeof(HttpClient)))
{
    // Setup HttpClient for server side in a client side compatible fashion
    builder.Services.AddScoped<HttpClient>(s =>
    {
        // Creating the URI helper needs to wait until the JS Runtime is initialized, so defer it.
        NavigationManager navman = s.GetRequiredService<NavigationManager>();
        return new HttpClient
        {
            BaseAddress = new Uri(navman.BaseUri )
        };
    });
}
~~~

**Comment by wtfacoconut** [comment]
I too am experiencing this issue and it looks like others are as well on StackOverflow ([link](https://stackoverflow.com/questions/71303529/blazorstrap-not-working-for-net-6-blazor)).

Thanks @jbomhold3 , your workaround works for me as well.

**Comment by jbomhold3** [comment]
Thanks for letting me know I don't watch StackOverflow normally but replied to it.

**Comment by jbomhold3** [comment]
Change added in preview 3 to address this. Will not just create a new instance of httpclient if the service isn't there in a using statement. If you need preset headers IG auth, you will need to inject the service yourself seeing workaround above.
