### ISSUE TITLE
Support table row templates for datatables

### ISSUE THREAD

**Issue by zandermar18** [chanan/BlazorStrap#490]
It would be sweet to add a data table row as a component so rows of a data table can be conditionally formatted. Something like:

`<BSDataTableRow>
    <BSTD></BSTD>
</BsDataTableRow`

Happy to take a crack at it and submit a PR.

**Comment by jbomhold3** [comment]
Not fully following what exactly the request is sorry. Please do submit the PR might be easier to get an idea of the goal.
