### ISSUE TITLE
Make 'NextAsync' & 'BackAsync' on BSCarousel public

### ISSUE THREAD

**Issue by Freshmintyy** [chanan/BlazorStrap#491]
Hi there, I'm needing the Next and Back methods to be publicly visible so I can control when they go forward or back. This used to be functional in the previous blazor strap so please include it in latest.

**Comment by jbomhold3** [comment]
Done think refactoring got that one wasn't intended to be internal 
Unlisted patch version for you to use now.
https://www.nuget.org/packages/BlazorStrap/5.0.105-Preview1b

**Comment by Freshmintyy** [comment]
Any chance you can do the same in v4 too please? Haven't got round to transferring over to v5 as of yet but updated to the latest and it seems it has the same problem.

Cheers

**Comment by jbomhold3** [comment]
V1 is already in there its  GoToNextItem() / GoToPrevItem() 
So you know  V1=Bootstrap 4 V5=Bootstrap 5

**Comment by jbomhold3** [comment]
You using a very old version should be safe to upgrade to [the 1.5.102-Preview2 ](https://www.nuget.org/packages/BlazorStrap/1.5.102-Preview2)
