### ISSUE TITLE
BSDataTable example not working: The name 'item' does not exist in the current context

### ISSUE THREAD

**Issue by barruka** [chanan/BlazorStrap#492]
I am not able to make BSDataTable work with the doc provided in /V5/content/tables.
(I am using net 6)

I think that the documentation needs to add:
```@using BlazorStrap.Extensions.BSDataTable```

And then in the BSDataTable we have to add:
```TItem="Employ"```

Even though, when building got the error:
```The name 'item' does not exist in the current context```

**Comment by jbomhold3** [comment]
BlazorStrap.Extensions.BSDataTable  is a V1 Extension.
 [5.0.105-Preview1](https://www.nuget.org/packages/BlazorStrap/5.0.105-Preview1) has a preview of the new BSDataTable it's in the core program now.

See https://blazorstrap.io/V5/content/tables for example

**Comment by jbomhold3** [comment]
Version requirement is now reflected in the Docs for that feature
