### ISSUE TITLE
BSToolTip Bug

### ISSUE THREAD

**Issue by MasterSkriptor** [chanan/BlazorStrap#494]
BSToolTip freezes the UI after it shows a tool tip. This stops the buttons from firing click events.

This was the setup I had when I ran into this bug.

```
<BSButton DataId="deactivateCustomer" Size="Size.ExtraSmall" Color="BSColor.Light" OnClick="Customer_Deactivate" 
                   IsDisabled="@(Customer.Status == "Inactive")">
           <span class="oi oi-trash text-danger"></span>
</BSButton>
<BSTooltip Target="deactivateCustomer" Placement="Placement.Top">Deactivate Customer</BSTooltip>
```

If I get a chance I will look into fixing this, but I am pretty busy these days.

BTW, BlazorStrap 5 is looking great!

**Comment by zandermar18** [comment]
Taking a look at this one

**Comment by zandermar18** [comment]
Hey @MasterSkriptor, I was unable to reproduce this bug. See [my fork](https://github.com/zandermar18/BlazorStrap/blob/BSTooltip-ui-freeze-bug/src/BlazorStrap-Docs/Samples/Components/Tooltips/TooltipTroubleshooting.razor) for the reproduction attempt and let me know if I'm missing anything here.
