### ISSUE TITLE
Bootstrap coupled or Material-Design possible?

### ISSUE THREAD

**Issue by PtwHub** [chanan/BlazorStrap#5]
Hi Chanan. Nice! I'm assuming, due to the name, that this is not reasonably usable/adaptable with a  Material-Design style basis? Sure, one can hack a Material-Design style on top of Bootstrap, but not really a good idea. We use MD in other contexts and, as such, can't readily go with Bootstrap. ... any thoughts appreciated!

**Comment by chanan** [comment]
BlazorStrap is indeed for bootstrap4. I saw this library is also being created for material design: https://github.com/BlazorExtensions/BlazorMaterial

Another option is using Blazorous to create what ever components you want: https://github.com/chanan/Blazorous
