### ISSUE TITLE
BSModal using as a Progress Screen

### ISSUE THREAD

**Issue by CliveBennett** [chanan/BlazorStrap#507]
In BS1, I used to use a BSModal as a Psuedo progress window, a payload was submitted to the API, and Blazor would poll for the response and display progress messages onscreen, which all worked fine

I migrated this to BS5, and the Show and Hide are now ShowAsync and HideAsync.

Issue 1) I had a string that I would update while polling the API for a response , in BS1 changing the string would update the BSModal, in BS5, the Modal doesnt get updated UNLESS I HideAsync() then ShowAsync(), which obviously causes the Modal to flash opening and closing all the time.

Issue 2) If you do a HideAsync or a ShowAsync when the Modal is Already showing, or Already hidden, it leaves the Screen in a odd state where it appears to have frozen, but when I inspect with Chrome, it shows there is an invisible Modal layer left over the screen, although nothing visible onScreen

```
<div class="modal fade" tabindex="-1" style="display: block;" data-blazorstrap="976f1f84-82a3-4cee-8f4c-20540b8556cc" _bl_190=""><div class="modal-dialog modal-dialog-centered  modal-dialog-centered"><div class="modal-content"><div class="modal-header"><!--!-->
                        <button type="button" class="ms-auto btn-close " data-bs-dismiss="modal" aria-label="Close"></button></div><div class="modal-body"><div>Generating Question flow for A1019 Benefit EMC</div></div><!--!-->
                <div class="modal-footer"></div></div></div></div>
```

, I couldnt see a property in BSModal that lets me see if its already open/closed, so implemented below and added OnShow and OnHide events  which works okish. On occasion though it sometimes still leaves the screen Frozen. 

It could be that Modals are the wrong thing for this now?.  but I cant see how else to display a Popup progress screen, that displays while a background process is occurring.

```
 private bool showing = false;
    private async Task Hide()
    {
        if (showing)  {
            await WaitPopup.HideAsync();
        }

    }
    private async Task Show()
    {
        if (!showing)  {
            await WaitPopup.ShowAsync();
        }
    }

    private void WaitPopupShow(BSModal modal)
    {
        showing = true;
    }
    private void WaitPopupHide(BSModal modal)
    {
        showing = false;
    }
```

**Comment by jbomhold3** [comment]
Issue 1) Sounds like a refresh function would fix that issue for you. Can easily be added and will be in the next preview.
Issue 2) 105.preview4

**Comment by CliveBennett** [comment]
Great thanks.

**Comment by jbomhold3** [comment]
Need an example of issue one. What I thought you were talking about works just fine.

**Comment by CliveBennett** [comment]
Hi John, this is pretty much what I'm doing, and replicates the issue.

[BlazorApp6.zip](https://github.com/chanan/BlazorStrap/files/8500460/BlazorApp6.zip)

**Comment by jbomhold3** [comment]
Added RefreshAsync to toggle base. Fixes that issue

**Comment by jbomhold3** [comment]
Added support in [5.0.105](https://www.nuget.org/packages/BlazorStrap/5.0.105)

**Comment by CliveBennett** [comment]
Thanks works well. cheers for adding it.
