### ISSUE TITLE
Nested Accordion Issue

### ISSUE THREAD

**Issue by steviev93** [chanan/BlazorStrap#509]
I'm using BlazorStrap V5.0.105 with a .NET MAUI Blazor project. When using the DefaultShow="false" attribute for the BSAccordionItem, all items show up as closed. However, when I open up that accordion item, if I attempt to open any nested accordions, it closes the parent accordion. This only happens when that attribute is set, otherwise, I'm able to interact with child accordions without triggering the parent. Below is my code:
```
<BSAccordion IsFlushed="true">
<BSAccordionItem DefaultShown="false">
	<Header>Editors</Header>
	<Content>
			<NavLink class="nav-link" href="fetchdata">
				Accounts
			</NavLink>
			<NavLink class="nav-link" href="fetchdata">
				Projects
			</NavLink>
			<NavLink class="nav-link" href="fetchdata">
				Cash Drawers
			</NavLink>
			<BSAccordion id="2">
				<BSAccordionItem>
					<Header>Vehicles</Header>
					<Content>
						<NavLink class="nav-link" href="fetchdata">
							Groups
						</NavLink>
						<NavLink class="nav-link" href="fetchdata">
							Types
						</NavLink>
						<NavLink class="nav-link" href="fetchdata">
							Transport Zones
						</NavLink>
						<NavLink class="nav-link" href="fetchdata">
							Transport Routes
						</NavLink>
						<NavLink class="nav-link" href="fetchdata">
							Purchased Vehicles
						</NavLink>
					</Content>
				</BSAccordionItem>
			</BSAccordion>
		
			<BSAccordion>
				<BSAccordionItem>
					<Header>Products</Header>
					<Content>
						<NavLink class="nav-link" href="fetchdata">
							Groups
						</NavLink>
						<NavLink class="nav-link" href="fetchdata">
							Types
						</NavLink>
						<NavLink class="nav-link" href="fetchdata">
							Limits
						</NavLink>
					</Content>
				</BSAccordionItem>
			</BSAccordion>
			<NavLink class="nav-link" href="fetchdata">
				Cards
			</NavLink>
			<NavLink class="nav-link" href="fetchdata">
				Inventory/Storages
			</NavLink>
			<NavLink class="nav-link" href="fetchdata">
				Invoicing
			</NavLink>
			<NavLink class="nav-link" href="fetchdata">
				Payments
			</NavLink>
			<NavLink class="nav-link" href="fetchdata">
				Price Lists
			</NavLink>
			<NavLink class="nav-link" href="fetchdata">
				Companies/Departments
			</NavLink>
			<NavLink class="nav-link" href="fetchdata">
				Custom Fields
			</NavLink>

		
	      </Content>
      </BSAccordionItem>
</BSAccordion>
```

**Comment by jbomhold3** [comment]
Will test this tonight I think I might already know what the issue is so fix will be out rather quickly

**Comment by uecasm** [comment]
I'm having a similar issue except the other way around -- I have `AlwaysOpen="true" DefaultShown="true"` and the items start open as expected, but when I close any of them they will automatically re-open.

I haven't confirmed, but I suspect what's happening is that something is triggering a re-render of the content, and Blazor is reapplying the default styles, because it is unaware of any changes done by JS Interop.  (And the Blazor docs strictly forbid using JS interop to add/remove classes or styles on any elements that contain Blazor subcomponents -- you're only allowed to do it on initially empty elements.)

**Comment by uecasm** [comment]
... although actually, looking more closely (and verified locally), I think the bug is just that the setter for `DefaultShown` also sets `Shown`, which is incorrect.  Though the JS interop thing still worries me.

**Comment by jbomhold3** [comment]
Hopefully putting the JS comment to bed. The only possible controlled desync that can happen is during animations. The lock on ShouldRender prevents the component from rerendering while the animations are running. Again this is the **only** time the component and the dom are in (a very aware and very controlled) desynced state with Blazor. If a class is added/removed or style via JavaScript it's readded or discarded if not need in Blazor during the. 

Blazor is completely responsible for tracking states of any of the components, not JavaScript. Should the component happen to be rerendered it's going to show it's self according the state tracked by Blazor. Your going to get reposition actions from this. A jump in the animation to the completed state. The transition end not being called so Shown/Hidden wouldn't be triggered. I am well aware of the warning. 

Components that depend on changes that happen from JavaScript, Ask for them back or rebuild them in Blazor according to the style. See BSModel styles. This is part of the reason this version of library runs on Boxes with animations disabled with the same final result as computers with animations on. We don't depend on anything JavaScript is doing with our classes/styles. 

All of this is done to prevent unneeded rerenders on the component. How animations would work in a sololy Blazor Call. in this example Set Style-> StateHasChanged -> Set Class -> StateHasChanged -> remove style StateHasChanged. That's two completely pointless refresh calls .

**Comment by jbomhold3** [comment]
[2458b48](https://github.com/chanan/BlazorStrap/commit/2458b48d220b79b9a89c829390a6cf9f2b900697) & [23fd28e](https://github.com/chanan/BlazorStrap/commit/23fd28ea4cd71945cd310c171f29152ffa75273d)
Should addresses any potential stuck state from parent changes. Discarding animations if the parent closes

**Comment by jbomhold3** [comment]
https://www.nuget.org/packages/BlazorStrap/5.0.105.4222022 Patched release
