### ISSUE TITLE
Responsive tables

### ISSUE THREAD

**Issue by uecasm** [chanan/BlazorStrap#513]
Currently, `<BSTable IsResponsive="true">` will add the `table-responsive` style directly on the `<table>` element.

This does not work; according to the [Bootstrap docs](https://getbootstrap.com/docs/5.0/content/tables/#responsive-tables), the style needs to be applied to the containing element instead (typically an extra wrapper div).

I think probably the best solution for this might be to just remove this parameter from BSTable entirely (such that people need to add the wrapping div themselves if they want this style).  Trying to include the wrapping div inside the component will lead to an ambiguity about where to place Classes and other attributes.  But I'm not sure, hence this is not a PR. 😄

**Comment by jbomhold3** [comment]
it's easy enough to do the wrapper and we can supply a class along with it so they can change it in css if they need to make a change at that level

**Comment by uecasm** [comment]
[5141b0b](https://github.com/chanan/BlazorStrap/commit/5141b0b691fc198a5ea3e52c091b2c7f3f69dbc9) doesn't have a `ResponsiveWrapperClass` or similar parameter...

**Comment by jbomhold3** [comment]
Wasn't going to add it why the bs-table-responsive was there to have something to target in css. But can see the value all the same it's added.

**Comment by uecasm** [comment]
Yeah, the point is to be able to add some of the Bootstrap utility styles (and in some cases the layout styles would need to be applied to the wrapper instead -- but not always), rather than just targeting custom CSS.

And AFAIK there isn't any easy way in CSS to say "apply styles to the parent of a child that has this class" -- at least not until [`:has(...)`](https://caniuse.com/?search=%3Ahas) actually gets implemented; you can only work from the outside down.
