### ISSUE TITLE
BSNav IsTabs=True in BS5, the active border doesn't render after first click

### ISSUE THREAD

**Issue by CliveBennett** [chanan/BlazorStrap#515]
Hi.
For BSNav IsTabs=True, its hard to see what the currently selected Tab is. I see the same behaviour in the BS Demo site

From demo site, when page loads, the selected Tab has a border to appear selected.
![image](https://user-images.githubusercontent.com/29695733/166853081-17149c84-9ec3-4d75-8b54-e3f42bd431f3.png)

If I click another tab, then click away, the border of the selected tab disappears 
![image](https://user-images.githubusercontent.com/29695733/166853142-13703de8-c414-4211-868f-b0ff9938801c.png)

**Comment by jbomhold3** [comment]
Ahh active isn't being set when you click easy fix on it.

**Comment by jbomhold3** [comment]
Hate the auto closing. This is fixed it sources and will reflect the changes in next beta/preview release

**Comment by CliveBennett** [comment]
Awesome thanks very much.
