### ISSUE TITLE
Add XML comments to public classes, properties, and methods for documentation

### ISSUE THREAD

**Issue by zandermar18** [chanan/BlazorStrap#517]
XML summary comments should be added to all public classes, properties, and methods to document what they do. It can slow down development having to look between the website and visual studio to determine what certain properties do. I can cut a branch and knock this out if you agree it is value added.

**Comment by jbomhold3** [comment]
Yeah, let's do it. Thanks!

**Comment by zandermar18** [comment]
#518 PR created, ready for review
