### ISSUE TITLE
popper.min.js 404 at runtime

### ISSUE THREAD

**Issue by CliveBennett** [chanan/BlazorStrap#519]
Hi, I get this error in the Browser console at runtime

Could not load content for https://###.com/_content/BlazorStrap/popper.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

I have the below in my index.html body tag. which is presumably where this 404 is coming from, 
Everything seems to work fine though

```
<script src="_content/BlazorStrap/popper.min.js"></script>
```

**Comment by jbomhold3** [comment]
can safely ignore the map file message it's not included in the package. Just a debug thing. What version are you working with 1.0 or 5 so I can remove the reference to it?

**Comment by CliveBennett** [comment]
Thanks, im using V5

**Comment by JosephAspey** [comment]
I'm seeing this issue, is there a fix?

**Comment by jbomhold3** [comment]
Still can safely ignore it, or if it really bugs you, use the CDN for the moment. https://unpkg.com/@popperjs/core@2.9.2/dist/umd/popper.min.js I removed the map from the script file, but it won't be in until the next release. 

This would cause the "program has exited with code 4294967295 (0xffffffff)"  part however.
