### ISSUE TITLE
Toaster Timer Throws Exception on Blazor Server

### ISSUE THREAD

**Issue by zandermar18** [chanan/BlazorStrap#520]
When multiple toasts with timers are added to the toaster and at least one (but not all) are dismissed manually before the timeout occurs, an exception is sometimes thrown. 

Sometimes an Enumerable out of range exception is thrown at [Toaster.cs:71](https://github.com/chanan/BlazorStrap/blob/3af6c3dcdddd32db95dd81c301fa7409b8bb68fd/src/BlazorStrap/Service/Toaster.cs#L74)

Sometimes a JSInterop exception is thrown at [BSToast.cs:137](https://github.com/chanan/BlazorStrap/blob/3af6c3dcdddd32db95dd81c301fa7409b8bb68fd/src/BlazorStrap/Components/BootstrapComponents/BSToast.razor.cs#L137)

It seems to be a transient error and is semi-reproducable. My guess is that the there is a thread concurrency issue going on here. It also appears to only be an issue on Blazor Server and not WASM, further implying it's a thread concurrency issue as WASM is single threaded. However since the root cause is unknown, it can't be ruled out that the issue also occurs on WASM.

**Comment by jbomhold3** [comment]
This is a Quick fix for the issue. Might visit later on .

**Comment by zandermar18** [comment]
Thanks for the quick fix, left a comment on the commit about one of the try blocks!

**Comment by jbomhold3** [comment]
not able to produce the issue so if you can just do the pr where needed

**Comment by zandermar18** [comment]
Put up a quick PR. I'm also having issues consistently reproducing the issue, so left it with the quick fix. I'd like to do the permanent at some point using a [`BlockingCollection<T>`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.concurrent.blockingcollection-1?view=net-6.0) but need to be able to repro consistently first.
