### ISSUE TITLE
button ListGroupItem uses 'submit' button type by default

### ISSUE THREAD

**Issue by razfriman** [chanan/BlazorStrap#53]
`ListGroupItem` with `ListGroupType="ListGroupType.Button"` needs to set button type to `button`, by default it acts as a submit button, and submits the current form.

---

Reproduction:

When the `ListGroupItem` is clicked:
1.`myWorkingClickHandler` will get called
2. `Save` will also get called

```
<form onsubmit="@Save">     
<ListGroup ListGroupType="ListGroupType.Button">
   <ListGroupItem ListGroupType="ListGroupType.Button" onclick="@myWorkingClickHandler">list group item button</ListGroupItem>
</ListGroup>
<BlazorButton ButtonType="ButtonType.Submit" Color="Color.Primary">Save</BlazorButton>
</form>
```

---

Solution:

Add `type="button"` on the generated HTML for `   <ListGroupItem ListGroupType="ListGroupType.Button">`

**Comment by BlackFenix2** [comment]
I can use my forked branch and submit another PR.

**Comment by BlackFenix2** [comment]
i submitted a PR, https://github.com/chanan/BlazorStrap/pull/55

hopefully this helps.

**Comment by chanan** [comment]
Thanks @BlackFenix2 !
