### ISSUE TITLE
Dismissable alerts do not have an 'X" button

### ISSUE THREAD

**Issue by snapfisher** [chanan/BlazorStrap#536]
You can dismiss the alerts, but the button is a small rectangle that is directly next to the text.  It should be an X that is right justified.  I can get this behavior by copying the example in the documentation.

Version 5.0.105.4262022

**Comment by jbomhold3** [comment]
Output of an alert from blazorstrap
``` html 
<div class="alert alert-info alert-dismissible" role="alert">
<!--!-->
    An example dismissable alert example.
<!--!-->
<button type="button" class="btn-close" aria-label="Close"></button>
</div>
```

Dismissible Alert example from the bootstrap docs.
``` html
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <strong>Holy guacamole!</strong> You should check in on some of those fields below.
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
```

It's outputting correctly according to the example provided. Can you post the rendered html and a screenshot of what your seeing?

**Comment by snapfisher** [comment]
```
<div class="alert alert-success d-flex align-items-center alert-dismissible" role="alert">
	<!--!-->
	<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-info-circle-fill flex-shrink-0 me-2" viewBox="0 0 16 16">
                        <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"></path>
	</svg>
	<!--!-->
            Success!
	<!--!-->
	<button type="button" class="btn-close" aria-label="Close"></button>
</div>
```

**Comment by snapfisher** [comment]
<img width="992" alt="dismissable alert issue" src="https://user-images.githubusercontent.com/45605309/176936976-9e38d2e1-4660-46dd-87fb-83208a8d6383.png">

**Comment by jbomhold3** [comment]
Only way I can reproduce the affect your getting is attempting to use bootstrap 4 vs 5. V5 targets bootstrap 5. Can you double check and make sure you're pulling in bootstrap 5 and not 4. Or that the template you're using if any is compatible with bootstrap 5
> Bootstrap 4
![Bootstrap 4](https://i.gyazo.com/1bc4e70bd79577368545fe9b4f30656e.png)
> Bootstrap 5
![Bootstrap 5](https://i.gyazo.com/55fcdd3ed3dc6aca1a39b2b760b2afaf.png)

**Comment by jbomhold3** [comment]
Please post a sample project if the above isn't correct. Will be faster than just guessing what it could be.

**Comment by snapfisher** [comment]
Ah, fixed.  Thanks for the help.  Note for the next guy, there is a difference between the bootstrap 5.1.3 from the nuget package and the one loaded in visual studio as a client side library from unpkg.  You want the second.
