### ISSUE TITLE
[Question] Can you launch a Modal without a button?

### ISSUE THREAD

**Issue by HeathAndrew** [chanan/BlazorStrap#550]
Hi all, been looking around for a solution but couldn't find an answer anywhere. I was just wondering if it is possible to launch a modal with using a button, as in call the ShowAsync() method from the code section somehow, and if so, how that would be done? 

Cheers.

**Comment by jbomhold3** [comment]
add a @ref="modal" to the modal
then you can call ShowAsync() on it.
{
   private BSModal modal;
}
