### ISSUE TITLE
[Docs] Navbar unusable with dark themes

### ISSUE THREAD

**Issue by lonix1** [chanan/BlazorStrap#551]
The [v5 docs site](https://blazorstrap.io/V5/) allows to change the theme. When any of the dark themes are used - cyborg, darkly, slate, solar, superhero, vapor - the navbar on the left becomes unreadable.

I'm unsure whether this is because of the way the docs site was written, or a flaw in the library itself?

**Comment by jbomhold3** [comment]
The docs are using same CSS file as the official bootstrap docs.  So it has set colors and styles that don't play well with standard loading other themes in. The switcher is just a demo of the functionality. So the simple answer is it's just the docs site. I I removed all the custom styles from the docs it would change the colors correctly.
