### ISSUE TITLE
[Question] Forms inside of dropdowns

### ISSUE THREAD

**Issue by HeathAndrew** [chanan/BlazorStrap#557]
Hi all, I'm looking to put a form inside of a dropdown input similar to what is shown on the standard bootstrap site (https://getbootstrap.com/docs/4.0/components/dropdowns/). I notice on the blazorstrap website the forms section in dropdowns is blank.
Is the functionality there for me and just not shown on the website or has it not been implemented yet? 
Thanks for any help in advance.

**Comment by jbomhold3** [comment]
shown properly in 5.1 docs https://blazorstrap.io/Beta/V5/components/dropdowns  likely just a type in the current docs
