### ISSUE TITLE
Do events work on any controls?

### ISSUE THREAD

**Issue by tsmccartan** [chanan/BlazorStrap#56]
I have events on Button Click, but appears they don't fire anymore with BlazorStrap?  I did see on the home page, Events were not working, but I wanted to confirm, as I see an example onClick in the BlazorButton Sample Page?

Below used to work, but now is not being fired.  Where iRoleIndex is just a Row in a BootStrap table.  AddEditClaim is the Function I have in Code Behind.

onclick="@(e => AddEditClaim(iRoleIndex))"

**Comment by chanan** [comment]
They *should* work - I think if you check the sample site you will see buttons that write to the console.

Having said that, In a recent update of Blazor, events have been changed to use: <code>EventCallback</code> and I have not had a chance to go change all events to use that yet. It seemed to me there were still working the old way using <code>Action</code>, if that is wrong I will try to do this ASAP.

**Comment by tsmccartan** [comment]
Thanks, I did manage to get it to work, apparently you need to add the Event Args for Mouse it it?

onclick="@(e => AddEditRole(e, RoleID))"

Signature for Method in Code Behind
public void AddEditClaim(UIMouseEventArgs e, int iRoleID)

I am not sure why I need to pass in UIMouseEventArgs to every method now?  Standard Bootstrap Buttons and Events I did not need to.

Anyway, no worries, it works great!

Thanks so much!

**Comment by chanan** [comment]
Thanks for the update.

I tried just <code>Action</code> without <code>Action<UIMouseEventArgs></code> and it didnt work. Also, <code>EventCallback</code> is the same. So it looks like that is the only way to go.
