### ISSUE TITLE
Bootstrap classes not working after upgrade to version 5.1.100

### ISSUE THREAD

**Issue by mhdr** [chanan/BlazorStrap#562]
`<BSCol ColumnSmall="6" Column="11">`
For example Column and ColumnSmall are not applied anymore.

**Comment by tony-asu** [comment]
you may need to install [Bootstrap.V5](https://www.nuget.org/packages/BlazorStrap.V5/5.1.100) or [Bootstrap.V4](https://www.nuget.org/packages/BlazorStrap.V4/5.1.100), and add a @using BlazorStrap.V# to your _Imports.razor

or atleast this is what worked for me.

**Comment by jbomhold3** [comment]
Exactly right. Core(Blazorstrap) package is all the events and methods. The render is BlazorStrap.V5 or BlazorStrap.V4 . V5 = Bootstrap 5 , V4 = Bootstrap 4

**Comment by mhdr** [comment]
You are right. Thank you.
@tony-asu 
@jbomhold3
