### ISSUE TITLE
Add Class to <Content>

### ISSUE THREAD

**Issue by digitalgym** [chanan/BlazorStrap#568]
How do we add additional classes to the content element when creating a dropdown?

This don't work ` <Content Class="dropdown-menu-end">`

`<BSDropdown>
                            <Toggler><BSToggle IsButton="true" Class="dropdown-toggle bg-transparent border-0">Open</BSToggle></Toggler>
                            <Content>
                                <BSDropdownItem>Action</BSDropdownItem>
                                <BSDropdownItem>Another action</BSDropdownItem>
                                <BSDropdownItem>Something else here</BSDropdownItem>
                            </Content>
                        </BSDropdown>`

**Comment by jbomhold3** [comment]
Content is render fragment, not a tag. You will have to put it in BSDropdownItem or do something like <Content><div class="yourclass"><BSDropdownItem> if you wanted to have it appear on all drop-down items. or even just add the class to BSDowndown it's self.
