### ISSUE TITLE
How to trigger method call on BsInput user inputs? 

### ISSUE THREAD

**Issue by obriankevin11** [chanan/BlazorStrap#569]
Hi,

How can I get the value be updated when user types text in the input?
Because for now that method is called when user moves focus.

`<BSInput InputType="InputType.Text" InputSize="Size.Small" ValidateOnInput="true" ValueChanged="@((string txt) => OnValueChanged(txt))" />`

Thanks!

**Comment by jbomhold3** [comment]
You were almost there doing this off memory so if it doesn't work let me know will do some more testing and provide a different solution.  
```<BSInput InputType="InputType.Text" InputSize="Size.Small" ValidateOnInput="true" ValueChanged="@((string txt) => OnValueChanged(txt))" value="value"/>```

```C#
@code {
  private string value = String.Empty;
  private void OnValueChanged(string txt)
  {
      value=txt;
      YourCode
  }
}
```
