### ISSUE TITLE
The menu is not displayed or is displayed incompletely

### ISSUE THREAD

**Issue by AmBplus** [chanan/BlazorStrap#570]
in maui blazor and wpf blazor when install package the menu will not shown completely or hidden
in blazor wpf when published the menuitem completly hidden like bellw

![image](https://user-images.githubusercontent.com/96792239/218236234-31f86c6e-7ebe-41f4-84a1-a11f13296074.png)

but when i run into visual studio 
![image](https://user-images.githubusercontent.com/96792239/218236217-4a4bef53-16bf-4070-8aa5-696d5a48a07f.png)

this problem happen with i use package with menuitem defualt blazor

**Comment by jbomhold3** [comment]
This looks like the default Blazor layout can you provide a sample project so I can see what you did here the pictures don't really tell me anything.
