### ISSUE TITLE
BSDataTable - NoData Template - Full Row

### ISSUE THREAD

**Issue by ruthequip** [chanan/BlazorStrap#575]
I am using BSDataTable, and I'm using the NoData template for when my dataset is empty. However, this only fills the first cell of the first row. I was looking through the source and looks like NoData is nested in a BSDataRow so I tried to add mutiple BSTD inside the NoData template but to no avail. Is it possible to make the NoData template occupy a full row?

Also an aside. Looks like the LoadingTemplate is no longer exposed to use?

**Comment by jbomhold3** [comment]
Your looking at the old datatable from V1 correct one is here. https://github.com/chanan/BlazorStrap/blob/master/src/BlazorStrap.V5/Components/Datatable
https://github.com/chanan/BlazorStrap/blob/master/src/BlazorStrap/Shared/Components/Datatable
NoDataColspan=Blah is what your wanting

**Comment by ruthequip** [comment]
Good looking out! That was the ticket!
