### ISSUE TITLE
BSModal - CSS-Class for Content

### ISSUE THREAD

**Issue by EMaderbacher** [chanan/BlazorStrap#578]
I can specify for almost everything an additional CSS class but not for the but not for the Body itself:
```csharp
protected override string? ContentClassBuilder => new CssBuilder("modal-content")
                .AddClass($"bg-{ModalColor.NameToLower()}", ModalColor != BSColor.Default)
                .Build().ToNullString();
```
Is it possible to add therefore an additional parameter?
When it's ok, I can provide a pull request. How shall this parameter be named?

**Comment by jbomhold3** [comment]
Yeah if you want to submit the pr will review it and get it in. Please make sure you add it both to V4 and V5

**Comment by EMaderbacher** [comment]
How shall I Name that property?
Unfortunately ContentClass is used already for Body

**Comment by jbomhold3** [comment]
Let's see the wrapper is just Class
The dialog is DisalogClass
Body class used ContentClass opps

Content without a body is missing a Parameter ModelContextClass probably will be best since I goofed on the body class naming.

**Comment by jbomhold3** [comment]
I see why I did it but should have did it differently don't want to do a breaking change to fix it however
probably add BodyClass and update the getter and setter for contextclass to set and read from the body class
[Parameter] public string? BodyClass { get; set; }
[Obsolete("ContentClass is deprecated, please use BodyClass instead.")]
[Parameter]public string? ContentClass { get => BodyClass set {BodyClasss = value;} }
