### ISSUE TITLE
Can't get multiple select to work.

### ISSUE THREAD

**Issue by SebastianFalborg** [chanan/BlazorStrap#581]
It looks like BSInputBase<TValue> is using this.IsMultipleSelect = typeof (TValue).IsArray;

Microsoft write this about IsArray.

"The IsArray property returns false for the Array class. It also returns false if the current instance is a Type object that represents a collection type or an interface designed to work with collections, such as IEnumerable or IEnumerable<T>.

To check for an array, use code such as:

typeof(Array).IsAssignableFrom(type)

If the current type represents a generic type, or a type parameter in the definition of a generic type or generic method, this property always returns false."

Or maybe something else is wrong. I am using a simple List<> and it is not making it multiple.

**Comment by jbomhold3** [comment]
You have to pass it an array. .net 5 limits if I remember right and we support backward to that version. A list isn't going to work feel free to test and submit a pr if you find an easy workaround that still works in .net 5
