### ISSUE TITLE
How do I get the ElementReference from BsInput

### ISSUE THREAD

**Issue by yaju** [chanan/BlazorStrap#584]
I used 5.1.102-Preview6 of NuGet 

I got an error trying to reference a BsInput via @ref:
<BsInput @ref="Control" />
In the code there is the ElementReference:
ElementReference Control { get; set; }
The error is:
"Error CS0029: cannot implicitly convert type 'BlazorStrap.V5.BsInput<string>' to 'Microsoft.AspNetCore.Components.ElementReference'"

I had a similar issue before
https://github.com/chanan/BlazorStrap/issues/343

**Comment by jbomhold3** [comment]
Ref needs to by the same type as the input.

```html
<BSInput @bind-Value="_blah" @ref="_inputRef"/>
```
```C#
private BSInput _inputRef;

private string _blah = string.Empty;

private async Task DoStuffAsync()
{
     var element = _inputRef.Element; //<---- ElementReference is provided like this.
}

**Comment by yaju** [comment]
Hi Thanks.
Focus can be set to BSInput!

```html
<BSInput @bind-Value="_blah" @ref="_inputRef"/>
```
```cs
private BSInput<string?> _inputRef;

private string _blah = string.Empty;

protected override async Task OnAfterRenderAsync(bool firstRender)
{
     if(_inputRef.Element != null)
         await _inputRef.Element.Value.FocusAsync();
}
```
