### ISSUE TITLE
Modal fails to close and throws promise error

### ISSUE THREAD

**Issue by mjarmstrong** [chanan/BlazorStrap#587]
In latest version of Blazorstrap and Blazorstrap V5, the modal component doesn't close in any scenario; clicking the close button, clicking outside the modal, or clicking a cancel button which calls hideAsync. 

Throws the following error in console...

blazorstrap.js:27 Uncaught (in promise) Error
    at blazorstrap.js:27:20
    
This is even reproducible using the live examples on the BlazorStrap website here: https://blazorstrap.io/V5/V5/components/modal

In any of the live examples, try closing the modal and you'll see the behavior's above.

**Comment by CliveBennett** [comment]
I get a similar issue with latest version in that BSModal.WaitAsync() doesnt return, the modal displays, but system then hangs as WaitAsync() doesnt return

**Comment by jbomhold3** [comment]
What Browser are you using so I can test I do not get the same results as you.

**Comment by jbomhold3** [comment]
line 27 is just a race if the animation fails to start

**Comment by mjarmstrong** [comment]
@jbomhold3 I'm seeing the behavior using Google Chrome - Version 113.0.5672.127 (Official Build) (64-bit). Still seeing the issue in the live examples at the link below as well. Modal opens fine, but doesn't close using close icon, close button, or save changes button. 

https://blazorstrap.io/V5/V5/components/modal
![screenshot](https://github.com/chanan/BlazorStrap/assets/6401739/3b98b029-abc1-43ea-bf99-059124d899bc)

**Comment by mjarmstrong** [comment]
@jbomhold3 - the console error seems to fire anytime I try to close using any of the buttons.

**Comment by jbomhold3** [comment]
By chance, are you getting animations?

**Comment by jbomhold3** [comment]
ok can reproduce if I disable animations on my computer will get it fixed

**Comment by jbomhold3** [comment]
Resolved in    https://www.nuget.org/packages/BlazorStrap/5.1.102.51923
