### ISSUE TITLE
BSModal Nesting/Multi-Modal Support Request

### ISSUE THREAD

**Issue by kalshair** [chanan/BlazorStrap#588]
I am currently working on a project where our users will be creating objects with multiple fields, and will be able to edit those objects. To create these objects, I am currently using a page with modals for selecting each value, as dropdowns are not allowed as per the project requirements. For instance, users need to input a formula from a predetermined list. To accomplish this, I use a modal with a datatable that contains that predetermined list, and they can select and accept one to populate the form field. The final objects populate a sort of 'Recent creations' data table, and clicking one needs to enable editing.

When clicking this, the ideal behavior is that a modal opens, and then clicking a field to edit opens another modal for that field without closing the first modal.

With all this said, it seems Blazored's Modals DO allow for this already. I'd just like a strong integration with Blazorstrap because almost all of my code is already done in Blazorstrap.

**Comment by jbomhold3** [comment]
Just to make sure I understand the requirements correctly.

```html
<BSModal DataId="modal1">
    <Header>Modal Title</Header>
    <Content>Woohoo, you're reading this text in a modal!
              <!-- Nested Modal -->
              <BSModal DataId="nestedModal">
              <Header>Modal Title</Header>
              <Content>My parent stays open because I'm nested</Content>
             </BSModal>
             <!-- END Nested Modal -->
             <BSButton Color="BSColor.Primary" Target="nestedModal">Launch demo modal</BSButton>
      </Content>
</BSModal>
<BSButton Color="BSColor.Primary" Target="modal1">Launch demo modal</BSButton>
```

**Comment by jbomhold3** [comment]
Or are you just wanting a flag that says hey ill close and open this one myself

**Comment by jbomhold3** [comment]
90% sure I addressed your requirements. Added in https://www.nuget.org/packages/BlazorStrap/5.1.103-Preview1a
See https://blazorstrap.io/VNext/V5/components/modal

**Comment by kalshair** [comment]
I am so sorry for missing your comments and all that. I have not tested yet, but based on the documentation, it is exactly what I was hoping for. I really appreciate the assist!!

**Comment by jbomhold3** [comment]
Nested is easy enough since would just have to take the parent and set the parent's param. Multi would require better tracking and indexing open modals. Something I'm going to have to do anyway. Since I want to a point we could do something like var modalId = BlazorStrap.Modals.ShowAsync<ModalComponent>(() => Id.params).  modal.HideAsync()

**Comment by jbomhold3** [comment]
Kinda jotting down notes now for myself

```C#
[Inject] public IBlazorStrap BlazorStrap {get;set;}
private BSModal _modal;
protected override OnInit()
{
       _modal = BlazorStrap.Modals.Add<ModalComponent>((0 => params)
}

public async Task ShowModal()
{
       await _modal.ShowAsync();
       await BlazorStrap.Modals.ShowAsync<SelfHidingModal>(() => params);
}
public async Task HideModal()
{
       await _modal.HideAsync();
}
public Dispose()
{
       BlazorStrap.Modals.Remove(_modal);
}
```

**Comment by jbomhold3** [comment]
BlazorStrap.ForwardClick("data-Id"); already kinda does that. Having statics maybe but would rather add a ShowAsync/HideAsync("data-Id") on the service so it can happen over all toggleable vs just modals

**Comment by kalshair** [comment]
Didn't even know I could do something like call BlazorStrap like that, but the ShowAsync("data-Id") for toggleables thing makes a lot of sense to me.

**Comment by jbomhold3** [comment]
yeah, I need to make copilot document the BlazorStrap/Interop service for me and get it added to the docs lol.
