### ISSUE TITLE
BSOffCanvas: Overflow hidden and some styling wont reset on OffCanvas hidden

### ISSUE THREAD

**Issue by jonathankarlsson88** [chanan/BlazorStrap#592]
When toggle open offcanvas body gets styled with overflow: hidden and some padding to it. 

When closed the styling does not get reset and it still there. 

Therefor its impossible to scroll and content on page gets hidden instead of scrollable. Same issue at your own demo site, just click toggle the offCanvas and the whole page is unscrollable.

`overflow: hidden; padding-right: 17px;`

**Comment by jbomhold3** [comment]
https://www.nuget.org/packages/BlazorStrap/5.1.103-Preview1b

**Comment by jonathankarlsson88** [comment]
Yep its working!

Awsome.
