### ISSUE TITLE
Documentation on how to set a theme?

### ISSUE THREAD

**Issue by gregowahoo** [chanan/BlazorStrap#596]
I can't find any documentation on how to set a theme. Thanks!

This page doesn't help.... https://blazorstrap.io/VNext/V5/themes

**Comment by jbomhold3** [comment]
https://blazorstrap.io/V5/V5/themes. If you're only going to have one theme, don't use this. Just load in the CSS directly. Please note the Advanced part of this did change in the next release. If your using the preview, ignore the example for advanced.

**Comment by gregowahoo** [comment]
Thanks. I finally figured it out. I just spent the day setting the theme last used by the user, upon successfully logging in. Works great. Love BlazorStrap!
