### ISSUE TITLE
Unhandled Error for property BlazorStrapSrc

### ISSUE THREAD

**Issue by coolblue2000** [chanan/BlazorStrap#598]
I am getting the following error despite following the setup docs for a Blazor WASM app

`Unhandled exception rendering component: Cannot provide a value for property 'BlazorStrapSrc' on type 'BlazorStrap.V5.BSContainer'. There is no registered service of type 'BlazorStrap.IBlazorStrap'.`

Does anyone know why this might be happening?

**Comment by jbomhold3** [comment]
You likely missed this step 
3. In Program.cs add
builder.Services.AddBlazorStrap();

**Comment by coolblue2000** [comment]
Do you know what. That is it. However I did have that line of code but it turns out I put it in the Program.cs in the server project rather than the client project....

**Comment by jbomhold3** [comment]
Easy to do when your starting out on the hosted model all good :)
