### ISSUE TITLE
Modal Fade show not working

### ISSUE THREAD

**Issue by yaju** [chanan/BlazorStrap#603]
I use library of BlazorStrap ver 5.2.100-Preview3b
Background of Modal  is not fade out.
![ModalFade](https://github.com/chanan/BlazorStrap/assets/1407467/76d200ca-2632-4394-b076-d56da8f42da4)

BlazorStrap ver 5.1.202.51723 is no problem

**Comment by jbomhold3** [comment]
Your missing `<BSCore>` in your layout

**Comment by yaju** [comment]
Tanks.
Background of Modal is fade out

Remove  _content/BlazorStrap/blazorStrap.js in _host.cshtml
 In your MainLayout after @Body add <BSCore/>

```html:MainLayout.razor
<article class="content px-4">
    @Body
    <BSCore HasToaster="false" />
</article>
 ```

**Comment by vnooli** [comment]
@yaju Issue still persist in 5.2.101 version.
