### ISSUE TITLE
Feature Request: FluentValidation in BSForm Edit Context

### ISSUE THREAD

**Issue by kalshair** [chanan/BlazorStrap#605]
Using Blazorstrap, I find myself faced with one issue: I can't make my page validate completely automatically based on my FluentValidation RuleSets. Is there a way to filter out fields from the EditContext, or set the EditContext validation state and messages manually? If not, could we get those?

**Comment by jbomhold3** [comment]
Please let me know if you're using our FluentValidation extension. What rulesets are you having issues with? Maybe a small example of the issue and I will get it fixed. For the second part of the request in my own project, I copied the code and added a public method to the base type to add errors to fields manually would have to get it working better before I add it into the main extention

**Comment by kalshair** [comment]
I am using your FluentValidation extension. I'm not having issues so much with any specific RuleSet as I am the whole set up.

EditContext has a method called 'Validate' that (as you might expect) validates everything on the page for that EditContext in the BSForm, showing any validation messages. However, it doesn't seem to allow me to pick and choose rulesets from my FluentValidation validator - it just takes all of them. It's not that much of an issue, it turns out, as I can call the Validate Method but actually use my Validator rulesets manually inside the OnSubmit method and check validity like that.

**Comment by jbomhold3** [comment]
I see what you're trying to do now. Yeah can add comma-separated rule set names to the component https://docs.fluentvalidation.net/en/latest/rulesets.html

**Comment by kalshair** [comment]
Thank you very much! This is very much appreciated!

**Comment by jbomhold3** [comment]
https://www.nuget.org/packages/BlazorStrap.Extensions.FluentValidation/2.0.1  
https://blazorstrap.io/VNext/V5/extensions/fluentValidation

Example
``` html
  <FluentValidator TValidator="CustomerValidator" RuleSets="Name,default" />
```

**Comment by kalshair** [comment]
Apologies. I completely forgot to mention that I am currently using the <FluentValidatorInjected> component, not the <FluentValidator> component. Is it the same with that?

**Comment by jbomhold3** [comment]
"I am currently using the component, not the component." huh? As long as you can supply the property via the parameter or reference, it will work. It doesn't create the string array for RuleSets until it validates. So can be done any point before that.

**Comment by kalshair** [comment]
I am once again incredibly sorry. It seems Github ate some of my comments because it thought it was markdown.

I am currently using the "FluentValidatorInjected" component, not the "FluentValidator" component.

**Comment by jbomhold3** [comment]
Yes it will work with that it uses the same base type as FluentValidator

**Comment by kalshair** [comment]
Thank you very, VERY much for all this! It is much appreciated.

**Comment by kalshair** [comment]
Just tested it. It seems to work wonderfully. Thanks again!
