### ISSUE TITLE
Question: NotifyFieldChanged in BlazorStrapInputBase

### ISSUE THREAD

**Issue by EMaderbacher** [chanan/BlazorStrap#608]
What is the purpose of NotifyFieldChanged at https://github.com/chanan/BlazorStrap/blob/610cef351fb7de5a78aec71064a521588e7a7ff1/src/BlazorStrap/Shared/Components/Forms/BlazorStrapInputBase.cs#L153C17-L153C75?
In my case `EditContext.IsModified()` returns `true` after I'm running `EditContext.Validate()`, even when no value has been changed

**Comment by jbomhold3** [comment]
Validate modifies the field it sets as valid or invalid. even if no data is entered
