### ISSUE TITLE
Virtualization of BSDataTable

### ISSUE THREAD

**Issue by sveinl** [chanan/BlazorStrap#610]
I am looking into using BlazorStrap. 
Was looking for virtualization for datatables as my data could grow a bit.
Are there any virtualization built into for example BSDataTable?

**Comment by jbomhold3** [comment]
Only pagination you can prefetch the number of rows and call your offsets when the page changes. See last example on https://blazorstrap.io/V5/V5/content/tables or Data Table Example using FetchData example. You can also use https://learn.microsoft.com/en-us/aspnet/core/blazor/components/quickgrid?view=aspnetcore-8.0. 

I have no plans to add virtualization at the moment but would take a PR that adds it

**Comment by jbomhold3** [comment]
See 
https://blazorstrap.io/VNext/V5/components/datagrid
