### ISSUE TITLE
Exception "System.NullReferenceException: Unable to load module."

### ISSUE THREAD

**Issue by EMaderbacher** [chanan/BlazorStrap#617]
I get very often this exception:
```
System.NullReferenceException: Unable to load module.
   at BlazorStrap.Service.BlazorStrapInterop.PreloadModuleAsync(Nullable`1 cancellationToken)
   at BlazorStrap.Shared.Components.BSCoreBase.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```
What I've seen in webserver logs this happens when
* The webpage is opened
* The webpage is closed immediatelly, is refreshed or any other reason that the circuit has been closed
* The exception is always shown exactly 1 minute after the webpage was opened

The code throwing the exception is found here: https://github.com/EMaderbacher/BlazorStrap/blob/cb2654ed79fac96290dbfe6d78019864ffc2cb1a/src/BlazorStrap/Service/BlazorStrapInterop.cs#L325
In other places a null check is made and no exception is thrown, like here: https://github.com/EMaderbacher/BlazorStrap/blob/cb2654ed79fac96290dbfe6d78019864ffc2cb1a/src/BlazorStrap/Service/BlazorStrapInterop.cs#L337
Any chance that the exception isn't thrown and instead of that a null check is made?

The same exception is thrown here too: https://github.com/EMaderbacher/BlazorStrap/blob/cb2654ed79fac96290dbfe6d78019864ffc2cb1a/src/BlazorStrap/Service/BlazorStrapInterop.cs#L307
May a similar exception is thrown in other places too?

**Comment by jbomhold3** [comment]
Should be safe to just return null for the preloaded.
On AnimateCarouselAsync returning false on null should just keep the slide
from changing if I remember correctly. Though not sure why the preloading
is getting called at all right now from a state the js runtime isn't ready.

**Comment by jbomhold3** [comment]
I removed the thrown exceptions.
The preloader doesn't care if it returns null and likely never should have.
AnimateCarouselAsync will not just return true bypassing the animation.

**Comment by jbomhold3** [comment]
I also wrapped NextAsync and BackAsync in a try-catch. This is because when navigating the timer might have just triggered and the task is still working. Since the elements are gone the array was out of range.
