### ISSUE TITLE
Most Controls Won't Work on iOS Devices

### ISSUE THREAD

**Issue by xJonathanLEI** [chanan/BlazorStrap#62]
It seems that the `onclick` event won't be fired on iOS devices when the rendered `<a>` tag doesn't have a `href` prop. Most controls (pagination, tabs, etc...) are broken.

Adding `href="javascript:;"` to `<a>` would solve the issue. I might as well submit a PR.

**Comment by chanan** [comment]
Thanks for letting me know. I will fix this after I manage to finally upgrade to preview 6.

**Comment by chanan** [comment]
Sorry for the delay on implementing this. I took a look at it and wasn't sure where all the places that would need to be changed and how to tackle it. I will get this done though.

**Comment by jbomhold3** [comment]
Check all Componets with click events to make the apple gods happy.

**Comment by jbomhold3** [comment]
Fixed in next release
