### ISSUE TITLE
The attribute 'onmouseleave' was matched by multiple event handler attributes.

### ISSUE THREAD

**Issue by 1fabi0** [chanan/BlazorStrap#621]
When migrating a project from .net 6 to .net 8 I get the error message: "The attribute 'onmouseleave' was matched by multiple event handler attributes. Duplicates: BlazorStrap.EventHandlers Microsoft.AspNetCore.Components.Web.EventHandler" only for the onmouseleave event.

**Comment by jbomhold3** [comment]
I have not seen this myself. What package version are you using?

**Comment by 1fabi0** [comment]
The Latest  
Version: 5.2.103.120724 and 5.2.103 for the V5 Project

**Comment by 1fabi0** [comment]
I have an div that looks like the following
``` html
    <div class="shadow position-absolute p-2 d-flex flex-wrap justify-content-center"
         style="border: 1px solid #dee2e6; border-radius: 4px; width: 300px; background: #fff; z-index: 9999;"
         @onmouseleave="(() => IsOpen = false)">
        Some Content here
   </div>
```

**Comment by jbomhold3** [comment]
Ok look's like mouseleave/enter were added in .net 7 this is a easy fix will get it pushed

**Comment by jbomhold3** [comment]
https://www.nuget.org/packages/BlazorStrap/5.2.103.121624 give it 10 minutes to list

**Comment by 1fabi0** [comment]
Thanks a lot, I really appreciate it

**Comment by jbomhold3** [comment]
Anytime
