### ISSUE TITLE
Migrate from Action to EventCallback

### ISSUE THREAD

**Issue by IvanJosipovic** [chanan/BlazorStrap#64]
The new guidance is to use EventCallback instead of Action. 
See for more details https://github.com/aspnet/AspNetCore/issues/6351

Since Preview 6, the use of Action is also causing the following errors to show up:
```
System.ArgumentException: Object of type 'Microsoft.AspNetCore.Components.EventCallback`1[Microsoft.AspNetCore.Components.UIMouseEventArgs]' cannot be converted to type 'System.Action`1[Microsoft.AspNetCore.Components.UIMouseEventArgs]'.
   at System.RuntimeType.CheckValue (System.Object value, System.Reflection.Binder binder, System.Globalization.CultureInfo culture, System.Reflection.BindingFlags invokeAttr) <0x2778e18 + 0x000c6> in <917eebd1d479468d957d9e8362baba7d>:0 
```

**Comment by chanan** [comment]
I did change some of them on migration, but didnt do a search on the full project. Doing the rest now.

**Comment by IvanJosipovic** [comment]
I just sent a PR which covers most of the migration. 

Not complete:
CarouselIndicators.razor
Modal.razor

Both of these trigger the event within a setter, I can't seem to get this to work with EventCallBack as its async.

**Comment by chanan** [comment]
Fixed those two as well. Will create a new build soon, have a few other fixes to do. Thanks for the PR!
