### ISSUE TITLE
Modal @bind-IsOpen lockup

### ISSUE THREAD

**Issue by IvanJosipovic** [chanan/BlazorStrap#69]
Binding to Modal IsOpen causes Client Side Blazor to lock up.

Blazor: 3.0.0-preview6.19307.2
BlazorStrap: 1.0.0-preview6-12

### Repro
Click on the Show Modal button. Blazor will freeze

```
@page "/Test"

<Modal @bind-IsOpen="@ModalIsOpen">
    <ModalHeader>Modal</ModalHeader>
    <ModalBody>Test</ModalBody>
</Modal>

<button @onclick="@(() => ModalIsOpen = true)">Show Modal</button>

@code {
    private bool ModalIsOpen { get;set; }
}
```

**Comment by chanan** [comment]
Weird. Something to do with the binding syntax maybe? I will take a look tonight

**Comment by IvanJosipovic** [comment]
This is caused by the InvokeAsync in the Model.razor setter. Not sure why or how to fix it yet.
```
private bool _isOpen;
[Parameter]
private bool IsOpen
{
    get
    {
        return _isOpen;
    }
    set
    {
        _isOpen = value;
        IsOpenChanged.InvokeAsync(_isOpen); // commenting this out fixes the issue
    }
}
```

**Comment by chanan** [comment]
not sure why, even though sync/async mixes. 

But, one thing i might try to see if it works is to try to represent the IsOpen in SetParametersAsync instead of a property and at least see if that is the reason

**Comment by IvanJosipovic** [comment]
I figured it out. I guess its running in an infinite loop. PR incoming.

Fix:
```
private bool _isOpen;
[Parameter]
private bool IsOpen
{
    get
    {
        return _isOpen;
    }
    set
    {
        if (value != _isOpen)
        {
            _isOpen = value;
            IsOpenChanged.InvokeAsync(_isOpen);
        }
    }
}
```
