### ISSUE TITLE
ItemsPerPage property on Carousel

### ISSUE THREAD

**Issue by desalbres** [chanan/BlazorStrap#77]
Hello,

Could you add a ItemsPerPage or similar property on Carousel ? Because I need to display more than an item at a time. It would be really cool!

By the way, BlazorStrap are reallly great components, good job !

Many thanks,

Raphaël

**Comment by chanan** [comment]
I dont think that would be possible. Ultimately BlazorStrap is creating divs with bootstrap class on them, so a Carousel with item becomes this (https://getbootstrap.com/docs/4.3/components/carousel/):

```
<div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
        <img src="..." class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="..." class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="..." class="d-block w-100" alt="...">
    </div>
  </div>
</div>
```
more divs with `div class="carousel-item"` will just become more items.

However, the items are just divs as you see above, can you not put the content of more "items" into one?

**Comment by desalbres** [comment]
Hello Chanan,
Thanks for your reply, I will test your solution ASAP !!!

________________________________
De : Chanan Braunstein <notifications@github.com>
Envoyé : Thursday, July 4, 2019 4:32:30 PM
À : chanan/BlazorStrap
Cc : Raphaël Desalbres; Author
Objet : Re: [chanan/BlazorStrap] ItemsPerPage property on Carousel (#77)


I dont think that would be possible. Ultimately BlazorStrap is creating divs with bootstrap class on them, so a Carousel with item becomes this (https://getbootstrap.com/docs/4.3/components/carousel/):

<div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
        <img src="..." class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="..." class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="..." class="d-block w-100" alt="...">
    </div>
  </div>
</div>


more divs with div class="carousel-item" will just become more items.

However, the items are just divs as you see above, can you not put the content of more "items" into one?

**Comment by desalbres** [comment]
Hello,
If there's someone interested, I ended up using that code:
@if (selOptions != null)
    {
    <Carousel NumberOfItems="TotalItems" @bind-ActiveIndex="@ActiveIndex" PauseOnHover="true">        
        <div class="carousel-inner">
            @for (int i = 0; i <= selOptions.Count() / PAGE_SIZE; i++)
            {
            <div class="carousel-item @(ActiveIndex==i ? "active":"")">                
                    <div class="row">
                        @foreach (var j in selOptions.Skip(i * PAGE_SIZE).Take(PAGE_SIZE))
                        {
                            <div class="col">
                                <img class="slide"...>
								<div>...more stuff</div>
							<div>
                        }
                    </div>
            </div>
            }
        </div>
        <CarouselControl CarouselDirection="CarouselDirection.Previous" NumberOfItems="@TotalItems" @bind-ActiveIndex="@ActiveIndex" />
        <CarouselControl CarouselDirection="CarouselDirection.Next" NumberOfItems="TotalItems" @bind-ActiveIndex="@ActiveIndex" />
    </Carousel>
}
@code
{
private const int PAGE_SIZE= 4;
        private int TotalItems
        {
            get
            {
                return (int)Math.Ceiling((double)selOptions.Count() / PAGE_SIZE);
            }
        }


        private int _activeIndex;
        int ActiveIndex
        {
            get => _activeIndex;
            set {
                _activeIndex = value; StateHasChanged();
            }
        }
        public List<int> selOptions { get; set; }
}

**Comment by desalbres** [comment]
Hello,
If there's someone interested, I ended up using that code:
@if (selOptions != null)
    {
    <Carousel NumberOfItems="TotalItems" @bind-ActiveIndex="@ActiveIndex" PauseOnHover="true">        
        <div class="carousel-inner">
            @for (int i = 0; i <= selOptions.Count() / PAGE_SIZE; i++)
            {
            <div class="carousel-item @(ActiveIndex==i ? "active":"")">                
                    <div class="row">
                        @foreach (var j in selOptions.Skip(i * PAGE_SIZE).Take(PAGE_SIZE))
                        {
                            <div class="col">
                                <img class="slide"...>
								<div>...more stuff</div>
							<div>
                        }
                    </div>
            </div>
            }
        </div>
        <CarouselControl CarouselDirection="CarouselDirection.Previous" NumberOfItems="@TotalItems" @bind-ActiveIndex="@ActiveIndex" />
        <CarouselControl CarouselDirection="CarouselDirection.Next" NumberOfItems="TotalItems" @bind-ActiveIndex="@ActiveIndex" />
    </Carousel>
}
@code
{
private const int PAGE_SIZE= 4;
        private int TotalItems
        {
            get
            {
                return (int)Math.Ceiling((double)selOptions.Count() / PAGE_SIZE);
            }
        }


        private int _activeIndex;
        int ActiveIndex
        {
            get => _activeIndex;
            set {
                _activeIndex = value; StateHasChanged();
            }
        }
        public List<int> selOptions { get; set; }
}

**Comment by chanan** [comment]
Thanks, glad it worked out for you! Please let me know if you have any more questions, closing this specific issue now.

**Comment by desalbres** [comment]
Hi Chanan, could you provide a sample of several items per page as I couldn’t get it to work with the latest version, I think something is broken. I’d like to avoid using owlCarousel that has dependency on JQuery/JavaScript. Many thanks, Raphaël
