### ISSUE TITLE
Dynamic tabs on click stops working

### ISSUE THREAD

**Issue by digitalgym** [chanan/BlazorStrap#79]
when generating a tab menu via a loop the events specifically on click stop firing. I haven’t seen an example using tabs and tab pane generated dynamically, has anyone else experienced this?

**Comment by chanan** [comment]
Can you give a code example please?

**Comment by digitalgym** [comment]
An example would be a list of categories, each category relates to a tab and a corresponding tab panel, each tab has an onclick event. When this renders the tabs lose their click event. When tabs are added through markup they work as expected, the issue seems directly related to tabs created dynamically.

` <BlazorNav IsTabs>
        @foreach (var c in categories)
        {
            <BlazorNavLink onclick="@(e=> onclick1(e,c))" IsActive="@(activeCat == c)">@c.Title</BlazorNavLink>
        }
    </BlazorNav>
    <TabContent>
        @foreach (var c in categories)
        {
            <TabPane IsOpen="@(activeCat == c)">
                <Row>
                    @foreach (var inner in c.Content)
                    {
                        <BlazorCol>
                            <Card>
                                <Card CardType="CardType.Body">
                                    <Card CardType="CardType.Title">Title</Card>
                                    <Card CardType="CardType.Subtitle">Card subtitle</Card>
                                </Card>
                                <Card CardType="CardType.Image" src="https://via.placeholder.com/286x180" alt="Card image cap" />
                                <Card CardType="CardType.Body">
                                    <Card CardType="CardType.Text">Some quick example text to build on the card title and make up the bulk of the card's content.</Card>
                                    <Card CardType="CardType.Link" href="#">Card Link</Card>
                                    <Card CardType="CardType.Link" href="#">Another Link</Card>
                                </Card>
                            </Card>
                        </BlazorCol>
                    }
                </Row>
            </TabPane>
        }
    </TabContent>`

**Comment by chanan** [comment]
Thanks for the Repro. I will take a look at it this weekend

**Comment by digitalgym** [comment]
Any idea what is causing this? There doesn't seem to be anything obvious and the NavLink component is very basic.

**Comment by chanan** [comment]
This worked for me, let me know how it works for you:

```
@page "/samples/navbars"

<BlazorNav IsTabs> 
    @foreach (var c in categories)
    {
        <BlazorNavLink @onclick="@((e) => onclick1(e, c))" IsActive="@(activeCat == c)">@c.Title</BlazorNavLink>
    } 
</BlazorNav> 

<TabContent> 
    @foreach (var c in categories)
    {
        <TabPane IsOpen="@(activeCat == c)"> 
            <Row> 
                @foreach (var inner in c.Content)
                {
                    <BlazorCol> 
                        <Card> 
                            <Card CardType="CardType.Body"> 
                                <Card CardType="CardType.Title">Title: @inner.Title</Card> 
                                <Card CardType="CardType.Subtitle">Category: @c.Title</Card> 
                            </Card> 
                            <Card CardType="CardType.Image" src="https://via.placeholder.com/286x180" alt="Card image cap" /> 
                            <Card CardType="CardType.Body">
                                <Card CardType="CardType.Text">Some quick example text to build on the card title and make up the bulk of the card's content.</Card> 
                                <Card CardType="CardType.Link" href="#">Card Link</Card> 
                                <Card CardType="CardType.Link" href="#">Another Link</Card> 
                            </Card> 
                        </Card> 
                    </BlazorCol>
                } 
            </Row>
        </TabPane>
    } 
</TabContent>


@code {
    List<Category> categories { get; set; }
    Category activeCat { get; set; }

    protected override void OnInit()
    {
        var content = new List<Content> {
            new Content {
                Title = "Content blog 1"
            },
            new Content {
                Title = "Content title listing 1"
            },
            new Content {
                Title = "Content blog 2"
            },
            new Content {
                Title = "Content blog 3"
            }
        };

        categories = new List<Category> {
            new Category {
                Content = content, Title = "Category 1" },
            new Category {
                Content = content, Title = "Category 2" }

        };

        activeCat = categories.First();

        base.OnInit();
    }


    void onclick1(UIMouseEventArgs e, Category c)
    {
        activeCat = c;
    }

    class Category
    {
        public List<Content> Content { get; set; }
        public string Title { get; set; }
    }

    class Content 
    {
        public Category Cat { get; set; }
        public string Title { get; set; }
    }
}
```

**Comment by digitalgym** [comment]
How do you get this to work without escaping @ as with "@onclick"?

**Comment by chanan** [comment]
Not sure what you mean

**Comment by chanan** [comment]
I am closing this because I was able to get it working with the above code. If you still are having issues let us know
