### ISSUE TITLE
Rework class string creation

### ISSUE THREAD

**Issue by chanan** [chanan/BlazorStrap#80]
Either directly using: https://github.com/EdCharbeneau/CssBuilder or similar to it.

**Comment by chucker** [comment]
I feel like Ed's CssBuilder is still a bit primitive (it doesn't _really_ understand classes in terms of tokens), but quite a step up over what we have now.

**Comment by chanan** [comment]
To be honest, didn't look at it yet, just put the link here so I don't forget where it is.

Creating our own shouldn't be too hard and I prefer not to rely on too many outside libraries if possible in case of upgrades/bugs etc.

**Comment by chanan** [comment]
After some thought, I am going to try and use Ed's CssBuilder for now. I would like to try and use it and if find anything that is missing send PRs and help the community in general. If worse comes to worse, we can always replace it.

**Comment by chanan** [comment]
Done in 1.0.0-preview6-19
