### ISSUE TITLE
Whitespace in sample

### ISSUE THREAD

**Issue by 1mpetuous** [chanan/BlazorStrap#87]
I'm a complete beginner at Blazor / ASP, but I was only able to compile the example source code after removing whitespace in the "@using BlazorStrap.util" so the @implements IDisposable could be parsed in Carousel.razor.  Just wanted to mention this in case it was unintentional.

**Comment by jbomhold3** [comment]
Blazorstrap project carousel.razor line 3

**Comment by jbomhold3** [comment]
Fixed with https://github.com/chanan/BlazorStrap/pull/91

**Comment by chanan** [comment]
Fixed in 1.0.0-preview6-18
