### ISSUE TITLE
Input Patterns missing?

### ISSUE THREAD

**Issue by endeffects** [chanan/BlazorStrap#88]
Do your input controls support regex patterns to disallow entering not matching characters?

**Comment by chanan** [comment]
Can you explain exactly what you are looking for? It sounds like that this might be something outside of scope of BlazorStrap. I think what you want to do is create your own component that wraps a BlazorStrap Input something like this (pseudo code):

```
<PatternInput InputPattern="Some Regex?" @bind-value="@value">
  <BlazorInput @bind-value="@myvalue" />
</PatternInput>

@code {
  //Code here to check if value matches the regex and then assign it to myvalue 
}
```

Is that what you mean?

If so, then like I said, I dont BlazorStrap should supply that (having said that, if you supply a PR... 

However, just so you know, binding is still a bit shaky in BlazorStrap, so you might run into problems implementing, but tell me how it goes.

**Comment by endeffects** [comment]
No, i was talking about this standard pattern option for input controls:
https://www.w3schools.com/tags/att_input_pattern.asp

**Comment by endeffects** [comment]
But this works on your controls too, i just used the wrong input type on my button. It has to be submit. Sorry.
