### ISSUE TITLE
Documentation bugs

### ISSUE THREAD

**Issue by conficient** [chanan/BlazorStrap#9]
Just a few notes on the documentation:
 * the `h3` tags could do with a padding-top or margin-top, they are often up against the example of the previous section, which looks confusing?
 * alerts: the "Dismissing" example is not rendering?

**Comment by chanan** [comment]
I will take a look at making the docs look better and the alert showing, however, that example will not work in the doc site since it run on Blazor, and the docs are static (for now).

**Comment by chanan** [comment]
Fixed
