### ISSUE TITLE
People are using BlazorStrap!

### ISSUE THREAD

**Issue by chanan** [chanan/BlazorStrap#92]
People are actually using BlazorStrap in the wild! Does anyone want a page on the documentation site (or the readme) linking their projects?

**Comment by sfmskywalker** [comment]
I'm working on my first Blazor-powered project. Once we go live I would love a link to it on the project site :D

Thanks for such this awesome library!

**Comment by chanan** [comment]
@sfmskywalker Yes, post a public project online and we will add a place(s) to list your project.

And thanks for the compliment, its great to see people use it and kudus to @jbomhold3 who has done most of the work lately!
