### ISSUE TITLE
Button ClickHandler doesn't work in SSB

### ISSUE THREAD

**Issue by chanan** [chanan/BlazorStrap#93]

**Comment by chanan** [comment]
In SSB mode, OnClick for BlazorButton doesn't work

**Comment by jbomhold3** [comment]
preview 7 anyone? it's getting confusing to debug things. a space matters on one person pc and not other and OnClick vs onclick matters to some and not others. fun fun

**Comment by chanan** [comment]
@jbomhold3 Are you saying that you looked into it and its due to casing of onclick? I haven't had a chance to look into this yet, I am in the middle of refactoring the class string (#80 )

**Comment by jbomhold3** [comment]
I can't repo it works just fine for me. Only thing I'm seeing is its all lower case but called like OnClick..  might be where your running into a issue.

**Comment by chanan** [comment]
Thanks for checking. Its maddening that Blazor works differently on different places... I hope it settles down soon.

**Comment by chanan** [comment]
duh, my bad, "Button was clicked!" shows up in the "ASP.Net Core Web Server" output pane in Visual Studio. I forgot and was looking in the browser console.
