### ISSUE TITLE
DynamicElement 

### ISSUE THREAD

**Issue by jbomhold3** [chanan/BlazorStrap#98]
Can you split DynamicElement into its own project. Would like to use it on other projects i'm working on.   Then BlazostrapComponentBase becomes DynamicComponentBase

**Comment by chanan** [comment]
Yes, although, I was trying to figure out if it is even useful going forward if in preview7 they add "splat"?

But if you want it, I will do it right after I finish the refactor to use CssBuilder (almost done)

**Comment by jbomhold3** [comment]
Didn't see they were doing that. In that case i wouldn't do the extra work. I can just copy and paste it for now. We are far to close to p7

**Comment by chanan** [comment]
I will leave this open in case we want to revisit this after we see preview7

Here is the aspnet issue: https://github.com/aspnet/AspNetCore/issues/5071

**Comment by jbomhold3** [comment]
Got to love when github refreshes slow

**Comment by jbomhold3** [comment]
Still going to need this because of the tag name... But far smaller

``` C#
  public class DynamicElement : ComponentBase
    {
        /// <summary>
        /// Gets or sets the name of the element to render.
        /// </summary>
        [Parameter]public string TagName { get; set; }

        
        [Parameter] private RenderFragment ChildContent { get; set; }
        [Parameter(CaptureUnmatchedValues =true)]
        private IDictionary<string, object> ExtraParams { get; set; }

        protected override void BuildRenderTree(RenderTreeBuilder builder)
        {
            base.BuildRenderTree(builder);
            builder.OpenElement(0, TagName);
            builder.AddMultipleAttributes(1, ExtraParams);
            builder.AddContent(3, ChildContent);
            builder.CloseElement();
        }
    }
```

**Comment by chanan** [comment]
No problem. I will make a package tomorrow morning. Not sure how to do it but if you want I can make you a commiter on theat repo. Let me know

**Comment by jbomhold3** [comment]
Do you have discord or skype? My info is in a PM on gitter

**Comment by chanan** [comment]
Skype should work. I will message you in the morning (US MDT)

**Comment by chanan** [comment]
After talking to @jbomhold3 some more, we decided to move forward with this once preview7 gets released

**Comment by chanan** [comment]
@jbomhold3 Since we are now in 1.0 timeframe, what are your thoughts on this one?

**Comment by jbomhold3** [comment]
it's useful still. Would be nice to be able to use it in another library without having to include all of blazorstrap
