### ISSUE TITLE
Where can I get the necessary js files for server-side blazor project

### ISSUE THREAD

**Issue by howardgod** [chanan/BlazorStrap#99]
I follow the document to _Host.cshtml, and there're three necessary JS files. However, I can only find blazorStrap.js within BlazorStrap\wwwroot\. 

So did I misunderstand the document? Or there's a release package include those js files?

BTW, what's the "_content/" means in <script src="_content/BlazorStrap/blazorStrap.js"></script> for example.

Thank you,

Howard

**Comment by chanan** [comment]
Everything is included.

You should only need to change your `_Host.cshtml` like the Sample project: https://github.com/chanan/BlazorStrap/blob/master/src/ServerSideSample/Pages/_Host.cshtml#L29-L30

**Comment by howardgod** [comment]
So does the "_content" keyword somehow link to the BlazorStrap.dll?

**Comment by chanan** [comment]
Yes, that is correct. See here: https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-3.0&tabs=visual-studio#create-an-rcl-with-static-assets

**Comment by howardgod** [comment]
Thank you very much

**Comment by chanan** [comment]
No problem! Hope you enjoy the library, let me know of any problems.

**Comment by woodste36** [comment]
Hey @chanan,

styled.js seems to be missing in the project.  I first noticed I was getting 404 errors in the console when running my project. Is it supposed to be in the wwwroot folder with the other files?

**Comment by chanan** [comment]
BlazorStyled is not needed, its just used for the Documentation site. We are updating our _Host.cshtml to reflect that in a comment

**Comment by woodste36** [comment]
Okay great.
